Multiscale: multiscale::analysis::ClusterDetector Class Reference
multiscale::analysis::ClusterDetector Class Reference abstract
Class for detecting clusters in 2D images.
#include <ClusterDetector.hpp>
Public Member Functions
ClusterDetector (int maxPileupNumber, double maxPileupIntensity, bool debugMode=false)
virtual ~ClusterDetector ()
double getEps ()
Get the value of the clustering algorithm parameter eps.
int getMinPoints ()
Get the value of the clustering algorithm parameter MinPoints.
vector< Cluster > const & getClusters ()
Get a const reference to the vector of detected clusters.
void setEps (double eps)
Set the value of the clustering algorithm parameter eps.
void setMinPoints (int minPoints)
Set the value of the clustering algorithm parameter MinPoints.
Public Member Functions inherited from multiscale::analysis::Detector
Detector (bool debugMode=false)
virtual ~Detector ()
void detect (const Mat &inputImage)
Run the detection procedure on the given image.
void outputResults (const string &outputFilepath)
Output the results to the given file.
Protected Member Functions
void initialiseDetectorSpecificFields () override
Initialise clustering values.
void createDetectorSpecificTrackbars () override
Create the trackbars.
void clearPreviousDetectionResults () override
Clear the clusters from the previous detection.
void processImageAndDetect () override
Process the provided image and detect clusters in it.
virtual void detectEntitiesInImage (vector< Entity > &entities)=0
Detect the entities in the image.
void detectAndAnalyseClusters (const vector< Entity > &entities, vector< Cluster > &clusters)
Detect and analyse the clusters of entities in the image.
void detectClusters (const vector< Entity > &entities, vector< int > &clusterIndexes, int &nrOfClusters)
Detect the clusters of entities in the image.
vector< shared_ptr< DataPoint > > convertEntities (const vector< Entity > &entities)
Convert the entities to the format required by the DBSCAN class.
void convertNonPiledUpEntities (const vector< Entity > &entities, vector< shared_ptr< DataPoint > > &dataPoints)
Convert the non pile up entities to the format required by the DBSCAN class.
void convertPiledUpEntities (const vector< Entity > &entities, vector< shared_ptr< DataPoint > > &dataPoints)
Convert the entities to the required format by the DBSCAN class.
void addEntitiesToClusters (const vector< Entity > &entities, const vector< int > &clusterIndexes, int nrOfClusters, vector< Cluster > &clusters)
Add the entities to the clusters as indicated by the clusterIndexes parameter.
void analyseClusters (vector< Cluster > &clusters)
Analyse the clusters.
void analyseClustersOriginDependentValues (vector< Cluster > &clusters)
Analyse the clusters and compute the origin dependent values.
void updateClusterOriginDependentValues (Cluster &cluster, const vector< Point > &clusterConvexHull)
Update the cluster and compute the origin dependent values considering the convex hull.
vector< Point > getClusterConvexHull (Cluster &cluster)
Return the convex hull of the given cluster.
double computeClusterednessIndex (const vector< Cluster > &clusters)
Compute the clusteredness index for all the entities detected in the image.
double computeAveragePileUpDegree (vector< Cluster > &clusters)
Compute the average pile up degree for all entities in the image.
void outputResultsToCsvFile (ofstream &fout) override
Output the information computed for the clusters to a csv file.
double convertEpsValue ()
Convert the value of eps from integer to double.
int getValidMinPointsValue ()
Return non-zero value for minPoints.
Protected Member Functions inherited from multiscale::analysis::Detector
void initialise ()
Initialisation function for the class.
void initialiseDetectorSpecificFieldsIfNotSet ()
Initialisation of the detector specific values in case they were not set.
void setDetectorSpecificFieldsInitialisationFlag (bool flag=true)
Set the detector specific fields initialisation flag to true.
void initialiseImageDependentFields ()
Initialisation of the image dependent values.
virtual void initialiseDetectorSpecificImageDependentFields ()=0
Initialisation of the detector specific image dependent values.
void initialiseImageOrigin ()
bool isValidInputImage (const Mat &inputImage)
Check if the image is valid.
void detect ()
Run the detection procedure.
void detectInDebugMode ()
Run the detection procedure when in debug mode.
void detectInReleaseMode ()
Run the detection procedure when in release mode (i.e. non-debug mode)
double polygonAngle (const vector< Point > &polygon, unsigned int closestPointIndex)
Compute the angle of the polygon.
double polygonAngle (const vector< Point > &polygonConvexHull, const Point &closestPoint)
Compute the angle of the polygon.
void minAreaRectCentre (const vector< Point > &polygon, Point &centre)
Get the centre of the minimum area bounding rectangle.
void findGoodPointsForAngle (const vector< Point > &polygonConvexHull, const Point &boundingRectCentre, const Point &closestPoint, vector< Point > &goodPointsForAngle)
Find the points for determining the angle of the polygon.
void findGoodIntersectionPoints (const vector< Point > &polygonConvexHull, const Point &edgePointA, const Point &edgePointB, vector< Point > &goodPointsForAngle)
Find good intersection points for computing the angle of the polygon.
void displayResultsInWindow ()
Display the results in a window.
void outputResultsToFile ()
Output the results to file(s)
virtual void outputResultsToImage ()=0
Output the results to an image.
void storeOutputImageOnDisk ()
Store the image with the output results on disk.
void outputResultsToCsvFile ()
Output the results to a file.
void createTrackbars ()
Create the trackbars which allow the user to change the values of the parameters.
void createTrackbarsWindow ()
Create the window in which the trackbars are placed.
void processPressedKeyRequest (char &pressedKey)
Process the request of the user by pressing the key.
void displayImage (const Mat &image, const string &windowName)
Display an image in a particular window.
void printOutputErrorMessage ()
Print error message, because the detect method was not called before calling the output method.
Protected Attributes
double clusterednessIndex
double avgPileUpDegree
double entityPileupDegree
int eps
int minPoints
vector< Cluster > clusters
Protected Attributes inherited from multiscale::analysis::Detector
Mat image
string outputFilepath
bool debugMode
Mat outputImage
bool detectMethodCalled
bool detectorSpecificFieldsInitialised
Point origin
Detailed Description
Class for detecting clusters in 2D images.
Definition at line 34 of file ClusterDetector.hpp.
Constructor & Destructor Documentation
ClusterDetector::ClusterDetector (int maxPileupNumber, double maxPileupIntensity, bool debugMode = false)
Parameters
debugMode Flag indicating if detector should run in debug mode or not
maxPileupNumber The maximum number of entities which can occupy a grid position at the same time
maxPileupIntensity The grayscale intensity of a maximally piled up grid position
Definition at line 15 of file ClusterDetector.cpp.
References avgPileUpDegree, clusterednessIndex, entityPileupDegree, eps, and minPoints.
ClusterDetector::~ClusterDetector () virtual
Definition at line 25 of file ClusterDetector.cpp.
Member Function Documentation
void ClusterDetector::addEntitiesToClusters (const vector< Entity > & entities, const vector< int > & clusterIndexes, int nrOfClusters, vector< Cluster > & clusters) protected
Add the entities to the clusters as indicated by the clusterIndexes parameter.
Add the entities to the clusters as indicated by the clusterIndexes parameter
Parameters
entities Entities detected in the image
clusterIndexes Indexes to which cluster each entity belongs
nrOfClusters Total number of clusters
clusters Collection of clusters, each one with the updated measures
Definition at line 111 of file ClusterDetector.cpp.
Referenced by detectAndAnalyseClusters().
void ClusterDetector::analyseClusters (vector< Cluster > & clusters) protected
Analyse the clusters.
Analyse the clusters and compute the angle and distance from the centre, average clusteredness degree and pile up degree
Parameters
clusters Collection of clusters, each one with the updated measures
Definition at line 122 of file ClusterDetector.cpp.
References analyseClustersOriginDependentValues(), avgPileUpDegree, clusterednessIndex, computeAveragePileUpDegree(), and computeClusterednessIndex().
Referenced by detectAndAnalyseClusters().
void ClusterDetector::analyseClustersOriginDependentValues (vector< Cluster > & clusters) protected
Analyse the clusters and compute the origin dependent values.
The values which depend on the origin point are the distance of the cluster from the centre and the angle
Parameters
clusters Collection of clusters, each one with the updated measures
Definition at line 129 of file ClusterDetector.cpp.
References getClusterConvexHull(), and updateClusterOriginDependentValues().
Referenced by analyseClusters().
void ClusterDetector::clearPreviousDetectionResults () override protected virtual
Clear the clusters from the previous detection.
Implements multiscale::analysis::Detector.
Definition at line 61 of file ClusterDetector.cpp.
References clusters.
double ClusterDetector::computeAveragePileUpDegree (vector< Cluster > & clusters) protected
Compute the average pile up degree for all entities in the image.
Compute the average pile up degree for all entities in the image as the sum of the average pile up degrees of all clusters divided by the number of clusters
Parameters
clusters Clusters of entities detected in the image
Definition at line 162 of file ClusterDetector.cpp.
Referenced by analyseClusters().
double ClusterDetector::computeClusterednessIndex (const vector< Cluster > & clusters) protected
Compute the clusteredness index for all the entities detected in the image.
Compute the clusteredness index for all the entities detected in the image using Silhouette cluster validity index
Parameters
clusters Collection of clusters, each one with the updated measures
Definition at line 158 of file ClusterDetector.cpp.
References multiscale::analysis::Silhouette::computeOverallAverageMeasure().
Referenced by analyseClusters().
vector< shared_ptr< DataPoint > > ClusterDetector::convertEntities (const vector< Entity > & entities) protected
Convert the entities to the format required by the DBSCAN class.
Parameters
entities Entities detected in the image
Definition at line 85 of file ClusterDetector.cpp.
References convertNonPiledUpEntities(), and convertPiledUpEntities().
Referenced by detectClusters().
double ClusterDetector::convertEpsValue () protected
Convert the value of eps from integer to double.
Definition at line 191 of file ClusterDetector.cpp.
References eps, EPS_MAX, EPS_MIN, EPS_REAL_MAX, and EPS_REAL_MIN.
Referenced by detectClusters(), and getEps().
void ClusterDetector::convertNonPiledUpEntities (const vector< Entity > & entities, vector< shared_ptr< DataPoint > > & dataPoints) protected
Convert the non pile up entities to the format required by the DBSCAN class.
Parameters
entities Entities detected in the image
dataPoints Collection of DataPoint instances required by the DBSCAN class
Definition at line 94 of file ClusterDetector.cpp.
Referenced by convertEntities().
void ClusterDetector::convertPiledUpEntities (const vector< Entity > & entities, vector< shared_ptr< DataPoint > > & dataPoints) protected
Convert the entities to the required format by the DBSCAN class.
Parameters
entities Entities detected in the image
dataPoints Collection of DataPoint instances required by the DBSCAN class
Definition at line 100 of file ClusterDetector.cpp.
Referenced by convertEntities().
void ClusterDetector::createDetectorSpecificTrackbars () override protected virtual
Create the trackbars.
Implements multiscale::analysis::Detector.
Definition at line 56 of file ClusterDetector.cpp.
References eps, EPS_MAX, MIN_POINTS_MAX, minPoints, TRACKBAR_EPS, TRACKBAR_MINPOINTS, and WIN_OUTPUT_IMAGE.
void ClusterDetector::detectAndAnalyseClusters (const vector< Entity > & entities, vector< Cluster > & clusters) protected
Detect and analyse the clusters of entities in the image.
Detect and analyse the clusters of entities in the image
Parameters
entities Entities detected in the image
clusters Clusters of entities detected in the image
Definition at line 72 of file ClusterDetector.cpp.
References addEntitiesToClusters(), analyseClusters(), CLUSTERING_UNCLASSIFIED, and detectClusters().
Referenced by processImageAndDetect().
void ClusterDetector::detectClusters (const vector< Entity > & entities, vector< int > & clusterIndexes, int & nrOfClusters) protected
Detect the clusters of entities in the image.
Detect the clusters of entities in the image using Density Based scan (DBscan) clustering algorithm Clusters start from index 1, because cluster 0 contains only noise data/points.
Parameters
entities Entities detected in the image
clusterIndexes Indexes to which cluster each entity belongs
nrOfClusters Total number of clusters
Definition at line 81 of file ClusterDetector.cpp.
References convertEntities(), convertEpsValue(), getValidMinPointsValue(), and multiscale::analysis::DBSCAN::run().
Referenced by detectAndAnalyseClusters().
virtual void multiscale::analysis::ClusterDetector::detectEntitiesInImage (vector< Entity > & entities) protected pure virtual
Detect the entities in the image.
Detect the entities in the image, compute their centre point and degree of pile up
Parameters
entities Entities detected in the image
Implemented in multiscale::analysis::SimulationClusterDetector.
Referenced by processImageAndDetect().
vector< Point > ClusterDetector::getClusterConvexHull (Cluster & cluster) protected
Return the convex hull of the given cluster.
Parameters
cluster The given cluster
Definition at line 148 of file ClusterDetector.cpp.
References multiscale::analysis::Cluster::getEntitiesConvexHull().
Referenced by analyseClustersOriginDependentValues().
vector< Cluster > const & ClusterDetector::getClusters ()
Get a const reference to the vector of detected clusters.
Definition at line 35 of file ClusterDetector.cpp.
References clusters.
double ClusterDetector::getEps ()
Get the value of the clustering algorithm parameter eps.
Definition at line 27 of file ClusterDetector.cpp.
References convertEpsValue().
Referenced by saveDetectorParameterValues().
int ClusterDetector::getMinPoints ()
Get the value of the clustering algorithm parameter MinPoints.
Definition at line 31 of file ClusterDetector.cpp.
References minPoints.
Referenced by saveDetectorParameterValues().
int ClusterDetector::getValidMinPointsValue () protected
Return non-zero value for minPoints.
Definition at line 195 of file ClusterDetector.cpp.
References minPoints.
Referenced by detectClusters().
void ClusterDetector::initialiseDetectorSpecificFields () override protected virtual
Initialise clustering values.
Implements multiscale::analysis::Detector.
Definition at line 51 of file ClusterDetector.cpp.
References eps, and minPoints.
void ClusterDetector::outputResultsToCsvFile (ofstream & fout) override protected virtual
Output the information computed for the clusters to a csv file.
Parameters
fout Output file stream
Implements multiscale::analysis::Detector.
Definition at line 177 of file ClusterDetector.cpp.
References avgPileUpDegree, clusterednessIndex, clusters, multiscale::analysis::Cluster::fieldNamesToString(), OUTPUT_CLUSTEREDNESS, and OUTPUT_PILE_UP.
void ClusterDetector::processImageAndDetect () override protected virtual
Process the provided image and detect clusters in it.
Implements multiscale::analysis::Detector.
Definition at line 65 of file ClusterDetector.cpp.
References clusters, detectAndAnalyseClusters(), and detectEntitiesInImage().
void ClusterDetector::setEps (double eps)
Set the value of the clustering algorithm parameter eps.
Parameters
eps Value of the clustering algorithm parameter eps
Definition at line 39 of file ClusterDetector.cpp.
References eps, EPS_MAX, EPS_MIN, EPS_REAL_MAX, EPS_REAL_MIN, and multiscale::analysis::Detector::setDetectorSpecificFieldsInitialisationFlag().
Referenced by loadDetectorParameterValues().
void ClusterDetector::setMinPoints (int minPoints)
Set the value of the clustering algorithm parameter MinPoints.
Parameters
minPoints Value of the clustering algorithm parameter MinPoints
Definition at line 45 of file ClusterDetector.cpp.
References minPoints, and multiscale::analysis::Detector::setDetectorSpecificFieldsInitialisationFlag().
Referenced by loadDetectorParameterValues().
void ClusterDetector::updateClusterOriginDependentValues (Cluster & cluster, const vector< Point > & clusterConvexHull) protected
Update the cluster and compute the origin dependent values considering the convex hull.
The values which depend on the origin point are the distance of the cluster from the centre and the angle
Parameters
cluster Cluster
clusterConvexHull Convex hull of the cluster
Definition at line 139 of file ClusterDetector.cpp.
References multiscale::Geometry2D::distanceBtwPoints(), multiscale::Geometry2D::minimumDistancePointIndex(), multiscale::analysis::Detector::origin, multiscale::analysis::Detector::polygonAngle(), and multiscale::analysis::Cluster::setOriginDependentMembers().
Referenced by analyseClustersOriginDependentValues().
Member Data Documentation
double multiscale::analysis::ClusterDetector::avgPileUpDegree protected
Average pile up degree of all clusters
Definition at line 39 of file ClusterDetector.hpp.
Referenced by analyseClusters(), ClusterDetector(), and outputResultsToCsvFile().
double multiscale::analysis::ClusterDetector::clusterednessIndex protected
Index of clusteredness for all clusters
Definition at line 38 of file ClusterDetector.hpp.
Referenced by analyseClusters(), ClusterDetector(), and outputResultsToCsvFile().
vector<Cluster> multiscale::analysis::ClusterDetector::clusters protected
Clusters found in the image
Definition at line 49 of file ClusterDetector.hpp.
Referenced by clearPreviousDetectionResults(), getClusters(), outputResultsToCsvFile(), multiscale::analysis::SimulationClusterDetector::outputResultsToImage(), and processImageAndDetect().
double multiscale::analysis::ClusterDetector::entityPileupDegree protected
      The pile up degree (intensity) of a grid position occupied by only
one entity
Definition at line 41 of file ClusterDetector.hpp.
Referenced by ClusterDetector(), and multiscale::analysis::SimulationClusterDetector::computePileUpDegreeAtPosition().
int multiscale::analysis::ClusterDetector::eps protected
                        DBSCAN algorithm parameter for specifying the maximum radius
of the neighbourhood
Definition at line 44 of file ClusterDetector.hpp.
Referenced by ClusterDetector(), convertEpsValue(), createDetectorSpecificTrackbars(), initialiseDetectorSpecificFields(), and setEps().
int multiscale::analysis::ClusterDetector::minPoints protected
                  DBSCAN algorithm parameter for specifying the minimum number
of points in an eps-neighbourhood of that point
Definition at line 46 of file ClusterDetector.hpp.
Referenced by ClusterDetector(), createDetectorSpecificTrackbars(), getMinPoints(), getValidMinPointsValue(), initialiseDetectorSpecificFields(), and setMinPoints().
The documentation for this class was generated from the following files:
include/multiscale/analysis/spatial/ClusterDetector.hpp
src/multiscale/analysis/spatial/ClusterDetector.cpp