Multiscale: multiscale::analysis::RectangularMatFactory Class Reference
multiscale::analysis::RectangularMatFactory Class Reference
Class for creating a Mat object considering a rectangular grid.
#include <RectangularMatFactory.hpp>
Public Member Functions
RectangularMatFactory ()
~RectangularMatFactory ()
Mat createFromViewerImage (const string &inputFile) override
Create a Mat object from the image file obtained from the RectangularGeometryViewer.
Public Member Functions inherited from multiscale::analysis::MatFactory
MatFactory ()
virtual ~MatFactory ()
Mat create (const string &inputFile)
Create a Mat object from the input file.
Protected Member Functions
unsigned char * processConcentrations (ifstream &fin) override
Process the concentrations from the input file.
bool isValidViewerImage (const Mat &image) override
Check if the image generated by the viewer has the required resolution.
Protected Member Functions inherited from multiscale::analysis::MatFactory
void initInputFile (ifstream &fin, const string &inputFile)
Initialise the input file.
unsigned char convertToIntensity (double concentration)
Convert concentration to intensity.
Additional Inherited Members
Protected Attributes inherited from multiscale::analysis::MatFactory
int rows
int cols
double simulationTime
Detailed Description
Class for creating a Mat object considering a rectangular grid.
Definition at line 24 of file RectangularMatFactory.hpp.
Constructor & Destructor Documentation
RectangularMatFactory::RectangularMatFactory ()
Definition at line 8 of file RectangularMatFactory.cpp.
RectangularMatFactory::~RectangularMatFactory ()
Definition at line 10 of file RectangularMatFactory.cpp.
Member Function Documentation
Mat RectangularMatFactory::createFromViewerImage (const string & inputFile) override virtual
Create a Mat object from the image file obtained from the RectangularGeometryViewer.
Create the Mat instance from the given image file
Parameters
inputFile The path to the image file
Implements multiscale::analysis::MatFactory.
Definition at line 12 of file RectangularMatFactory.cpp.
References isValidViewerImage(), ROI_HEIGHT, ROI_START_X, ROI_START_Y, and ROI_WIDTH.
Referenced by main().
bool RectangularMatFactory::isValidViewerImage (const Mat & image) override protected virtual
Check if the image generated by the viewer has the required resolution.
Parameters
image Image generated by the viewer
Implements multiscale::analysis::MatFactory.
Definition at line 37 of file RectangularMatFactory.cpp.
References ERR_IMG_RESOLUTION, ERR_INPUT_OPEN, INPUT_IMG_HEIGHT, and INPUT_IMG_WIDTH.
Referenced by createFromViewerImage().
unsigned char * RectangularMatFactory::processConcentrations (ifstream & fin) override protected virtual
Process the concentrations from the input file.
Read the concentrations from the input file and return them as an array which can be used afterwards to create a Mat object from them
REMARK: The constructor of Mat does not copy the data. Therefore, DO NOT deallocate it in this class.
Parameters
fin Input file stream from which the concentrations are read
Implements multiscale::analysis::MatFactory.
Definition at line 20 of file RectangularMatFactory.cpp.
References multiscale::analysis::MatFactory::cols, multiscale::analysis::MatFactory::convertToIntensity(), ERR_CONC, and multiscale::analysis::MatFactory::rows.
The documentation for this class was generated from the following files:
include/multiscale/analysis/spatial/factory/RectangularMatFactory.hpp
src/multiscale/analysis/spatial/factory/RectangularMatFactory.cpp