Multiscale: multiscale::MinimumAreaEnclosingTriangle Class Reference
multiscale::MinimumAreaEnclosingTriangle Class Reference
Class for computing the minimum area enclosing triangle for a given polygon.
#include <MinimumAreaEnclosingTriangle.hpp>
Static Public Member Functions
static void find (const vector< Point2f > &polygon, vector< Point2f > &minimumAreaEnclosingTriangle, double &area)
Find the minimum area enclosing triangle for the given polygon.
Static Private Member Functions
static void initialise ()
Initialisation function for the class.
static void findMinimumAreaEnclosingTriangle (vector< Point2f > &minimumAreaEnclosingTriangle, double &area)
Find the minimum area enclosing triangle for the given polygon.
static void advanceBToRightChain ()
Advance b to the right chain.
static void moveAIfLowAndBIfHigh ()
Move "a" if it is low and "b" if it is high.
static void searchForBTangency ()
Search for the tangency of side B.
static bool isNotBTangency ()
Check if tangency for side B was not obtained.
static void updateSidesCA ()
Update sides A and C.
static void updateSidesBA ()
Update sides B and possibly A if tangency for side B was not obtained.
static void updateSideB ()
Set side B if tangency for side B was obtained.
static bool updateTriangleVertices ()
Update the triangle vertices after all sides were set and return true if possible or false otherwise.
static bool isValidMinimalTriangle ()
Check if the found minimal triangle is valid.
static void updateMinimumAreaEnclosingTriangle (vector< Point2f > &minimumAreaEnclosingTriangle, double &minimumAreaEnclosingTriangleArea)
Update the current minimum area enclosing triangle if the newly obtained one has a smaller area.
static bool middlePointOfSideB (Point2f &middlePointOfSideB)
Return the middle point of side B.
static bool intersectsBelow (const Point2f &gammaPoint, unsigned int polygonPointIndex)
Check if the line determined by gammaPoint and polygon[polygonPointIndex] intersects the polygon below the point polygon[polygonPointIndex].
static bool intersectsAbove (const Point2f &gammaPoint, unsigned int polygonPointIndex)
Check if the line determined by gammaPoint and polygon[polygonPointIndex] intersects the polygon above the point polygon[polygonPointIndex].
static unsigned int intersects (double angleOfGammaAndPoint, unsigned int polygonPointIndex)
Check if/where the line determined by gammaPoint and polygon[polygonPointIndex] intersects the polygon.
static unsigned int intersectsAboveOrBelow (unsigned int successorOrPredecessorIndex, unsigned int pointIndex)
If (gamma(x) x) intersects P between successorOrPredecessorIndex and pointIntex is it above/below?
static bool isFlushAngleBetweenPredecessorAndSuccessor (double &angleFlushEdge, double anglePredecessor, double angleSuccessor)
Check if the angle of the flush edge or its opposite angle lie between the angle of the predecessor and successor.
static bool isGammaAngleBetween (double &gammaAngle, double angle1, double angle2)
Check if the angle of the line (gamma(p) p) or its opposite angle lie between angle1 and angle2.
static bool isGammaAngleEqualTo (double &gammaAngle, double angle)
Check if the angle of the line (gamma(p) p) or its opposite angle is equal to the given angle.
static double height (unsigned int polygonPointIndex)
Compute the height of the point specified by the given index.
static double height (const Point2f &polygonPoint)
Compute the height of the point.
static bool gamma (unsigned int polygonPointIndex, Point2f &gammaPoint)
Find gamma for a given point "p" specified by its index.
static Point2f findVertexCOnSideB ()
Find vertex C which lies on side B at a distance = 2 * height(a-1) from side C.
static bool findGammaIntersectionPoints (unsigned int polygonPointIndex, const Point2f &side1StartVertex, const Point2f &side1EndVertex, const Point2f &side2StartVertex, const Point2f &side2EndVertex, Point2f &intersectionPoint1, Point2f &intersectionPoint2)
Find the intersection points to compute gamma(point)
static bool areIdenticalLines (const vector< double > &side1Params, const vector< double > &side2Params, double sideCExtraParam)
Check if the given lines are identical or not.
static bool areIntersectingLines (const vector< double > &side1Params, const vector< double > &side2Params, double sideCExtraParam, Point2f &intersectionPoint1, Point2f &intersectionPoint2)
Check if the given lines intersect or not. If the lines intersect find their intersection points.
static vector< double > lineEquationParameters (const Point2f &p, const Point2f &q)
Get the line equation parameters "a", "b" and "c" for the line determined by points "p" and "q".
static void advance (unsigned int &index)
Advance the given index with one position.
static unsigned int successor (unsigned int index)
Return the succesor of the provided point index.
static unsigned int predecessor (unsigned int index)
Return the predecessor of the provided point index.
Static Private Attributes
static unsigned int validationFlag
static Point2f vertexA
static Point2f vertexB
static Point2f vertexC
static Point2f sideAStartVertex
static Point2f sideAEndVertex
static Point2f sideBStartVertex
static Point2f sideBEndVertex
static Point2f sideCStartVertex
static Point2f sideCEndVertex
static double area
static unsigned int a
static unsigned int b
static unsigned int c
static unsigned int nrOfPoints
static vector< Point2f > polygon
Detailed Description
Class for computing the minimum area enclosing triangle for a given polygon.
This implementation has a linear complexity (theta(n)) with respect to the number of points defining the polygon and is based on the algorithm described in the following paper:
J. O’Rourke, A. Aggarwal, S. Maddila, and M. Baldwin, ‘An optimal algorithm for finding minimal enclosing triangles’, Journal of Algorithms, vol. 7, no. 2, pp. 258–269, Jun. 1986.
Definition at line 34 of file MinimumAreaEnclosingTriangle.hpp.
Member Function Documentation
void MinimumAreaEnclosingTriangle::advance (unsigned int & index) static private
Advance the given index with one position.
Parameters
index Index of the point
Definition at line 385 of file MinimumAreaEnclosingTriangle.cpp.
References successor().
Referenced by advanceBToRightChain(), moveAIfLowAndBIfHigh(), and searchForBTangency().
void MinimumAreaEnclosingTriangle::advanceBToRightChain () static private
Advance b to the right chain.
See paper for more details
Definition at line 81 of file MinimumAreaEnclosingTriangle.cpp.
References advance(), b, multiscale::Numeric::greaterOrEqual(), height(), and successor().
Referenced by findMinimumAreaEnclosingTriangle().
bool MinimumAreaEnclosingTriangle::areIdenticalLines (const vector< double > & side1Params, const vector< double > & side2Params, double sideCExtraParam) static private
Check if the given lines are identical or not.
The lines are specified as: ax + by + c = 0 OR ax + by + c (+/-) sideCExtraParam = 0
Parameters
side1Params Vector containing the values of a, b and c for side 1
side2Params Vector containing the values of a, b and c for side 2
sideCExtraParam Extra parameter for the flush edge C
Definition at line 350 of file MinimumAreaEnclosingTriangle.cpp.
References multiscale::Geometry2D::areIdenticalLines().
Referenced by findGammaIntersectionPoints().
bool MinimumAreaEnclosingTriangle::areIntersectingLines (const vector< double > & side1Params, const vector< double > & side2Params, double sideCExtraParam, Point2f & intersectionPoint1, Point2f & intersectionPoint2) static private
Check if the given lines intersect or not. If the lines intersect find their intersection points.
The lines are specified as: ax + by + c = 0 OR ax + by + c (+/-) sideCExtraParam = 0
Parameters
side1Params Vector containing the values of a, b and c for side 1
side2Params Vector containing the values of a, b and c for side 2
sideCExtraParam Extra parameter for the flush edge C
intersectionPoint1 The first intersection point, if it exists
intersectionPoint2 The second intersection point, if it exists
Definition at line 360 of file MinimumAreaEnclosingTriangle.cpp.
References multiscale::Geometry2D::lineIntersection().
Referenced by findGammaIntersectionPoints().
void MinimumAreaEnclosingTriangle::find (const vector< Point2f > & polygon, vector< Point2f > & minimumAreaEnclosingTriangle, double & area) static
Find the minimum area enclosing triangle for the given polygon.
Parameters
polygon Polygon of points for which the minimum area enclosing triangle will be found
minimumAreaEnclosingTriangle Minimum area triangle enclosing the given polygon
area Area of the minimum area enclosing triangle
Definition at line 37 of file MinimumAreaEnclosingTriangle.cpp.
References findMinimumAreaEnclosingTriangle(), initialise(), and polygon.
bool MinimumAreaEnclosingTriangle::findGammaIntersectionPoints (unsigned int polygonPointIndex, const Point2f & side1StartVertex, const Point2f & side1EndVertex, const Point2f & side2StartVertex, const Point2f & side2EndVertex, Point2f & intersectionPoint1, Point2f & intersectionPoint2) static private
Find the intersection points to compute gamma(point)
Parameters
polygonPointIndex Index of the polygon point for which the distance is known
side1StartVertex Start vertex for side 1
side1EndVertex End vertex for side 1
side2StartVertex Start vertex for side 2
side2EndVertex End vertex for side 2
intersectionPoint1 First intersection point between one pair of lines
intersectionPoint2 Second intersection point between another pair of lines
Definition at line 327 of file MinimumAreaEnclosingTriangle.cpp.
References areIdenticalLines(), areIntersectingLines(), height(), and lineEquationParameters().
Referenced by findVertexCOnSideB(), and gamma().
void MinimumAreaEnclosingTriangle::findMinimumAreaEnclosingTriangle (vector< Point2f > & minimumAreaEnclosingTriangle, double & area) static private
Find the minimum area enclosing triangle for the given polygon.
Parameters
minimumAreaEnclosingTriangle Minimum area triangle enclosing the given polygon
area Area of the minimum area enclosing triangle
Definition at line 61 of file MinimumAreaEnclosingTriangle.cpp.
References advanceBToRightChain(), c, isNotBTangency(), moveAIfLowAndBIfHigh(), nrOfPoints, searchForBTangency(), updateMinimumAreaEnclosingTriangle(), updateSideB(), updateSidesBA(), updateSidesCA(), and updateTriangleVertices().
Referenced by find().
Point2f MinimumAreaEnclosingTriangle::findVertexCOnSideB () static private
Find vertex C which lies on side B at a distance = 2 * height(a-1) from side C.
Considering that line (x y) is a line parallel to (c c-1) and that the distance between the lines is equal to 2 * height(a-1), we can have two possible (x y) lines.
Therefore, we will compute two intersection points between the lines (x y) and (b b-1) and take the point which is closest to point polygon[b].
See paper and formula for distance from point to a line for more details
Definition at line 310 of file MinimumAreaEnclosingTriangle.cpp.
References a, multiscale::Geometry2D::areOnTheSameSideOfLine(), c, ERR_VERTEX_C_ON_SIDE_B, findGammaIntersectionPoints(), polygon, predecessor(), sideBEndVertex, sideBStartVertex, sideCEndVertex, sideCStartVertex, and successor().
Referenced by updateSidesBA().
bool MinimumAreaEnclosingTriangle::gamma (unsigned int polygonPointIndex, Point2f & gammaPoint) static private
Find gamma for a given point "p" specified by its index.
The function returns true if gamma exists i.e. if lines (a a-1) and (x y) intersect and false otherwise. In case the two lines intersect in point intersectionPoint, gamma is computed.
Considering that line (x y) is a line parallel to (c c-1) and that the distance between the lines is equal to 2 * height(p), we can have two possible (x y) lines.
Therefore, we will compute two intersection points between the lines (x y) and (a a-1) and take the point which is closest to point polygon[a].
See paper and formula for distance from point to a line for more details
Parameters
polygonPointIndex Index of the polygon point
gammaPoint Point2f gamma(polygon[polygonPointIndex])
Definition at line 291 of file MinimumAreaEnclosingTriangle.cpp.
References a, multiscale::Geometry2D::areOnTheSameSideOfLine(), c, findGammaIntersectionPoints(), polygon, predecessor(), and successor().
Referenced by isNotBTangency(), moveAIfLowAndBIfHigh(), searchForBTangency(), and updateSideB().
double MinimumAreaEnclosingTriangle::height (unsigned int polygonPointIndex) static private
Compute the height of the point specified by the given index.
See paper for more details
Parameters
polygonPointIndex Index of the polygon point
Definition at line 275 of file MinimumAreaEnclosingTriangle.cpp.
References c, multiscale::Geometry2D::distanceFromPointToLine(), polygon, and predecessor().
Referenced by advanceBToRightChain(), findGammaIntersectionPoints(), intersectsAboveOrBelow(), isNotBTangency(), moveAIfLowAndBIfHigh(), searchForBTangency(), and updateSidesBA().
double MinimumAreaEnclosingTriangle::height (const Point2f & polygonPoint) static private
Compute the height of the point.
See paper for more details
Parameters
polygonPoint Polygon point
Definition at line 284 of file MinimumAreaEnclosingTriangle.cpp.
References c, multiscale::Geometry2D::distanceFromPointToLine(), polygon, and predecessor().
void MinimumAreaEnclosingTriangle::initialise () static private
Initialisation function for the class.
Definition at line 53 of file MinimumAreaEnclosingTriangle.cpp.
References a, b, c, nrOfPoints, and polygon.
Referenced by find().
unsigned int MinimumAreaEnclosingTriangle::intersects (double angleOfGammaAndPoint, unsigned int polygonPointIndex) static private
Check if/where the line determined by gammaPoint and polygon[polygonPointIndex] intersects the polygon.
Parameters
angleOfGammaAndPoint Angle between gammaPoint and polygon[polygonPointIndex]
polygonPointIndex Index of the polygon point which is considered when determining the line
Definition at line 222 of file MinimumAreaEnclosingTriangle.cpp.
References multiscale::Numeric::almostEqual(), multiscale::Geometry2D::angleOfLineWrtOxAxis(), c, INTERSECTS_BELOW, INTERSECTS_CRITICAL, intersectsAboveOrBelow(), isFlushAngleBetweenPredecessorAndSuccessor(), isGammaAngleBetween(), isGammaAngleEqualTo(), polygon, predecessor(), and successor().
Referenced by intersectsAbove(), and intersectsBelow().
bool MinimumAreaEnclosingTriangle::intersectsAbove (const Point2f & gammaPoint, unsigned int polygonPointIndex) static private
Check if the line determined by gammaPoint and polygon[polygonPointIndex] intersects the polygon above the point polygon[polygonPointIndex].
Parameters
gammaPoint Gamma(p)
polygonPointIndex Index of the polygon point which is considered when determining the line
Definition at line 216 of file MinimumAreaEnclosingTriangle.cpp.
References multiscale::Geometry2D::angleOfLineWrtOxAxis(), intersects(), INTERSECTS_ABOVE, and polygon.
Referenced by isNotBTangency().
unsigned int MinimumAreaEnclosingTriangle::intersectsAboveOrBelow (unsigned int successorOrPredecessorIndex, unsigned int pointIndex) static private
If (gamma(x) x) intersects P between successorOrPredecessorIndex and pointIntex is it above/below?
Parameters
successorOrPredecessorIndex Index of the successor or predecessor
pointIndex Index of the point x in the polygon
Definition at line 246 of file MinimumAreaEnclosingTriangle.cpp.
References height(), INTERSECTS_ABOVE, and INTERSECTS_BELOW.
Referenced by intersects().
bool MinimumAreaEnclosingTriangle::intersectsBelow (const Point2f & gammaPoint, unsigned int polygonPointIndex) static private
Check if the line determined by gammaPoint and polygon[polygonPointIndex] intersects the polygon below the point polygon[polygonPointIndex].
Parameters
gammaPoint Gamma(p)
polygonPointIndex Index of the polygon point which is considered when determining the line
Definition at line 210 of file MinimumAreaEnclosingTriangle.cpp.
References multiscale::Geometry2D::angleOfLineWrtOxAxis(), intersects(), INTERSECTS_BELOW, and polygon.
Referenced by moveAIfLowAndBIfHigh(), and searchForBTangency().
bool MinimumAreaEnclosingTriangle::isFlushAngleBetweenPredecessorAndSuccessor (double & angleFlushEdge, double anglePredecessor, double angleSuccessor) static private
Check if the angle of the flush edge or its opposite angle lie between the angle of the predecessor and successor.
Parameters
angleFlushEdge Angle of the flush edge
anglePredecessor Angle of the predecessor
angleSuccessor Angle of the successor
Definition at line 254 of file MinimumAreaEnclosingTriangle.cpp.
References multiscale::Geometry2D::isAngleBetweenNonReflex(), multiscale::Geometry2D::isOppositeAngleBetweenNonReflex(), and multiscale::Geometry2D::oppositeAngle().
Referenced by intersects().
bool MinimumAreaEnclosingTriangle::isGammaAngleBetween (double & gammaAngle, double angle1, double angle2) static private
Check if the angle of the line (gamma(p) p) or its opposite angle lie between angle1 and angle2.
Parameters
gammaAngle Angle of the line (gamma(p) p)
angle1 One of the boundary angles
angle2 Another boundary angle
Definition at line 267 of file MinimumAreaEnclosingTriangle.cpp.
References multiscale::Geometry2D::isAngleBetweenNonReflex().
Referenced by intersects().
bool MinimumAreaEnclosingTriangle::isGammaAngleEqualTo (double & gammaAngle, double angle) static private
Check if the angle of the line (gamma(p) p) or its opposite angle is equal to the given angle.
Parameters
gammaAngle Angle of the line (gamma(p) p)
angle Angle to compare against
Definition at line 271 of file MinimumAreaEnclosingTriangle.cpp.
References multiscale::Numeric::almostEqual().
Referenced by intersects().
bool MinimumAreaEnclosingTriangle::isNotBTangency () static private
Check if tangency for side B was not obtained.
See paper for more details
Definition at line 108 of file MinimumAreaEnclosingTriangle.cpp.
References a, b, gamma(), height(), intersectsAbove(), and predecessor().
Referenced by findMinimumAreaEnclosingTriangle().
bool MinimumAreaEnclosingTriangle::isValidMinimalTriangle () static private
Check if the found minimal triangle is valid.
This means that all midpoints of the triangle should touch the polygon
See paper for more details
Definition at line 165 of file MinimumAreaEnclosingTriangle.cpp.
References a, multiscale::Geometry2D::areEqualPoints(), b, multiscale::Geometry2D::isPointOnLineSegment(), multiscale::Geometry2D::middlePoint(), polygon, predecessor(), sideAEndVertex, sideAStartVertex, sideBEndVertex, sideBStartVertex, sideCEndVertex, sideCStartVertex, VALIDATION_SIDE_A_TANGENT, VALIDATION_SIDE_B_TANGENT, validationFlag, vertexA, vertexB, and vertexC.
Referenced by updateTriangleVertices().
vector< double > MinimumAreaEnclosingTriangle::lineEquationParameters (const Point2f & p, const Point2f & q) static private
Get the line equation parameters "a", "b" and "c" for the line determined by points "p" and "q".
The equation of the line is considered in the general form: ax + by + c = 0
Parameters
p One point for defining the equation of the line
q Second point for defining the equation of the line
Definition at line 372 of file MinimumAreaEnclosingTriangle.cpp.
References a, b, c, and multiscale::Geometry2D::lineEquationDeterminedByPoints().
Referenced by findGammaIntersectionPoints().
bool MinimumAreaEnclosingTriangle::middlePointOfSideB (Point2f & middlePointOfSideB) static private
Return the middle point of side B.
Definition at line 197 of file MinimumAreaEnclosingTriangle.cpp.
References multiscale::Geometry2D::lineIntersection(), multiscale::Geometry2D::middlePoint(), sideAEndVertex, sideAStartVertex, sideBEndVertex, sideBStartVertex, sideCEndVertex, sideCStartVertex, vertexA, and vertexC.
Referenced by updateSidesBA().
void MinimumAreaEnclosingTriangle::moveAIfLowAndBIfHigh () static private
Move "a" if it is low and "b" if it is high.
See paper for more details
Definition at line 87 of file MinimumAreaEnclosingTriangle.cpp.
References a, advance(), b, gamma(), height(), and intersectsBelow().
Referenced by findMinimumAreaEnclosingTriangle().
unsigned int MinimumAreaEnclosingTriangle::predecessor (unsigned int index) static private
Return the predecessor of the provided point index.
The predecessor of the first polygon point is the last polygon point (circular referencing)
Parameters
index Index of the point
Definition at line 393 of file MinimumAreaEnclosingTriangle.cpp.
References nrOfPoints.
Referenced by findVertexCOnSideB(), gamma(), height(), intersects(), isNotBTangency(), isValidMinimalTriangle(), searchForBTangency(), updateSidesBA(), and updateSidesCA().
void MinimumAreaEnclosingTriangle::searchForBTangency () static private
Search for the tangency of side B.
See paper for more details
Definition at line 99 of file MinimumAreaEnclosingTriangle.cpp.
References a, advance(), b, gamma(), multiscale::Numeric::greaterOrEqual(), height(), intersectsBelow(), and predecessor().
Referenced by findMinimumAreaEnclosingTriangle().
unsigned int MinimumAreaEnclosingTriangle::successor (unsigned int index) static private
Return the succesor of the provided point index.
The succesor of the last polygon point is the first polygon point (circular referencing)
Parameters
index Index of the point
Definition at line 389 of file MinimumAreaEnclosingTriangle.cpp.
References nrOfPoints.
Referenced by advance(), advanceBToRightChain(), findVertexCOnSideB(), gamma(), and intersects().
void MinimumAreaEnclosingTriangle::updateMinimumAreaEnclosingTriangle (vector< Point2f > & minimumAreaEnclosingTriangle, double & minimumAreaEnclosingTriangleArea) static private
Update the current minimum area enclosing triangle if the newly obtained one has a smaller area.
Parameters
minimumAreaEnclosingTriangle Minimum area triangle enclosing the given polygon
minimumAreaEnclosingTriangleArea Area of the minimum area triangle enclosing the given polygon
Definition at line 183 of file MinimumAreaEnclosingTriangle.cpp.
References area, multiscale::Geometry2D::areaOfTriangle(), vertexA, vertexB, and vertexC.
Referenced by findMinimumAreaEnclosingTriangle().
void MinimumAreaEnclosingTriangle::updateSideB () static private
Set side B if tangency for side B was obtained.
See paper for more details
Definition at line 146 of file MinimumAreaEnclosingTriangle.cpp.
References b, ERR_SIDE_B_GAMMA, gamma(), polygon, sideBEndVertex, sideBStartVertex, VALIDATION_SIDE_B_TANGENT, and validationFlag.
Referenced by findMinimumAreaEnclosingTriangle().
void MinimumAreaEnclosingTriangle::updateSidesBA () static private
Update sides B and possibly A if tangency for side B was not obtained.
See paper for more details
Definition at line 128 of file MinimumAreaEnclosingTriangle.cpp.
References a, b, findVertexCOnSideB(), height(), middlePointOfSideB(), polygon, predecessor(), sideAEndVertex, sideAStartVertex, sideBEndVertex, sideBStartVertex, VALIDATION_SIDE_A_TANGENT, VALIDATION_SIDES_FLUSH, and validationFlag.
Referenced by findMinimumAreaEnclosingTriangle().
void MinimumAreaEnclosingTriangle::updateSidesCA () static private
Update sides A and C.
Side C will have as start and end vertices the polygon points "c" and "c-1" Side A will have as start and end vertices the polygon points "a" and "a-1"
Definition at line 120 of file MinimumAreaEnclosingTriangle.cpp.
References a, c, polygon, predecessor(), sideAEndVertex, sideAStartVertex, sideCEndVertex, and sideCStartVertex.
Referenced by findMinimumAreaEnclosingTriangle().
bool MinimumAreaEnclosingTriangle::updateTriangleVertices () static private
Update the triangle vertices after all sides were set and return true if possible or false otherwise.
See paper for more details
Definition at line 155 of file MinimumAreaEnclosingTriangle.cpp.
References isValidMinimalTriangle(), multiscale::Geometry2D::lineIntersection(), sideAEndVertex, sideAStartVertex, sideBEndVertex, sideBStartVertex, sideCEndVertex, sideCStartVertex, vertexA, vertexB, and vertexC.
Referenced by findMinimumAreaEnclosingTriangle().
Member Data Documentation
unsigned int MinimumAreaEnclosingTriangle::a static private
Index of point "a"; see paper for more details
Definition at line 59 of file MinimumAreaEnclosingTriangle.hpp.
Referenced by findVertexCOnSideB(), gamma(), initialise(), isNotBTangency(), isValidMinimalTriangle(), lineEquationParameters(), moveAIfLowAndBIfHigh(), searchForBTangency(), updateSidesBA(), and updateSidesCA().
double MinimumAreaEnclosingTriangle::area static private
Area of the current considered enclosing triangle
Definition at line 57 of file MinimumAreaEnclosingTriangle.hpp.
Referenced by updateMinimumAreaEnclosingTriangle().
unsigned int MinimumAreaEnclosingTriangle::b static private
Index of point "b"; see paper for more details
Definition at line 60 of file MinimumAreaEnclosingTriangle.hpp.
Referenced by advanceBToRightChain(), initialise(), isNotBTangency(), isValidMinimalTriangle(), lineEquationParameters(), moveAIfLowAndBIfHigh(), searchForBTangency(), updateSideB(), and updateSidesBA().
unsigned int MinimumAreaEnclosingTriangle::c static private
Index of point "c"; see paper for more details
Definition at line 61 of file MinimumAreaEnclosingTriangle.hpp.
Referenced by findMinimumAreaEnclosingTriangle(), findVertexCOnSideB(), gamma(), height(), initialise(), intersects(), lineEquationParameters(), and updateSidesCA().
unsigned int MinimumAreaEnclosingTriangle::nrOfPoints static private
Number of points defining the polygon
Definition at line 63 of file MinimumAreaEnclosingTriangle.hpp.
Referenced by findMinimumAreaEnclosingTriangle(), initialise(), predecessor(), and successor().
vector< Point2f > MinimumAreaEnclosingTriangle::polygon static private
Polygon for which the minimum area enclosing triangle is computed
Definition at line 65 of file MinimumAreaEnclosingTriangle.hpp.
Referenced by find(), findVertexCOnSideB(), gamma(), height(), initialise(), intersects(), intersectsAbove(), intersectsBelow(), isValidMinimalTriangle(), updateSideB(), updateSidesBA(), and updateSidesCA().
Point2f MinimumAreaEnclosingTriangle::sideAEndVertex static private
Ending vertex for side A of triangle
Definition at line 49 of file MinimumAreaEnclosingTriangle.hpp.
Referenced by isValidMinimalTriangle(), middlePointOfSideB(), updateSidesBA(), updateSidesCA(), and updateTriangleVertices().
Point2f MinimumAreaEnclosingTriangle::sideAStartVertex static private
Starting vertex for side A of triangle
Definition at line 48 of file MinimumAreaEnclosingTriangle.hpp.
Referenced by isValidMinimalTriangle(), middlePointOfSideB(), updateSidesBA(), updateSidesCA(), and updateTriangleVertices().
Point2f MinimumAreaEnclosingTriangle::sideBEndVertex static private
Ending vertex for side B of triangle
Definition at line 52 of file MinimumAreaEnclosingTriangle.hpp.
Referenced by findVertexCOnSideB(), isValidMinimalTriangle(), middlePointOfSideB(), updateSideB(), updateSidesBA(), and updateTriangleVertices().
Point2f MinimumAreaEnclosingTriangle::sideBStartVertex static private
Starting vertex for side B of triangle
Definition at line 51 of file MinimumAreaEnclosingTriangle.hpp.
Referenced by findVertexCOnSideB(), isValidMinimalTriangle(), middlePointOfSideB(), updateSideB(), updateSidesBA(), and updateTriangleVertices().
Point2f MinimumAreaEnclosingTriangle::sideCEndVertex static private
Ending vertex for side C of triangle
Definition at line 55 of file MinimumAreaEnclosingTriangle.hpp.
Referenced by findVertexCOnSideB(), isValidMinimalTriangle(), middlePointOfSideB(), updateSidesCA(), and updateTriangleVertices().
Point2f MinimumAreaEnclosingTriangle::sideCStartVertex static private
Starting vertex for side C of triangle
Definition at line 54 of file MinimumAreaEnclosingTriangle.hpp.
Referenced by findVertexCOnSideB(), isValidMinimalTriangle(), middlePointOfSideB(), updateSidesCA(), and updateTriangleVertices().
unsigned int MinimumAreaEnclosingTriangle::validationFlag static private
Validation flag can take the following values:
VALIDATION_SIDE_A_TANGENT;
VALIDATION_SIDE_B_TANGENT;
VALIDATION_SIDES_FLUSH.
Definition at line 38 of file MinimumAreaEnclosingTriangle.hpp.
Referenced by isValidMinimalTriangle(), updateSideB(), and updateSidesBA().
Point2f MinimumAreaEnclosingTriangle::vertexA static private
Vertex A of the current considered enclosing triangle
Definition at line 44 of file MinimumAreaEnclosingTriangle.hpp.
Referenced by isValidMinimalTriangle(), middlePointOfSideB(), updateMinimumAreaEnclosingTriangle(), and updateTriangleVertices().
Point2f MinimumAreaEnclosingTriangle::vertexB static private
Vertex B of the current considered enclosing triangle
Definition at line 45 of file MinimumAreaEnclosingTriangle.hpp.
Referenced by isValidMinimalTriangle(), updateMinimumAreaEnclosingTriangle(), and updateTriangleVertices().
Point2f MinimumAreaEnclosingTriangle::vertexC static private
Vertex C of the current considered enclosing triangle
Definition at line 46 of file MinimumAreaEnclosingTriangle.hpp.
Referenced by isValidMinimalTriangle(), middlePointOfSideB(), updateMinimumAreaEnclosingTriangle(), and updateTriangleVertices().
The documentation for this class was generated from the following files:
include/multiscale/util/MinimumAreaEnclosingTriangle.hpp
src/multiscale/util/MinimumAreaEnclosingTriangle.cpp