Multiscale: multiscale::analysis::SpatialCollection2D Class Reference
multiscale::analysis::SpatialCollection2D Class Reference abstract
Class for representing a collection of objects in 2D space.
#include <SpatialCollection2D.hpp>
Public Member Functions
SpatialCollection2D ()
virtual ~SpatialCollection2D ()
double getClusterednessDegree ()
Get the clusteredness degree.
double getArea ()
Get the area.
double getPerimeter ()
Get the perimeter.
double getDistanceFromOrigin ()
Get the distance from the origin.
double getAngle ()
Get the angle.
Shape2D getShape ()
Get the shape best fitting the spatial collection.
Point2f getCentre ()
Get the point defining the centre of the entity.
string toString ()
Get the string representation of all field values.
Protected Member Functions
void updateMeasuresIfRequired ()
Update the values of all measures if required.
void updateMeasures ()
Update the values of all measures.
virtual void updateSpatialCollectionSpecificValues ()=0
Update the values of all measures specific to the derived classes.
virtual void updateClusterednessDegree ()=0
Update the value of the clusteredness degree.
virtual void updateArea ()=0
Update the value of the area.
virtual void updatePerimeter ()=0
Update the value of the perimeter.
void updateShape ()
Update the shape of the cluster.
virtual void updateCentrePoint ()=0
Update the point defining the centre of the cluster.
virtual double isTriangularMeasure ()=0
Get the measure that the cluster has a triangular shape.
virtual double isRectangularMeasure ()=0
Get the measure that the cluster has a rectangular shape.
virtual double isCircularMeasure ()=0
Get the measure that the cluster has a circular shape.
string shapeAsString ()
Return the shape of the cluster as a string.
virtual string fieldValuesToString ()=0
Return the values of the fields as a string.
vector< Point2f > convertPoints (const vector< Point > &points)
Convert the collection of points from type Point to type Point2f.
Protected Attributes
double clusterednessDegree
double area
double perimeter
double distanceFromOrigin
double angle
double triangularMeasure
double rectangularMeasure
double circularMeasure
Shape2D shape
Point2f centre
bool updateFlag
Private Member Functions
void initialise ()
Initialisation function for the class.
Detailed Description
Class for representing a collection of objects in 2D space.
Definition at line 29 of file SpatialCollection2D.hpp.
Constructor & Destructor Documentation
SpatialCollection2D::SpatialCollection2D ()
Definition at line 6 of file SpatialCollection2D.cpp.
References initialise().
SpatialCollection2D::~SpatialCollection2D () virtual
Definition at line 10 of file SpatialCollection2D.cpp.
Member Function Documentation
vector< Point2f > SpatialCollection2D::convertPoints (const vector< Point > & points) protected
Convert the collection of points from type Point to type Point2f.
Parameters
points Collection of points
Definition at line 119 of file SpatialCollection2D.cpp.
Referenced by multiscale::analysis::Region::isTriangularMeasure().
virtual string multiscale::analysis::SpatialCollection2D::fieldValuesToString () protected pure virtual
Return the values of the fields as a string.
Implemented in multiscale::analysis::Cluster, and multiscale::analysis::Region.
Referenced by toString().
double SpatialCollection2D::getAngle ()
Get the angle.
Definition at line 36 of file SpatialCollection2D.cpp.
References angle, and updateMeasuresIfRequired().
double SpatialCollection2D::getArea ()
Get the area.
Definition at line 18 of file SpatialCollection2D.cpp.
References area, and updateMeasuresIfRequired().
Point2f SpatialCollection2D::getCentre ()
Get the point defining the centre of the entity.
Definition at line 48 of file SpatialCollection2D.cpp.
References centre, and updateMeasuresIfRequired().
double SpatialCollection2D::getClusterednessDegree ()
Get the clusteredness degree.
Definition at line 12 of file SpatialCollection2D.cpp.
References clusterednessDegree, and updateMeasuresIfRequired().
double SpatialCollection2D::getDistanceFromOrigin ()
Get the distance from the origin.
Definition at line 30 of file SpatialCollection2D.cpp.
References distanceFromOrigin, and updateMeasuresIfRequired().
double SpatialCollection2D::getPerimeter ()
Get the perimeter.
Definition at line 24 of file SpatialCollection2D.cpp.
References perimeter, and updateMeasuresIfRequired().
Shape2D SpatialCollection2D::getShape ()
Get the shape best fitting the spatial collection.
Definition at line 42 of file SpatialCollection2D.cpp.
References shape, and updateMeasuresIfRequired().
Referenced by multiscale::analysis::SimulationClusterDetector::outputClusterShape().
void SpatialCollection2D::initialise () private
Initialisation function for the class.
Definition at line 129 of file SpatialCollection2D.cpp.
References area, circularMeasure, perimeter, rectangularMeasure, shape, triangularMeasure, multiscale::analysis::Undefined, and updateFlag.
Referenced by SpatialCollection2D().
virtual double multiscale::analysis::SpatialCollection2D::isCircularMeasure () protected pure virtual
Get the measure that the cluster has a circular shape.
Implemented in multiscale::analysis::Cluster, and multiscale::analysis::Region.
Referenced by updateShape().
virtual double multiscale::analysis::SpatialCollection2D::isRectangularMeasure () protected pure virtual
Get the measure that the cluster has a rectangular shape.
Implemented in multiscale::analysis::Cluster, and multiscale::analysis::Region.
Referenced by updateShape().
virtual double multiscale::analysis::SpatialCollection2D::isTriangularMeasure () protected pure virtual
Get the measure that the cluster has a triangular shape.
Implemented in multiscale::analysis::Cluster, and multiscale::analysis::Region.
Referenced by updateShape().
string SpatialCollection2D::shapeAsString () protected
Return the shape of the cluster as a string.
Definition at line 97 of file SpatialCollection2D.cpp.
References multiscale::analysis::Circle, multiscale::analysis::Rectangle, shape, STR_CIRCLE, STR_RECTANGLE, STR_TRIANGLE, STR_UNDEFINED, multiscale::analysis::Triangle, and multiscale::analysis::Undefined.
Referenced by multiscale::analysis::Cluster::fieldValuesToString(), and multiscale::analysis::Region::fieldValuesToString().
string SpatialCollection2D::toString ()
Get the string representation of all field values.
Definition at line 54 of file SpatialCollection2D.cpp.
References fieldValuesToString(), and updateMeasuresIfRequired().
virtual void multiscale::analysis::SpatialCollection2D::updateArea () protected pure virtual
Update the value of the area.
Implemented in multiscale::analysis::Cluster, and multiscale::analysis::Region.
Referenced by updateMeasures().
virtual void multiscale::analysis::SpatialCollection2D::updateCentrePoint () protected pure virtual
Update the point defining the centre of the cluster.
Implemented in multiscale::analysis::Region, and multiscale::analysis::Cluster.
Referenced by updateMeasures().
virtual void multiscale::analysis::SpatialCollection2D::updateClusterednessDegree () protected pure virtual
Update the value of the clusteredness degree.
Implemented in multiscale::analysis::Region, and multiscale::analysis::Cluster.
Referenced by updateMeasures().
void SpatialCollection2D::updateMeasures () protected
Update the values of all measures.
Definition at line 69 of file SpatialCollection2D.cpp.
References updateArea(), updateCentrePoint(), updateClusterednessDegree(), updatePerimeter(), and updateShape().
Referenced by updateMeasuresIfRequired().
void SpatialCollection2D::updateMeasuresIfRequired () protected
Update the values of all measures if required.
Definition at line 60 of file SpatialCollection2D.cpp.
References updateFlag, updateMeasures(), and updateSpatialCollectionSpecificValues().
Referenced by getAngle(), getArea(), getCentre(), getClusterednessDegree(), multiscale::analysis::Region::getDensity(), getDistanceFromOrigin(), multiscale::analysis::Cluster::getMinAreaEnclosingCircleCentre(), multiscale::analysis::Cluster::getMinAreaEnclosingCircleRadius(), multiscale::analysis::Cluster::getMinAreaEnclosingRect(), multiscale::analysis::Cluster::getMinAreaEnclosingTriangle(), getPerimeter(), multiscale::analysis::Cluster::getPileUpDegree(), getShape(), and toString().
virtual void multiscale::analysis::SpatialCollection2D::updatePerimeter () protected pure virtual
Update the value of the perimeter.
Implemented in multiscale::analysis::Cluster, and multiscale::analysis::Region.
Referenced by updateMeasures().
void SpatialCollection2D::updateShape () protected
Update the shape of the cluster.
Definition at line 77 of file SpatialCollection2D.cpp.
References multiscale::analysis::Circle, circularMeasure, isCircularMeasure(), isRectangularMeasure(), isTriangularMeasure(), multiscale::analysis::Rectangle, rectangularMeasure, shape, multiscale::analysis::Triangle, and triangularMeasure.
Referenced by updateMeasures().
virtual void multiscale::analysis::SpatialCollection2D::updateSpatialCollectionSpecificValues () protected pure virtual
Update the values of all measures specific to the derived classes.
Implemented in multiscale::analysis::Region, and multiscale::analysis::Cluster.
Referenced by updateMeasuresIfRequired().
Member Data Documentation
double multiscale::analysis::SpatialCollection2D::angle protected
Angle of the region wrt the origin
Definition at line 39 of file SpatialCollection2D.hpp.
Referenced by multiscale::analysis::Cluster::fieldValuesToString(), multiscale::analysis::Region::fieldValuesToString(), getAngle(), multiscale::analysis::Cluster::initialise(), multiscale::analysis::Region::Region(), and multiscale::analysis::Cluster::setOriginDependentMembers().
double multiscale::analysis::SpatialCollection2D::area protected
Area of the spatial collection
Definition at line 35 of file SpatialCollection2D.hpp.
Referenced by multiscale::analysis::Cluster::fieldValuesToString(), multiscale::analysis::Region::fieldValuesToString(), getArea(), initialise(), multiscale::analysis::Region::isCircularMeasure(), multiscale::analysis::Cluster::isCircularMeasure(), multiscale::analysis::Region::isRectangularMeasure(), multiscale::analysis::Cluster::isRectangularMeasure(), multiscale::analysis::Region::isTriangularMeasure(), multiscale::analysis::Cluster::isTriangularMeasure(), multiscale::analysis::Region::Region(), and multiscale::analysis::Cluster::updateArea().
Point2f multiscale::analysis::SpatialCollection2D::centre protected
Point defining the centre of the spatial collection
Definition at line 46 of file SpatialCollection2D.hpp.
Referenced by multiscale::analysis::Cluster::fieldValuesToString(), multiscale::analysis::Region::fieldValuesToString(), getCentre(), multiscale::analysis::Cluster::updateCentrePoint(), and multiscale::analysis::Region::updateCentrePoint().
double multiscale::analysis::SpatialCollection2D::circularMeasure protected
Measure ([0, 1]) indicating that the shape of the spatial collection is circular
Definition at line 43 of file SpatialCollection2D.hpp.
Referenced by multiscale::analysis::Cluster::fieldValuesToString(), multiscale::analysis::Region::fieldValuesToString(), initialise(), and updateShape().
double multiscale::analysis::SpatialCollection2D::clusterednessDegree protected
Degree of clusteredness
Definition at line 33 of file SpatialCollection2D.hpp.
Referenced by multiscale::analysis::Cluster::fieldValuesToString(), multiscale::analysis::Region::fieldValuesToString(), getClusterednessDegree(), multiscale::analysis::Cluster::initialise(), multiscale::analysis::Region::Region(), and multiscale::analysis::Cluster::updateClusterednessDegree().
double multiscale::analysis::SpatialCollection2D::distanceFromOrigin protected
Distance from the origin
Definition at line 38 of file SpatialCollection2D.hpp.
Referenced by multiscale::analysis::Cluster::fieldValuesToString(), multiscale::analysis::Region::fieldValuesToString(), getDistanceFromOrigin(), multiscale::analysis::Cluster::initialise(), multiscale::analysis::Region::Region(), and multiscale::analysis::Cluster::setOriginDependentMembers().
double multiscale::analysis::SpatialCollection2D::perimeter protected
Perimeter of the spatial collection
Definition at line 36 of file SpatialCollection2D.hpp.
Referenced by multiscale::analysis::Cluster::fieldValuesToString(), multiscale::analysis::Region::fieldValuesToString(), getPerimeter(), initialise(), multiscale::analysis::Cluster::updatePerimeter(), and multiscale::analysis::Region::updatePerimeter().
double multiscale::analysis::SpatialCollection2D::rectangularMeasure protected
Measure ([0, 1]) indicating that the shape of the spatial collection is rectangular
Definition at line 42 of file SpatialCollection2D.hpp.
Referenced by multiscale::analysis::Cluster::fieldValuesToString(), multiscale::analysis::Region::fieldValuesToString(), initialise(), and updateShape().
Shape2D multiscale::analysis::SpatialCollection2D::shape protected
Shape of the spatial collection
Definition at line 45 of file SpatialCollection2D.hpp.
Referenced by getShape(), initialise(), shapeAsString(), and updateShape().
double multiscale::analysis::SpatialCollection2D::triangularMeasure protected
Measure ([0, 1]) indicating that the shape of the spatial collection is triangular
Definition at line 41 of file SpatialCollection2D.hpp.
Referenced by multiscale::analysis::Cluster::fieldValuesToString(), multiscale::analysis::Region::fieldValuesToString(), initialise(), and updateShape().
bool multiscale::analysis::SpatialCollection2D::updateFlag protected
                Flag indicating if the field values dependent on the
collection of entities need to be updated. This flag is used for lazy evaluation purposes, such that new field values are computed only when required
Definition at line 48 of file SpatialCollection2D.hpp.
Referenced by multiscale::analysis::Cluster::addEntity(), multiscale::analysis::Cluster::initialise(), initialise(), and updateMeasuresIfRequired().
The documentation for this class was generated from the following files:
include/multiscale/analysis/spatial/SpatialCollection2D.hpp
src/multiscale/analysis/spatial/SpatialCollection2D.cpp