Multiscale: multiscale::analysis::SimulationClusterDetector Class Reference
multiscale::analysis::SimulationClusterDetector Class Reference
Class for detecting clusters in 2D images obtained from simulations.
#include <SimulationClusterDetector.hpp>
Public Member Functions
SimulationClusterDetector (const Mat &inputImage, const string &outputFilepath, unsigned int height, unsigned int width, bool debugMode=false)
~SimulationClusterDetector ()
Public Member Functions inherited from multiscale::analysis::ClusterDetector
ClusterDetector (const Mat &inputImage, const string &outputFilepath, bool debugMode=false)
virtual ~ClusterDetector ()
void detect ()
Detect the clusters in the image and output the results.
Private Member Functions
void initialiseThresholdedImage ()
Initialise the thresholdedImage field.
void detectEntitiesInImage (vector< Entity > &entities)
Detect the entities in the image.
bool isEntityAtPosition (int x, int y)
Check if there is an entity in the image at the given position.
double computePileUpDegreeAtPosition (int x, int y)
Compute the pile up degree at the given position.
void outputClustersInDebugMode (vector< Cluster > &clusters) override
Output the information computed for the clusters visually in a separate window.
void outputClustersInNormalMode (vector< Cluster > &clusters) override
Output the information computed for the clusters in a in a ".csv" and ".png" file.
void outputClustersOnImage (vector< Cluster > &clusters)
Dsiaply clusters on image.
void outputClusterOnImage (Cluster &cluster, Scalar colour, Mat &image)
Display cluster on the image.
void outputClusterShape (Cluster &cluster, Scalar colour, Mat &image)
Draw the best matching shape (triangular, rectangular, circular) of the cluster on the image.
void outputClusterTriangularShape (Cluster &cluster, Scalar colour, Mat &image)
Draw the best matching triangular shape of the cluster on the image.
void outputClusterRectangularShape (Cluster &cluster, Scalar colour, Mat &image)
Draw the best matching rectangular shape of the cluster on the image.
void outputClusterCircularShape (Cluster &cluster, Scalar colour, Mat &image)
Draw the best matching circular shape of the cluster on the image.
void processSaveRequest ()
Process the save request in case the lowercase "s" key was pressed.
void saveResultsAsPNGImage ()
Store the results as a ".png" image on disk.
Private Attributes
Mat thresholdedImage
Mat outputImage
unsigned int height
unsigned int width
double entityHeight
double entityWidth
Additional Inherited Members
Protected Member Functions inherited from multiscale::analysis::ClusterDetector
void initialise ()
Initialisation function for the class.
void initialiseClusteringValues ()
Initialise clustering values.
bool isValidInputImage ()
Check if the image is valid.
void createTrackbars ()
Create the trackbars.
void detectClusters ()
Detect the clusters in the provided image.
void detectClustersInDebugMode (vector< Cluster > &clusters)
Detect the clusters in the provided image in debug mode.
void detectClustersInNormalMode (vector< Cluster > &clusters)
Detect the clusters in the provided image in normal mode.
void findClusters (vector< Cluster > &clusters)
Find clusters in the provided image.
void detectAndAnalyseClusters (const vector< Entity > &entities, vector< Cluster > &clusters)
Detect and analyse the clusters of entities in the image.
void detectClusters (const vector< Entity > &entities, vector< int > &clusterIndexes, int &nrOfClusters)
Detect the clusters of entities in the image.
vector< shared_ptr< DataPoint > > convertEntities (const vector< Entity > &entities)
Convert the entities to the required format by the DBSCAN class.
void addEntitiesToClusters (const vector< Entity > &entities, const vector< int > &clusterIndexes, int nrOfClusters, vector< Cluster > &clusters)
Add the entities to the clusters as indicated by the clusterIndexes parameter.
void analyseClusters (vector< Cluster > &clusters)
Analyse the clusters.
double computeClusterednessIndex (const vector< Cluster > &clusters)
Compute the clusteredness index for all the entities detected in the image.
double computeAveragePileUpDegree (vector< Cluster > &clusters)
Compute the average pile up degree for all entities in the image.
void outputClusters (vector< Cluster > &clusters, bool debugMode)
Output the information computed for the clusters.
void outputClustersAsCsvFile (vector< Cluster > &clusters)
Output the information computed for the clusters in a csv file.
void outputClustersAsCsvFile (vector< Cluster > &clusters, ofstream &fout)
Output the information computed for the clusters in a csv file.
void processPressedKeyRequest (char &pressedKey)
Process the request of the user by pressing the key.
void displayImage (const Mat &image, const string &windowName)
Display an image in a particular window.
double convertEpsValue ()
Convert the value of eps from integer to double.
Protected Attributes inherited from multiscale::analysis::ClusterDetector
Mat image
string outputFilepath
bool debugMode
double clusterednessIndex
double avgPileUpDegree
int eps
int minPoints
Detailed Description
Class for detecting clusters in 2D images obtained from simulations.
Definition at line 26 of file SimulationClusterDetector.hpp.
Constructor & Destructor Documentation
SimulationClusterDetector::SimulationClusterDetector (const Mat & inputImage, const string & outputFilepath, unsigned int height, unsigned int width, bool debugMode = false)
Definition at line 9 of file SimulationClusterDetector.cpp.
References entityHeight, entityWidth, height, initialiseThresholdedImage(), and width.
SimulationClusterDetector::~SimulationClusterDetector ()
Definition at line 21 of file SimulationClusterDetector.cpp.
Member Function Documentation
double SimulationClusterDetector::computePileUpDegreeAtPosition (int x, int y) private
Compute the pile up degree at the given position.
Parameters
x Coordinate for Ox axis
y Coordinate for Oy axis
Definition at line 53 of file SimulationClusterDetector.cpp.
References entityHeight, entityWidth, and multiscale::analysis::ClusterDetector::image.
Referenced by detectEntitiesInImage().
void SimulationClusterDetector::detectEntitiesInImage (vector< Entity > & entities) private virtual
Detect the entities in the image.
Detect the entities in the image, compute their centre point and degree of pile up
Parameters
entities Entities detected in the image
Implements multiscale::analysis::ClusterDetector.
Definition at line 27 of file SimulationClusterDetector.cpp.
References computePileUpDegreeAtPosition(), entityHeight, entityWidth, height, isEntityAtPosition(), and width.
void SimulationClusterDetector::initialiseThresholdedImage () private
Initialise the thresholdedImage field.
Definition at line 23 of file SimulationClusterDetector.cpp.
References multiscale::analysis::ClusterDetector::image, THRESHOLD, THRESHOLD_MAX, and thresholdedImage.
Referenced by SimulationClusterDetector().
bool SimulationClusterDetector::isEntityAtPosition (int x, int y) private
Check if there is an entity in the image at the given position.
Parameters
x Coordinate for Ox axis
y Coordinate for Oy axis
Definition at line 45 of file SimulationClusterDetector.cpp.
References ENTITY_THRESH, entityHeight, entityWidth, and thresholdedImage.
Referenced by detectEntitiesInImage().
void SimulationClusterDetector::outputClusterCircularShape (Cluster & cluster, Scalar colour, Mat & image) private
Draw the best matching circular shape of the cluster on the image.
Parameters
cluster Cluster
colour Colour associated to all entities in the cluster
image The image on which to display the cluster related information
Definition at line 140 of file SimulationClusterDetector.cpp.
References DATAPOINT_WIDTH, multiscale::analysis::Cluster::getMinAreaEnclosingCircleCentre(), and multiscale::analysis::Cluster::getMinAreaEnclosingCircleRadius().
Referenced by outputClusterShape().
void SimulationClusterDetector::outputClusterOnImage (Cluster & cluster, Scalar colour, Mat & image) private
Display cluster on the image.
Parameters
cluster Cluster
colour Colour associated to all entities in the cluster
image The image on which to display the cluster related information
Definition at line 88 of file SimulationClusterDetector.cpp.
References DATAPOINT_THICKNESS, DATAPOINT_WIDTH, multiscale::analysis::Cluster::getEntities(), and outputClusterShape().
Referenced by outputClustersOnImage().
void SimulationClusterDetector::outputClusterRectangularShape (Cluster & cluster, Scalar colour, Mat & image) private
Draw the best matching rectangular shape of the cluster on the image.
Parameters
cluster Cluster
colour Colour associated to all entities in the cluster
image The image on which to display the cluster related information
Definition at line 130 of file SimulationClusterDetector.cpp.
References DATAPOINT_WIDTH, and multiscale::analysis::Cluster::getMinAreaEnclosingRect().
Referenced by outputClusterShape().
void SimulationClusterDetector::outputClusterShape (Cluster & cluster, Scalar colour, Mat & image) private
Draw the best matching shape (triangular, rectangular, circular) of the cluster on the image.
Parameters
cluster Cluster
colour Colour associated to all entities in the cluster
image The image on which to display the cluster related information
Definition at line 98 of file SimulationClusterDetector.cpp.
References multiscale::analysis::Circle, ERR_UNDEFINED_SHAPE, multiscale::analysis::Cluster::getShape(), outputClusterCircularShape(), outputClusterRectangularShape(), outputClusterTriangularShape(), multiscale::analysis::Rectangle, and multiscale::analysis::Triangle.
Referenced by outputClusterOnImage().
void SimulationClusterDetector::outputClustersInDebugMode (vector< Cluster > & clusters) override private virtual
Output the information computed for the clusters visually in a separate window.
Output the information computed for the clusters visually in a separate window
Parameters
clusters Clusters of entities detected in the image
Implements multiscale::analysis::ClusterDetector.
Definition at line 61 of file SimulationClusterDetector.cpp.
References multiscale::analysis::ClusterDetector::displayImage(), outputClustersOnImage(), outputImage, and WIN_OUTPUT_IMAGE.
void SimulationClusterDetector::outputClustersInNormalMode (vector< Cluster > & clusters) override private virtual
Output the information computed for the clusters in a in a ".csv" and ".png" file.
Parameters
clusters Clusters of entities detected in the image
Implements multiscale::analysis::ClusterDetector.
Definition at line 66 of file SimulationClusterDetector.cpp.
References multiscale::analysis::ClusterDetector::outputClustersAsCsvFile(), outputClustersOnImage(), and saveResultsAsPNGImage().
void SimulationClusterDetector::outputClustersOnImage (vector< Cluster > & clusters) private
Dsiaply clusters on image.
Parameters
clusters Clusters of entities detected in the image
Definition at line 72 of file SimulationClusterDetector.cpp.
References multiscale::RGBColourGenerator::generate(), multiscale::analysis::ClusterDetector::image, outputClusterOnImage(), and outputImage.
Referenced by outputClustersInDebugMode(), and outputClustersInNormalMode().
void SimulationClusterDetector::outputClusterTriangularShape (Cluster & cluster, Scalar colour, Mat & image) private
Draw the best matching triangular shape of the cluster on the image.
Parameters
cluster Cluster
colour Colour associated to all entities in the cluster
image The image on which to display the cluster related information
Definition at line 120 of file SimulationClusterDetector.cpp.
References DATAPOINT_WIDTH, and multiscale::analysis::Cluster::getMinAreaEnclosingTriangle().
Referenced by outputClusterShape().
void SimulationClusterDetector::processSaveRequest () private virtual
Process the save request in case the lowercase "s" key was pressed.
Implements multiscale::analysis::ClusterDetector.
Definition at line 147 of file SimulationClusterDetector.cpp.
References saveResultsAsPNGImage().
void SimulationClusterDetector::saveResultsAsPNGImage () private
Store the results as a ".png" image on disk.
Definition at line 151 of file SimulationClusterDetector.cpp.
References IMG_EXTENSION, MSG_IMG_SAVED, multiscale::analysis::ClusterDetector::outputFilepath, and outputImage.
Referenced by outputClustersInNormalMode(), and processSaveRequest().
Member Data Documentation
double multiscale::analysis::SimulationClusterDetector::entityHeight private
Height of an entity
Definition at line 36 of file SimulationClusterDetector.hpp.
Referenced by computePileUpDegreeAtPosition(), detectEntitiesInImage(), isEntityAtPosition(), and SimulationClusterDetector().
double multiscale::analysis::SimulationClusterDetector::entityWidth private
Width of an entity
Definition at line 37 of file SimulationClusterDetector.hpp.
Referenced by computePileUpDegreeAtPosition(), detectEntitiesInImage(), isEntityAtPosition(), and SimulationClusterDetector().
unsigned int multiscale::analysis::SimulationClusterDetector::height private
Height of the grid used in the simulation
Definition at line 33 of file SimulationClusterDetector.hpp.
Referenced by detectEntitiesInImage(), and SimulationClusterDetector().
Mat multiscale::analysis::SimulationClusterDetector::outputImage private
Image for displaying the results
Definition at line 31 of file SimulationClusterDetector.hpp.
Referenced by outputClustersInDebugMode(), outputClustersOnImage(), and saveResultsAsPNGImage().
Mat multiscale::analysis::SimulationClusterDetector::thresholdedImage private
Thresholded version of the image
Definition at line 30 of file SimulationClusterDetector.hpp.
Referenced by initialiseThresholdedImage(), and isEntityAtPosition().
unsigned int multiscale::analysis::SimulationClusterDetector::width private
Width of the grid used in the simulation
Definition at line 34 of file SimulationClusterDetector.hpp.
Referenced by detectEntitiesInImage(), and SimulationClusterDetector().
The documentation for this class was generated from the following files:
include/multiscale/analysis/spatial/cluster/SimulationClusterDetector.hpp
src/multiscale/analysis/spatial/cluster/SimulationClusterDetector.cpp