Multiscale: multiscale::Geometry2D Class Reference
multiscale::Geometry2D Class Reference
Two-dimensional geometric operations.
#include <Geometry2D.hpp>
Public Member Functions
template<typename T , typename U >
bool isBetweenCoordinates (T c, U c1, U c2)
Static Public Member Functions
static double angleOfLineWrtOxAxis (const Point2f &a, const Point2f &b)
Get the angle of the line measured from the Ox axis in counterclockwise direction.
static bool isAngleBetween (double angle1, double angle2, double angle3)
Check if angle1 lies between angles 2 and 3.
static bool isOppositeAngleBetween (double angle1, double angle2, double angle3)
Check if the opposite of angle1, ((angle1 + 180) % 360), lies between angles 2 and 3.
static bool isAngleBetweenNonReflex (double angle1, double angle2, double angle3)
Check if angle1 lies between non reflex angle determined by angles 2 and 3.
static bool isOppositeAngleBetweenNonReflex (double angle1, double angle2, double angle3)
Check if the opposite of angle1, ((angle1 + 180) % 360), lies between non reflex angle determined by angles 2 and 3.
static double oppositeAngle (double angle)
Return the angle opposite to the given angle.
static bool slopeOfLine (const Point2f &a, const Point2f &b, double &slope)
Compute the slope of the line defined by points "a" and "b".
static double distanceBtwPoints (const Point2f &a, const Point2f &b)
Compute the distance between two points.
static double distanceFromPointToLine (const Point2f &a, const Point2f &linePointB, const Point2f &linePointC)
Compute the distance from a point "a" to a line specified by two points "B" and "C".
static Point2f middlePoint (const Point2f &a, const Point2f &b)
Get the point in the middle of the segment determined by points "a" and "b".
static void orthogonalLineToAnotherLineEdgePoints (const Point &a1, const Point &b1, Point &a2, Point &b2, int nrOfRows, int nrOfCols)
Find the points which are on the edge and on the line orthogonal to the line defined by 2 given points.
static bool areOnTheSameSideOfLine (const Point2f &p1, const Point2f &p2, const Point2f &a, const Point2f &b)
Check if p1 and p2 are on the same side of the line determined by points a and b.
static void lineEquationDeterminedByPoints (const Point2f &p, const Point2f &q, double &a, double &b, double &c)
Get the values of "a", "b" and "c" of the line equation ax + by + c = 0 knowing that point "p" and "q" are on the line.
static bool areIdenticalLines (double a1, double b1, double c1, double a2, double b2, double c2)
Check if two lines are identical.
static bool areIdenticalLines (const Point2f &a1, const Point2f &b1, const Point2f &a2, const Point2f &b2)
Check if two lines are identical.
static bool lineIntersection (const Point2f &a1, const Point2f &b1, const Point2f &a2, const Point2f &b2, Point2f &intersection)
Determine the intersection point of two lines, if this point exists.
static bool lineIntersection (const Point &a1, const Point &b1, const Point &a2, const Point &b2, Point &intersection)
Determine the intersection point of two lines, if this point exists.
static bool lineIntersection (double a1, double b1, double c1, double a2, double b2, double c2, Point2f &intersection)
Determine the intersection point of two lines, if this point exists.
static bool lineSegmentIntersection (const Point &a1, const Point &b1, const Point &a2, const Point &b2, Point &intersection)
Determine the intersection point of two line segments, if this point exists.
static bool lineCircleIntersection (Point2f a, Point2f b, const Point2f &circleOrigin, double radius, vector< Point2f > &intersectionPoints)
Determine if a line and a circle intersect and return the intersection points if they exist.
static bool lineSegmentCircleIntersection (const Point2f &a, const Point2f &b, const Point2f &circleOrigin, double radius, vector< Point2f > &intersectionPoints)
Determine if a line segment and a circle intersect and return the intersection points if they exist.
static double angleBtwPoints (const Point2f &a, const Point2f &b, const Point2f &c)
Compute the angle between three points.
static vector< Point2f > findPointsOnEdge (const vector< Point2f > &points, unsigned int nrOfRows, unsigned int nrOfCols)
Find the subset of points from the given set of points which lie on the edge.
static unsigned int minimumDistancePointIndex (const vector< Point > &points, const Point2f &origin)
Get the index of the point which is the closest to the origin.
static double areaOfTriangle (const Point2f &a, const Point2f &b, const Point2f &c)
Compute the area of a triangle defined by three points.
static bool isPointOnLineSegment (const Point2f &point, const Point2f &lineSegmentStart, const Point2f &lineSegmentEnd)
Check if one point lies between two other points.
static bool areEqualPoints (const Point2f &point1, const Point2f &point2)
Check if points point1 and point2 are equal or not.
static bool areCollinear (const Point2f &point1, const Point2f &point2, const Point2f &point3)
Check if the three points are collinear.
Static Private Member Functions
static bool isPointOnEdge (const Point2f &p, int nrOfRows, int nrOfCols)
Check if the given point is on the edge.
template<typename T , typename U >
static bool isBetweenCoordinates (T c, U c1, U c2)
Check if the coordinate c lies between c1 and c2.
static void translate (Point2f &point, const Point2f &translation)
Translate a point by the given values.
static void inverseTranslate (Point2f &point, const Point2f &translation)
Inverse translate a point by the given values.
static void lineCircleTwoIntersectionPoints (const Point2f &circleOrigin, double A, double B, double C, double delta, vector< Point2f > &intersectionPoints)
Treat the case when the line and circle intersect in two points.
static void lineCircleOneIntersectionPoint (const Point2f &circleOrigin, double A, double B, double C, double delta, vector< Point2f > &intersectionPoints)
Treat the case when the line and circle intersect in one point.
Detailed Description
Two-dimensional geometric operations.
Definition at line 19 of file Geometry2D.hpp.
Member Function Documentation
double Geometry2D::angleBtwPoints (const Point2f & a, const Point2f & b, const Point2f & c) static
Compute the angle between three points.
Compute the angle between the lines determined by points A, B and B, C
Parameters
a Point2f a
b Point2f b
c Point2f c
Definition at line 307 of file Geometry2D.cpp.
References PI.
Referenced by multiscale::analysis::RegionDetector::regionAngle().
double Geometry2D::angleOfLineWrtOxAxis (const Point2f & a, const Point2f & b) static
Get the angle of the line measured from the Ox axis in counterclockwise direction.
The line is specified by points "a" and "b". The value of the angle is expressed in degrees.
Parameters
a Point2f a
b Point2f b
Definition at line 9 of file Geometry2D.cpp.
References PI.
Referenced by multiscale::MinimumAreaEnclosingTriangle::intersects(), multiscale::MinimumAreaEnclosingTriangle::intersectsAbove(), and multiscale::MinimumAreaEnclosingTriangle::intersectsBelow().
double Geometry2D::areaOfTriangle (const Point2f & a, const Point2f & b, const Point2f & c) static
Compute the area of a triangle defined by three points.
The area is computed using the determinant method. An example is presented at http://demonstrations.wolfram.com/TheAreaOfATriangleUsingADeterminant/ (Last access: 10.07.2013)
Parameters
a Point2f a
b Point2f b
c Point2f c
Definition at line 352 of file Geometry2D.cpp.
Referenced by multiscale::MinimumAreaEnclosingTriangle::updateMinimumAreaEnclosingTriangle().
bool Geometry2D::areCollinear (const Point2f & point1, const Point2f & point2, const Point2f & point3) static
Check if the three points are collinear.
Parameters
point1 Point 1
point2 Point 2
point3 Point 3
Definition at line 374 of file Geometry2D.cpp.
References multiscale::Numeric::almostEqual().
bool Geometry2D::areEqualPoints (const Point2f & point1, const Point2f & point2) static
Check if points point1 and point2 are equal or not.
Parameters
point1 One point
point2 The other point
Definition at line 370 of file Geometry2D.cpp.
References multiscale::Numeric::almostEqual().
Referenced by multiscale::MinimumAreaEnclosingTriangle::isValidMinimalTriangle(), and lineEquationDeterminedByPoints().
bool Geometry2D::areIdenticalLines (double a1, double b1, double c1, double a2, double b2, double c2) static
Check if two lines are identical.
Lines are be specified in the following form: A1x + B1x = C1 A2x + B2x = C2
If (A1/A2) == (B1/B2) == (C1/C2), then the lines are identical else they are not
Parameters
a1 A1
b1 B1
c1 C1
a2 A2
b2 B2
c2 C2
Definition at line 161 of file Geometry2D.cpp.
References multiscale::Numeric::almostEqual().
Referenced by multiscale::MinimumAreaEnclosingTriangle::areIdenticalLines().
bool Geometry2D::areIdenticalLines (const Point2f & a1, const Point2f & b1, const Point2f & a2, const Point2f & b2) static
Check if two lines are identical.
The lines are specified by a pair of points each. If they are identical, then the function returns true, else it returns false.
Lines can be specified in the following form: A1x + B1x = C1 A2x + B2x = C2
If (A1/A2) == (B1/B2) == (C1/C2), then the lines are identical else they are not
Parameters
a1 First point for determining the first line
b1 Second point for determining the first line
a2 First point for determining the second line
b2 Second point for determining the second line
Definition at line 172 of file Geometry2D.cpp.
References multiscale::Numeric::almostEqual().
bool Geometry2D::areOnTheSameSideOfLine (const Point2f & p1, const Point2f & p2, const Point2f & a, const Point2f & b) static
Check if p1 and p2 are on the same side of the line determined by points a and b.
Parameters
p1 Point p1
p2 Point p2
a First point for determining line
b Second point for determining line
Definition at line 141 of file Geometry2D.cpp.
References lineEquationDeterminedByPoints(), and multiscale::Numeric::sign().
Referenced by multiscale::MinimumAreaEnclosingTriangle::findVertexCOnSideB(), and multiscale::MinimumAreaEnclosingTriangle::gamma().
double Geometry2D::distanceBtwPoints (const Point2f & a, const Point2f & b) static
Compute the distance between two points.
Compute the Euclidean distance between two points
Parameters
a Point2f a
b Point2f b
Definition at line 69 of file Geometry2D.cpp.
Referenced by multiscale::analysis::Silhouette::computeAverageDissimilarityBtwEntityAndCluster(), multiscale::analysis::Silhouette::computeAverageDissimilarityWithinCluster(), multiscale::analysis::RegionDetector::createRegionFromPolygon(), multiscale::analysis::Entity::distanceTo(), isPointOnLineSegment(), and minimumDistancePointIndex().
double Geometry2D::distanceFromPointToLine (const Point2f & a, const Point2f & linePointB, const Point2f & linePointC) static
Compute the distance from a point "a" to a line specified by two points "B" and "C".
Formula used:
|(x_c - x_b) * (y_b - y_a) - (x_b - x_a) * (y_c - y_b)|
d = ----------------------------------------------------— sqrt(((x_c - x_b)^2) + ((y_c - y_b)^2))
Reference: http://mathworld.wolfram.com/Point-LineDistance2-Dimensional.html
Parameters
a Point2f from which the distance is measures
linePointB One of the points determining the line
linePointC One of the points determining the line
Definition at line 76 of file Geometry2D.cpp.
Referenced by multiscale::MinimumAreaEnclosingTriangle::height().
vector< Point2f > Geometry2D::findPointsOnEdge (const vector< Point2f > & points, unsigned int nrOfRows, unsigned int nrOfCols) static
Find the subset of points from the given set of points which lie on the edge.
A point "p" is considered to be on the edge if: ((p.x == 1) && (p.y > 1) && (p.y < nrOfCols)) OR ((p.x == nrOfRows) && (p.y > 1) && (p.y < nrOfCols)) OR ((p.y == 1) && (p.x > 1) && (p.x < nrOfRows)) OR ((p.y == nrOfCols) && (p.x > 1) && (p.x < nrOfRows))
Parameters
points The set of points
nrOfRows The number of rows
nrOfCols The number of columns
Definition at line 319 of file Geometry2D.cpp.
References isPointOnEdge().
void Geometry2D::inverseTranslate (Point2f & point, const Point2f & translation) static private
Inverse translate a point by the given values.
Parameters
point The point
translation Translation values
Definition at line 400 of file Geometry2D.cpp.
Referenced by lineCircleOneIntersectionPoint(), and lineCircleTwoIntersectionPoints().
bool Geometry2D::isAngleBetween (double angle1, double angle2, double angle3) static
Check if angle1 lies between angles 2 and 3.
Parameters
angle1 The angle which lies between angle2 and angle3 or not
angle2 One of the boundary angles
angle3 The other boundary angle
Definition at line 19 of file Geometry2D.cpp.
Referenced by isAngleBetweenNonReflex(), and isOppositeAngleBetween().
bool Geometry2D::isAngleBetweenNonReflex (double angle1, double angle2, double angle3) static
Check if angle1 lies between non reflex angle determined by angles 2 and 3.
Parameters
angle1 The angle which lies between angle2 and angle3 or not
angle2 One of the boundary angles
angle3 The other boundary angle
Definition at line 33 of file Geometry2D.cpp.
References isAngleBetween(), and multiscale::Numeric::lessOrEqual().
Referenced by multiscale::MinimumAreaEnclosingTriangle::isFlushAngleBetweenPredecessorAndSuccessor(), multiscale::MinimumAreaEnclosingTriangle::isGammaAngleBetween(), and isOppositeAngleBetweenNonReflex().
template<typename T , typename U > bool multiscale::Geometry2D::isBetweenCoordinates (T c, U c1, U c2)
Definition at line 391 of file Geometry2D.cpp.
template<typename T , typename U > static bool multiscale::Geometry2D::isBetweenCoordinates (T c, U c1, U c2) static private
Check if the coordinate c lies between c1 and c2.
Parameters
c Coordinate c
c1 Coordinate c1
c2 Coordinate c2
bool Geometry2D::isOppositeAngleBetween (double angle1, double angle2, double angle3) static
Check if the opposite of angle1, ((angle1 + 180) % 360), lies between angles 2 and 3.
Parameters
angle1 The angle for which the opposite angle lies between angle2 and angle3 or not
angle2 One of the boundary angles
angle3 The other boundary angle
Definition at line 27 of file Geometry2D.cpp.
References isAngleBetween(), and oppositeAngle().
bool Geometry2D::isOppositeAngleBetweenNonReflex (double angle1, double angle2, double angle3) static
Check if the opposite of angle1, ((angle1 + 180) % 360), lies between non reflex angle determined by angles 2 and 3.
Parameters
angle1 The angle which lies between angle2 and angle3 or not
angle2 One of the boundary angles
angle3 The other boundary angle
Definition at line 45 of file Geometry2D.cpp.
References isAngleBetweenNonReflex(), and oppositeAngle().
Referenced by multiscale::MinimumAreaEnclosingTriangle::isFlushAngleBetweenPredecessorAndSuccessor().
bool Geometry2D::isPointOnEdge (const Point2f & p, int nrOfRows, int nrOfCols) static private
Check if the given point is on the edge.
A point "p" is considered to be on the edge if: ((p.x == 1) && (p.y > 1) && (p.y < nrOfCols)) OR ((p.x == nrOfRows) && (p.y > 1) && (p.y < nrOfCols)) OR ((p.y == 1) && (p.x > 1) && (p.x < nrOfRows)) OR ((p.y == nrOfCols) && (p.x > 1) && (p.x < nrOfRows))
Parameters
p Point2f p
nrOfRows The number of rows
nrOfCols The number of columns
Definition at line 381 of file Geometry2D.cpp.
References MATRIX_START_INDEX.
Referenced by findPointsOnEdge(), and orthogonalLineToAnotherLineEdgePoints().
bool Geometry2D::isPointOnLineSegment (const Point2f & point, const Point2f & lineSegmentStart, const Point2f & lineSegmentEnd) static
Check if one point lies between two other points.
Parameters
point Point lying possibly outside the line segment
lineSegmentStart First point determining the line segment
lineSegmentEnd Second point determining the line segment
Definition at line 361 of file Geometry2D.cpp.
References multiscale::Numeric::almostEqual(), and distanceBtwPoints().
Referenced by multiscale::MinimumAreaEnclosingTriangle::isValidMinimalTriangle().
bool Geometry2D::lineCircleIntersection (Point2f a, Point2f b, const Point2f & circleOrigin, double radius, vector< Point2f > & intersectionPoints) static
Determine if a line and a circle intersect and return the intersection points if they exist.
We translate all the points such that the circle origin coincides with the origin of the coordinate system. When returning the results, the intersection points are inverse translated.
Parameters
a First point for determining the line
b Second point for determining the line
circleOrigin Origin of the circle
radius Radius of the circle
intersectionPoints The intersection points between the circle and the line
< Two intersection points
< One intersection point
Definition at line 259 of file Geometry2D.cpp.
References lineCircleOneIntersectionPoint(), lineCircleTwoIntersectionPoints(), and translate().
Referenced by lineSegmentCircleIntersection().
void Geometry2D::lineCircleOneIntersectionPoint (const Point2f & circleOrigin, double A, double B, double C, double delta, vector< Point2f > & intersectionPoints) static private
Treat the case when the line and circle intersect in one point.
Parameters
circleOrigin Origin of the circle
A y2 - y1
B x1 - x2
C A*x1 + B*y1
delta (4 * B^2 * C^2) - (4 * (A^2 + B^2) * (C^2 - (R^2 * A^2)))
intersectionPoints Intersection points
Definition at line 423 of file Geometry2D.cpp.
References inverseTranslate().
Referenced by lineCircleIntersection().
void Geometry2D::lineCircleTwoIntersectionPoints (const Point2f & circleOrigin, double A, double B, double C, double delta, vector< Point2f > & intersectionPoints) static private
Treat the case when the line and circle intersect in two points.
Parameters
circleOrigin Origin of the circle
A y2 - y1
B x1 - x2
C A*x1 + B*y1
delta (4 * B^2 * C^2) - (4 * (A^2 + B^2) * (C^2 - (R^2 * A^2)))
intersectionPoints Intersection points
Definition at line 405 of file Geometry2D.cpp.
References inverseTranslate().
Referenced by lineCircleIntersection().
void Geometry2D::lineEquationDeterminedByPoints (const Point2f & p, const Point2f & q, double & a, double & b, double & c) static
Get the values of "a", "b" and "c" of the line equation ax + by + c = 0 knowing that point "p" and "q" are on the line.
a = q.y - p.y b = p.x - q.x c = - (p.x * a) - (p.y * b)
Parameters
p Point2f p
q Point2f q
a Parameter "a" from the line equation
b Parameter "b" from the line equation
c Parameter "c" from the line equation
Definition at line 153 of file Geometry2D.cpp.
References areEqualPoints().
Referenced by areOnTheSameSideOfLine(), and multiscale::MinimumAreaEnclosingTriangle::lineEquationParameters().
bool Geometry2D::lineIntersection (const Point2f & a1, const Point2f & b1, const Point2f & a2, const Point2f & b2, Point2f & intersection) static
Determine the intersection point of two lines, if this point exists.
Two lines intersect if they are not parallel (Parallel lines intersect at +/- infinity, but we do not consider this case here).
The lines are specified by a pair of points each. If they intersect, then the function returns true, else it returns false.
Lines can be specified in the following form: A1x + B1x = C1 A2x + B2x = C2
If det (= A1xB2 - A2xB1) == 0, then lines are parallel else they intersect
If they intersect, then let us denote the intersection point with P(x, y) where: x = (C1xB2 - C2xB1) / (det) y = (C2xA1 - C1xA2) / (det)
Parameters
a1 First point for determining the first line
b1 Second point for determining the first line
a2 First point for determining the second line
b2 Second point for determining the second line
intersection The intersection point, if this point exists
Definition at line 212 of file Geometry2D.cpp.
References multiscale::Numeric::almostEqual().
Referenced by multiscale::MinimumAreaEnclosingTriangle::areIntersectingLines(), multiscale::MinimumAreaEnclosingTriangle::isLocalMinimalTriangle(), lineSegmentIntersection(), and multiscale::MinimumAreaEnclosingTriangle::middlePointOfSideB().
bool Geometry2D::lineIntersection (const Point & a1, const Point & b1, const Point & a2, const Point & b2, Point & intersection) static
Determine the intersection point of two lines, if this point exists.
Two lines intersect if they are not parallel (Parallel lines intersect at +/- infinity, but we do not consider this case here).
The lines are specified by a pair of points each. If they intersect, then the function returns true, else it returns false.
Lines can be specified in the following form: A1x + B1x = C1 A2x + B2x = C2
If det (= A1xB2 - A2xB1) == 0, then lines are parallel else they intersect
If they intersect, then let us denote the intersection point with P(x, y) where: x = (C1xB2 - C2xB1) / (det) y = (C2xA1 - C1xA2) / (det)
Parameters
a1 First point for determining the first line
b1 Second point for determining the first line
a2 First point for determining the second line
b2 Second point for determining the second line
intersection The intersection point, if this point exists
Definition at line 191 of file Geometry2D.cpp.
References multiscale::Numeric::almostEqual().
bool Geometry2D::lineIntersection (double a1, double b1, double c1, double a2, double b2, double c2, Point2f & intersection) static
Determine the intersection point of two lines, if this point exists.
Two lines intersect if they are not parallel (Parallel lines intersect at +/- infinity, but we do not consider this case here).
The lines are specified in the following form: A1x + B1x = C1 A2x + B2x = C2
If det (= A1xB2 - A2xB1) == 0, then lines are parallel else they intersect
If they intersect, then let us denote the intersection point with P(x, y) where: x = (C1xB2 - C2xB1) / (det) y = (C2xA1 - C1xA2) / (det)
Parameters
a1 A1
b1 B1
c1 C1
a2 A2
b2 B2
c2 C2
intersection The intersection point, if this point exists
Definition at line 233 of file Geometry2D.cpp.
References multiscale::Numeric::almostEqual().
bool Geometry2D::lineSegmentCircleIntersection (const Point2f & a, const Point2f & b, const Point2f & circleOrigin, double radius, vector< Point2f > & intersectionPoints) static
Determine if a line segment and a circle intersect and return the intersection points if they exist.
We translate all the points such that the circle origin coincides with the origin of the coordinate system. When returning the results, the intersection points are inverse translated.
Parameters
a First point for determining the line
b Second point for determining the line
circleOrigin Origin of the circle
radius Radius of the circle
intersectionPoints The intersection points between the circle and the line
Definition at line 288 of file Geometry2D.cpp.
References lineCircleIntersection().
bool Geometry2D::lineSegmentIntersection (const Point & a1, const Point & b1, const Point & a2, const Point & b2, Point & intersection) static
Determine the intersection point of two line segments, if this point exists.
Find the intersection point of the lines, if this point exists. Let us assume that this point exists and let us denote it with P(x, y). Then, in order for the point to be the intersection of the segments and not of the lines, we have to verify the following conditions:
min(a1.x, b1.x) <= x <= max(a1.x, b1.x) – x coordinate is valid for first line segment
min(a2.x, b2.x) <= x <= max(a2.x, b2.x) – x coordinate is valid for second line segment
min(a1.y, b1.y) <= y <= max(a1.y, b1.y) – y coordinate is valid for first line segment
min(a2.y, b2.y) <= y <= max(a2.y, b2.y) – y coordinate is valid for second line segment
Parameters
a1 First point for determining the first line
b1 Second point for determining the first line
a2 First point for determining the second line
b2 Second point for determining the second line
intersection The intersection point, if this point exists
Definition at line 246 of file Geometry2D.cpp.
References lineIntersection().
Referenced by multiscale::analysis::RegionDetector::findGoodIntersectionPoints().
Point2f Geometry2D::middlePoint (const Point2f & a, const Point2f & b) static
Get the point in the middle of the segment determined by points "a" and "b".
Parameters
a Point2f a
b Point2f b
Definition at line 88 of file Geometry2D.cpp.
Referenced by multiscale::MinimumAreaEnclosingTriangle::isValidMinimalTriangle(), and multiscale::MinimumAreaEnclosingTriangle::middlePointOfSideB().
unsigned int Geometry2D::minimumDistancePointIndex (const vector< Point > & points, const Point2f & origin) static
Get the index of the point which is the closest to the origin.
Get the index of the point P from the given set of points, such that for any point A from the set of points dist(A, origin) >= dist(P, origin).
Parameters
points The set of points
origin The origin
Definition at line 333 of file Geometry2D.cpp.
References distanceBtwPoints().
Referenced by multiscale::analysis::RegionDetector::createRegionFromPolygon().
double Geometry2D::oppositeAngle (double angle) static
Return the angle opposite to the given angle.
if (angle < 180) then return (angle + 180); else return (angle - 180); endif
Parameters
angle Angle
Definition at line 51 of file Geometry2D.cpp.
Referenced by multiscale::MinimumAreaEnclosingTriangle::isFlushAngleBetweenPredecessorAndSuccessor(), isOppositeAngleBetween(), and isOppositeAngleBetweenNonReflex().
void Geometry2D::orthogonalLineToAnotherLineEdgePoints (const Point & a1, const Point & b1, Point & a2, Point & b2, int nrOfRows, int nrOfCols) static
Find the points which are on the edge and on the line orthogonal to the line defined by 2 given points.
Parameters
a1 First point for determining the first line
b1 Second point for determining the first line
a2 First point for determining the second line
b2 Second point for determining the second line
nrOfRows Maximum number of rows in the considered matrix
nrOfCols Maximum number of columns in the considered matrix
Definition at line 95 of file Geometry2D.cpp.
References isPointOnEdge().
Referenced by multiscale::analysis::RegionDetector::findGoodPointsForAngle().
bool Geometry2D::slopeOfLine (const Point2f & a, const Point2f & b, double & slope) static
Compute the slope of the line defined by points "a" and "b".
Returns true if the slope of the line can be computed and false otherwise.
Parameters
a Point2f a
b Point2f b
slope Slope of the line if it is different from (+/-)infinity
Definition at line 56 of file Geometry2D.cpp.
void Geometry2D::translate (Point2f & point, const Point2f & translation) static private
Translate a point by the given values.
Parameters
point The point
translation Translation values
Definition at line 395 of file Geometry2D.cpp.
Referenced by lineCircleIntersection().
The documentation for this class was generated from the following files:
include/multiscale/util/Geometry2D.hpp
src/multiscale/util/Geometry2D.cpp