Multiscale: multiscale::video::CartesianToPolarConverter Class Reference
multiscale::video::CartesianToPolarConverter Class Reference
Converter from the rectangular geometry grid cells to annular sectors.
#include <CartesianToPolarConverter.hpp>
Public Member Functions
CartesianToPolarConverter (const string &inputFilepath, const string &outputFilepath)
~CartesianToPolarConverter ()
void convert (bool outputToScript)
Start the conversion.
Private Member Functions
void readInputData () throw (string)
Read the input data.
void readHeaderLine (ifstream &fin) throw (string)
Read the header line.
void readConcentrations (ifstream &fin) throw (string)
Read the concentrations.
void transformToAnnularSectors ()
Convert the concentrations to annular sectors.
void outputResultsAsFile ()
Output the results as a plain file.
void outputResultsAsScript ()
Output the results as a gnuplot script.
Private Attributes
vector< AnnularSector > annularSectors
vector< double > concentrations
unsigned long nrOfConcentricCircles
unsigned long nrOfSectors
double simulationTime
string inputFilepath
string outputFilepath
Detailed Description
Converter from the rectangular geometry grid cells to annular sectors.
Definition at line 28 of file CartesianToPolarConverter.hpp.
Constructor & Destructor Documentation
CartesianToPolarConverter::CartesianToPolarConverter (const string & inputFilepath, const string & outputFilepath)
Definition at line 14 of file CartesianToPolarConverter.cpp.
References nrOfConcentricCircles, nrOfSectors, and simulationTime.
CartesianToPolarConverter::~CartesianToPolarConverter ()
Definition at line 23 of file CartesianToPolarConverter.cpp.
Member Function Documentation
void CartesianToPolarConverter::convert (bool outputToScript)
Start the conversion.
Parameters
outputToScript Output to script or to plain file
Definition at line 25 of file CartesianToPolarConverter.cpp.
References outputResultsAsFile(), outputResultsAsScript(), readInputData(), and transformToAnnularSectors().
Referenced by main().
void CartesianToPolarConverter::outputResultsAsFile () private
Output the results as a plain file.
Definition at line 108 of file CartesianToPolarConverter.cpp.
References annularSectors, OUTPUT_FILE_EXTENSION, and outputFilepath.
Referenced by convert().
void CartesianToPolarConverter::outputResultsAsScript () private
Output the results as a gnuplot script.
Definition at line 123 of file CartesianToPolarConverter.cpp.
References annularSectors, multiscale::video::PolarGnuplotScriptGenerator::generateScript(), outputFilepath, and simulationTime.
Referenced by convert().
void CartesianToPolarConverter::readConcentrations (ifstream & fin) throw (string) private
Read the concentrations.
Parameters
fin Input file stream
Definition at line 65 of file CartesianToPolarConverter.cpp.
References ERR_CONC.
Referenced by readInputData().
void CartesianToPolarConverter::readHeaderLine (ifstream & fin) throw (string) private
Read the header line.
The header line contains values for number of concentric circles, number of sectors and simulation time
Parameters
fin Input file stream
Definition at line 56 of file CartesianToPolarConverter.cpp.
References ERR_NEG_SIM_TIME, and ERR_NONPOS_DIMENSION.
Referenced by readInputData().
void CartesianToPolarConverter::readInputData () throw (string) private
Read the input data.
Definition at line 36 of file CartesianToPolarConverter.cpp.
References ERR_IN_EXTRA_DATA, ERR_INPUT_OPEN, inputFilepath, readConcentrations(), and readHeaderLine().
Referenced by convert().
void CartesianToPolarConverter::transformToAnnularSectors () private
Convert the concentrations to annular sectors.
Definition at line 83 of file CartesianToPolarConverter.cpp.
References annularSectors, concentrations, nrOfConcentricCircles, nrOfSectors, RADIUS_MAX, and RADIUS_MIN.
Referenced by convert().
Member Data Documentation
vector<AnnularSector> multiscale::video::CartesianToPolarConverter::annularSectors private
Resulting annular sectors
Definition at line 32 of file CartesianToPolarConverter.hpp.
Referenced by outputResultsAsFile(), outputResultsAsScript(), and transformToAnnularSectors().
vector<double> multiscale::video::CartesianToPolarConverter::concentrations private
Concentrations received as input
Definition at line 33 of file CartesianToPolarConverter.hpp.
Referenced by transformToAnnularSectors().
string multiscale::video::CartesianToPolarConverter::inputFilepath private
Path to the input file
Definition at line 39 of file CartesianToPolarConverter.hpp.
Referenced by readInputData().
unsigned long multiscale::video::CartesianToPolarConverter::nrOfConcentricCircles private
Number of concentric circles
Definition at line 35 of file CartesianToPolarConverter.hpp.
Referenced by CartesianToPolarConverter(), and transformToAnnularSectors().
unsigned long multiscale::video::CartesianToPolarConverter::nrOfSectors private
Number of sectors
Definition at line 36 of file CartesianToPolarConverter.hpp.
Referenced by CartesianToPolarConverter(), and transformToAnnularSectors().
string multiscale::video::CartesianToPolarConverter::outputFilepath private
Path to the output file
Definition at line 40 of file CartesianToPolarConverter.hpp.
Referenced by outputResultsAsFile(), and outputResultsAsScript().
double multiscale::video::CartesianToPolarConverter::simulationTime private
Simulation time corresponding to the input data
Definition at line 37 of file CartesianToPolarConverter.hpp.
Referenced by CartesianToPolarConverter(), and outputResultsAsScript().
The documentation for this class was generated from the following files:
include/multiscale/video/circular/CartesianToPolarConverter.hpp
src/multiscale/video/circular/CartesianToPolarConverter.cpp