Multiscale: multiscale::video::RectangularGnuplotScriptGenerator Class Reference
multiscale::video::RectangularGnuplotScriptGenerator Class Reference
Gnuplot script generator from the provided concentrations considering a rectangular geometry.
#include <RectangularGnuplotScriptGenerator.hpp>
Static Public Member Functions
static void generateScript (const vector< double > &concentrations, double simulationTime, unsigned long height, unsigned long width, const string &outputFilepath) throw (string)
Generate the script.
Static Private Member Functions
static void generateHeader (ofstream &fout, const string &outputFilepath, double simulationTime, unsigned long height, unsigned long width)
Generate the header of the script.
static void generateBody (const vector< double > &concentrations, unsigned long height, unsigned long width, ofstream &fout)
Generate the body/content of the script.
static void generateFooter (ofstream &fout)
Generate the footer of the script.
static void outputHeader (ifstream &fin, const string &outputFilename, double simulationTime, unsigned long height, unsigned long width, ofstream &fout)
Output the header of the script.
static void outputContent (const vector< double > &concentrations, unsigned long height, unsigned long width, ofstream &fout)
Output the content of the script.
static void outputFooter (ifstream &fin, ofstream &fout)
Output the footer of the script.
Detailed Description
Gnuplot script generator from the provided concentrations considering a rectangular geometry.
Definition at line 30 of file RectangularGnuplotScriptGenerator.hpp.
Member Function Documentation
void RectangularGnuplotScriptGenerator::generateBody (const vector< double > & concentrations, unsigned long height, unsigned long width, ofstream & fout) static private
Generate the body/content of the script.
Parameters
concentrations The concentrations
height The height of the grid
width The width of the grid
fout Output file stream
Definition at line 45 of file RectangularGnuplotScriptGenerator.cpp.
References CONTENT_IN.
void RectangularGnuplotScriptGenerator::generateFooter (ofstream & fout) static private
Generate the footer of the script.
Parameters
fout Output file stream
Definition at line 56 of file RectangularGnuplotScriptGenerator.cpp.
References FOOTER_IN.
void RectangularGnuplotScriptGenerator::generateHeader (ofstream & fout, const string & outputFilepath, double simulationTime, unsigned long height, unsigned long width) static private
Generate the header of the script.
Parameters
fout Output file stream
outputFilepath Path to the output file
simulationTime Simulation time
height Height of the grid
width Width of the grid
Definition at line 31 of file RectangularGnuplotScriptGenerator.cpp.
References multiscale::StringManipulator::filenameFromPath(), and HEADER_IN.
void RectangularGnuplotScriptGenerator::generateScript (const vector< double > & concentrations, double simulationTime, unsigned long height, unsigned long width, const string & outputFilepath) throw (string) static
Generate the script.
Parameters
concentrations Concentrations
simulationTime Simulation time
height Height of the grid
width Width of the grid
outputFilepath Path of the output file
Definition at line 14 of file RectangularGnuplotScriptGenerator.cpp.
References GNUPLOT_EXTENSION.
Referenced by multiscale::video::CartesianToConcentrationsConverter::outputResults().
void RectangularGnuplotScriptGenerator::outputContent (const vector< double > & concentrations, unsigned long height, unsigned long width, ofstream & fout) static private
Output the content of the script.
Parameters
concentrations The concentrations
height The height of the grid
width The width of the grid
fout Output file stream
Definition at line 82 of file RectangularGnuplotScriptGenerator.cpp.
References OUTPUT_SEPARATOR.
void RectangularGnuplotScriptGenerator::outputFooter (ifstream & fin, ofstream & fout) static private
Output the footer of the script.
Parameters
fin Input file stream
fout Output file stream
Definition at line 95 of file RectangularGnuplotScriptGenerator.cpp.
void RectangularGnuplotScriptGenerator::outputHeader (ifstream & fin, const string & outputFilename, double simulationTime, unsigned long height, unsigned long width, ofstream & fout) static private
Output the header of the script.
Parameters
fin Input file stream
outputFilename Name of the output file
simulationTime Simulation time
height The height of the grid
width The width of the grid
fout Output file stream
Definition at line 66 of file RectangularGnuplotScriptGenerator.cpp.
References multiscale::StringManipulator::replace(), REPLACE_DIMENSION_EXTRA, REPLACE_HEADER_FILENAME, REPLACE_HEADER_HEIGHT, REPLACE_HEADER_SIM_TIME, and REPLACE_HEADER_WIDTH.
The documentation for this class was generated from the following files:
include/multiscale/video/rectangular/RectangularGnuplotScriptGenerator.hpp
src/multiscale/video/rectangular/RectangularGnuplotScriptGenerator.cpp