Multiscale: multiscale::analysis::Cluster Class Reference
multiscale::analysis::Cluster Class Reference
Class for representing a cluster of entities in an image.
#include <Cluster.hpp>
Public Member Functions
Cluster ()
~Cluster ()
void addEntity (const Entity &entity)
Add a new entity to the cluster.
double getPileUpDegree ()
Get the degree of pile up.
vector< Point2f > getMinAreaEnclosingTriangle ()
Get the minimum area enclosing triangle.
RotatedRect getMinAreaEnclosingRect ()
Get the minimum area enclosing rectangle.
Point2f getMinAreaEnclosingCircleCentre ()
Get the minimum area enclosing circle centre.
float getMinAreaEnclosingCircleRadius ()
Get the minimum area enclosing circle radius.
vector< Entity > getEntities () const
Get the collection of underlying entities.
vector< Point2f > getEntitiesConvexHull ()
Get the convex hull enclosing the collection of entities' contour points.
void setOriginDependentMembers (double distanceFromOrigin, double angleWrtOrigin)
Set the values of the origin dependent members.
Public Member Functions inherited from multiscale::analysis::SpatialCollection2D
SpatialCollection2D ()
virtual ~SpatialCollection2D ()
double getClusterednessDegree ()
Get the clusteredness degree.
double getArea ()
Get the area.
double getPerimeter ()
Get the perimeter.
double getDistanceFromOrigin ()
Get the distance from the origin.
double getAngle ()
Get the angle.
Shape2D getShape ()
Get the shape best fitting the spatial collection.
Point2f getCentre ()
Get the point defining the centre of the entity.
string toString ()
Get the string representation of all field values.
Static Public Member Functions
static string fieldNamesToString ()
Get a string representation of all the field names printed in the "toString" method.
Static Public Attributes
static const string ERR_UNDEFINED_SHAPE = "The shape of the given cluster is undefined."
static const string ERR_ORIGIN_DEPENDENT_VALUES = "The origin dependent values are invalid (i.e. negative)."
Private Member Functions
void initialise ()
Initialisation function for the class.
vector< Point2f > getEntitiesCentrePoints ()
Get the collection of entities' centres.
vector< Point2f > getEntitiesContourPoints ()
Get the collection of entities' contour points.
void updateSpatialCollectionSpecificValues () override
Update the values of all measures.
void updateClusterednessDegree () override
Update the value of the clusteredness degree.
void updatePileUpDegree ()
Update the value of the pile up degree.
void updateArea () override
Update the value of the area.
void updatePerimeter () override
Update the value of the perimeter.
void updateCentrePoint () override
Update the point defining the centre of the cluster.
double isTriangularMeasure () override
Get the measure that the cluster has a triangular shape.
double isRectangularMeasure () override
Get the measure that the cluster has a rectangular shape.
double isCircularMeasure () override
Get the measure that the cluster has a circular shape.
string fieldValuesToString () override
Get a string representation of all the field values.
void validateOriginDependentValues (double distanceFromOrigin, double angleWrtOrigin)
Validate the origin dependent values (i.e. non-negative)
bool areValidOriginDependentValues (double distanceFromOrigin, double angleWrtOrigin)
Check if the origin dependent values are valid (i.e. non-negative)
Private Attributes
double pileUpDegree
vector< Point2f > minAreaEnclosingTriangle
RotatedRect minAreaEnclosingRect
Point2f minAreaEnclosingCircleCentre
float minAreaEnclosingCircleRadius
vector< Entity > entities
Additional Inherited Members
Protected Member Functions inherited from multiscale::analysis::SpatialCollection2D
void updateMeasuresIfRequired ()
Update the values of all measures if required.
void updateMeasures ()
Update the values of all measures.
void updateShape ()
Update the shape of the cluster.
string shapeAsString ()
Return the shape of the cluster as a string.
vector< Point2f > convertPoints (const vector< Point > &points)
Convert the collection of points from type Point to type Point2f.
Protected Attributes inherited from multiscale::analysis::SpatialCollection2D
double clusterednessDegree
double area
double perimeter
double distanceFromOrigin
double angle
double triangularMeasure
double rectangularMeasure
double circularMeasure
Shape2D shape
Point2f centre
bool updateFlag
Static Protected Attributes inherited from multiscale::analysis::SpatialCollection2D
static const string STR_TRIANGLE = "triangle"
static const string STR_RECTANGLE = "rectangle"
static const string STR_CIRCLE = "circle"
static const string STR_UNDEFINED = "undefined"
static const string OUTPUT_SEPARATOR = ","
static const string ERR_INPUT = "Invalid input parameters were provided to the constructor."
static const bool CONVEX_HULL_CLOCKWISE = true
Detailed Description
Class for representing a cluster of entities in an image.
Definition at line 21 of file Cluster.hpp.
Constructor & Destructor Documentation
Cluster::Cluster ()
Definition at line 11 of file Cluster.cpp.
References initialise().
Cluster::~Cluster ()
Definition at line 15 of file Cluster.cpp.
Member Function Documentation
void Cluster::addEntity (const Entity & entity)
Add a new entity to the cluster.
Definition at line 17 of file Cluster.cpp.
References entities, and multiscale::analysis::SpatialCollection2D::updateFlag.
bool Cluster::areValidOriginDependentValues (double distanceFromOrigin, double angleWrtOrigin) private
Check if the origin dependent values are valid (i.e. non-negative)
Parameters
distanceFromOrigin Distance from the origin
angleWrtOrigin Angle with respect to the origin
Definition at line 233 of file Cluster.cpp.
Referenced by validateOriginDependentValues().
string Cluster::fieldNamesToString () static
Get a string representation of all the field names printed in the "toString" method.
Definition at line 75 of file Cluster.cpp.
Referenced by multiscale::analysis::ClusterDetector::outputResultsToCsvFile().
string Cluster::fieldValuesToString () override private virtual
Get a string representation of all the field values.
Implements multiscale::analysis::SpatialCollection2D.
Definition at line 208 of file Cluster.cpp.
References multiscale::analysis::SpatialCollection2D::angle, multiscale::analysis::SpatialCollection2D::area, multiscale::analysis::SpatialCollection2D::centre, multiscale::analysis::SpatialCollection2D::circularMeasure, multiscale::analysis::SpatialCollection2D::clusterednessDegree, multiscale::analysis::SpatialCollection2D::distanceFromOrigin, multiscale::analysis::SpatialCollection2D::OUTPUT_SEPARATOR, multiscale::analysis::SpatialCollection2D::perimeter, pileUpDegree, multiscale::analysis::SpatialCollection2D::rectangularMeasure, multiscale::analysis::SpatialCollection2D::shapeAsString(), and multiscale::analysis::SpatialCollection2D::triangularMeasure.
vector< Entity > Cluster::getEntities () const
Get the collection of underlying entities.
Definition at line 53 of file Cluster.cpp.
References entities.
Referenced by multiscale::analysis::SimulationClusterDetector::outputClusterToImage().
vector< Point2f > Cluster::getEntitiesCentrePoints () private
Get the collection of entities' centres.
Definition at line 94 of file Cluster.cpp.
References entities.
vector< Point2f > Cluster::getEntitiesContourPoints () private
Get the collection of entities' contour points.
Definition at line 104 of file Cluster.cpp.
References entities.
Referenced by getEntitiesConvexHull(), isCircularMeasure(), and isRectangularMeasure().
vector< Point2f > Cluster::getEntitiesConvexHull ()
Get the convex hull enclosing the collection of entities' contour points.
Definition at line 57 of file Cluster.cpp.
References multiscale::analysis::SpatialCollection2D::CONVEX_HULL_CLOCKWISE, entities, and getEntitiesContourPoints().
Referenced by multiscale::analysis::ClusterDetector::getClusterConvexHull(), isTriangularMeasure(), and updatePerimeter().
Point2f Cluster::getMinAreaEnclosingCircleCentre ()
Get the minimum area enclosing circle centre.
Definition at line 41 of file Cluster.cpp.
References minAreaEnclosingCircleCentre, and multiscale::analysis::SpatialCollection2D::updateMeasuresIfRequired().
Referenced by multiscale::analysis::SimulationClusterDetector::outputClusterCircularShape().
float Cluster::getMinAreaEnclosingCircleRadius ()
Get the minimum area enclosing circle radius.
Definition at line 47 of file Cluster.cpp.
References minAreaEnclosingCircleRadius, and multiscale::analysis::SpatialCollection2D::updateMeasuresIfRequired().
Referenced by multiscale::analysis::SimulationClusterDetector::outputClusterCircularShape().
RotatedRect Cluster::getMinAreaEnclosingRect ()
Get the minimum area enclosing rectangle.
Definition at line 35 of file Cluster.cpp.
References minAreaEnclosingRect, and multiscale::analysis::SpatialCollection2D::updateMeasuresIfRequired().
Referenced by multiscale::analysis::SimulationClusterDetector::outputClusterRectangularShape().
vector< Point2f > Cluster::getMinAreaEnclosingTriangle ()
Get the minimum area enclosing triangle.
Definition at line 29 of file Cluster.cpp.
References minAreaEnclosingTriangle, and multiscale::analysis::SpatialCollection2D::updateMeasuresIfRequired().
Referenced by multiscale::analysis::SimulationClusterDetector::outputClusterTriangularShape().
double Cluster::getPileUpDegree ()
Get the degree of pile up.
Definition at line 23 of file Cluster.cpp.
References pileUpDegree, and multiscale::analysis::SpatialCollection2D::updateMeasuresIfRequired().
void Cluster::initialise () private
Initialisation function for the class.
Definition at line 79 of file Cluster.cpp.
References multiscale::analysis::SpatialCollection2D::angle, multiscale::analysis::SpatialCollection2D::clusterednessDegree, multiscale::analysis::SpatialCollection2D::distanceFromOrigin, entities, minAreaEnclosingCircleRadius, minAreaEnclosingTriangle, pileUpDegree, and multiscale::analysis::SpatialCollection2D::updateFlag.
Referenced by Cluster().
double Cluster::isCircularMeasure () override private virtual
Get the measure that the cluster has a circular shape.
Implements multiscale::analysis::SpatialCollection2D.
Definition at line 196 of file Cluster.cpp.
References multiscale::Numeric::almostEqual(), multiscale::analysis::SpatialCollection2D::area, getEntitiesContourPoints(), minAreaEnclosingCircleCentre, minAreaEnclosingCircleRadius, and multiscale::Geometry2D::PI.
double Cluster::isRectangularMeasure () override private virtual
Get the measure that the cluster has a rectangular shape.
Implements multiscale::analysis::SpatialCollection2D.
Definition at line 184 of file Cluster.cpp.
References multiscale::Numeric::almostEqual(), multiscale::analysis::SpatialCollection2D::area, getEntitiesContourPoints(), and minAreaEnclosingRect.
double Cluster::isTriangularMeasure () override private virtual
Get the measure that the cluster has a triangular shape.
Implements multiscale::analysis::SpatialCollection2D.
Definition at line 175 of file Cluster.cpp.
References multiscale::Numeric::almostEqual(), multiscale::analysis::SpatialCollection2D::area, multiscale::MinEnclosingTriangleFinder::find(), getEntitiesConvexHull(), and minAreaEnclosingTriangle.
void Cluster::setOriginDependentMembers (double distanceFromOrigin, double angleWrtOrigin)
Set the values of the origin dependent members.
Parameters
distanceFromOrigin Distance from the origin
angleWrtOrigin Angle with respect to the origin
Definition at line 68 of file Cluster.cpp.
References multiscale::analysis::SpatialCollection2D::angle, multiscale::analysis::SpatialCollection2D::distanceFromOrigin, and validateOriginDependentValues().
Referenced by multiscale::analysis::ClusterDetector::updateClusterOriginDependentValues().
void Cluster::updateArea () override private virtual
Update the value of the area.
Implements multiscale::analysis::SpatialCollection2D.
Definition at line 150 of file Cluster.cpp.
References multiscale::analysis::SpatialCollection2D::area, and entities.
void Cluster::updateCentrePoint () override private virtual
Update the point defining the centre of the cluster.
Implements multiscale::analysis::SpatialCollection2D.
Definition at line 164 of file Cluster.cpp.
References multiscale::analysis::SpatialCollection2D::centre, and entities.
void Cluster::updateClusterednessDegree () override private virtual
Update the value of the clusteredness degree.
Implements multiscale::analysis::SpatialCollection2D.
Definition at line 120 of file Cluster.cpp.
References multiscale::analysis::SpatialCollection2D::clusterednessDegree, and entities.
void Cluster::updatePerimeter () override private virtual
Update the value of the perimeter.
Implements multiscale::analysis::SpatialCollection2D.
Definition at line 158 of file Cluster.cpp.
References getEntitiesConvexHull(), and multiscale::analysis::SpatialCollection2D::perimeter.
void Cluster::updatePileUpDegree () private
Update the value of the pile up degree.
Definition at line 140 of file Cluster.cpp.
References entities, and pileUpDegree.
Referenced by updateSpatialCollectionSpecificValues().
void Cluster::updateSpatialCollectionSpecificValues () override private virtual
Update the values of all measures.
Implements multiscale::analysis::SpatialCollection2D.
Definition at line 116 of file Cluster.cpp.
References updatePileUpDegree().
void Cluster::validateOriginDependentValues (double distanceFromOrigin, double angleWrtOrigin) private
Validate the origin dependent values (i.e. non-negative)
Parameters
distanceFromOrigin Distance from the origin
angleWrtOrigin Angle with respect to the origin
Definition at line 227 of file Cluster.cpp.
References areValidOriginDependentValues(), ERR_ORIGIN_DEPENDENT_VALUES, and MS_throw.
Referenced by setOriginDependentMembers().
Member Data Documentation
vector<Entity> multiscale::analysis::Cluster::entities private
Entities which belong to this cluster
Definition at line 34 of file Cluster.hpp.
Referenced by addEntity(), getEntities(), getEntitiesCentrePoints(), getEntitiesContourPoints(), getEntitiesConvexHull(), initialise(), updateArea(), updateCentrePoint(), updateClusterednessDegree(), and updatePileUpDegree().
const string Cluster::ERR_ORIGIN_DEPENDENT_VALUES = "The origin dependent values are invalid (i.e. negative)." static
Definition at line 135 of file Cluster.hpp.
Referenced by validateOriginDependentValues().
const string Cluster::ERR_UNDEFINED_SHAPE = "The shape of the given cluster is undefined." static
Definition at line 134 of file Cluster.hpp.
Referenced by multiscale::analysis::SimulationClusterDetector::outputClusterShape().
Point2f multiscale::analysis::Cluster::minAreaEnclosingCircleCentre private
The minimum area enclosing circle centre point
Definition at line 31 of file Cluster.hpp.
Referenced by getMinAreaEnclosingCircleCentre(), and isCircularMeasure().
float multiscale::analysis::Cluster::minAreaEnclosingCircleRadius private
The minimum area enclosing circle radius
Definition at line 32 of file Cluster.hpp.
Referenced by getMinAreaEnclosingCircleRadius(), initialise(), and isCircularMeasure().
RotatedRect multiscale::analysis::Cluster::minAreaEnclosingRect private
The minimum area enclosing rectangle
Definition at line 29 of file Cluster.hpp.
Referenced by getMinAreaEnclosingRect(), and isRectangularMeasure().
vector<Point2f> multiscale::analysis::Cluster::minAreaEnclosingTriangle private
The minimum area enclosing triangle
Definition at line 27 of file Cluster.hpp.
Referenced by getMinAreaEnclosingTriangle(), initialise(), and isTriangularMeasure().
double multiscale::analysis::Cluster::pileUpDegree private
Degree of pile up
Definition at line 25 of file Cluster.hpp.
Referenced by fieldValuesToString(), getPileUpDegree(), initialise(), and updatePileUpDegree().
The documentation for this class was generated from the following files:
modules/analysis/spatial/include/multiscale/analysis/spatial/Cluster.hpp
modules/analysis/spatial/src/Cluster.cpp