Multiscale: multiscale::video::RectangularCsvToInputFilesConverter Class Reference
multiscale::video::RectangularCsvToInputFilesConverter Class Reference
Csv file to input file converter considering cartesian coordinates.
#include <RectangularCsvToInputFilesConverter.hpp>
Public Member Functions
RectangularCsvToInputFilesConverter (const string &inputFilepath, const string &outputFilepath, unsigned int height, unsigned int width, unsigned int nrOfConcentrationsForPosition, unsigned int selectedConcentrationIndex, bool useLogScaling, NumberIteratorType numberIteratorType)
~RectangularCsvToInputFilesConverter ()
void convert ()
Start the conversion.
Private Member Functions
void initInputFile (ifstream &fin)
Initialise the input file stream over the given input file.
void initMaximumConcentration (ifstream &fin)
Compute the value of member maximum concentration.
void initOutputFile (ofstream &fout, unsigned int index, double &simulationTime)
Initialise the output file with the given index and simulation time.
void initIterators (const NumberIteratorType &numberIteratorType)
Initialise the iterators considering the given number iterator type.
void validateSelectedConcentrationIndex ()
Validate the selected concentration index in case of more than one concentration for each position.
void validateInput (ifstream &fin)
Validate the input.
void validateInputLine (const string &line, unsigned int lineNumber)
Validate the provided line identified by a line number.
void processInputFile (ifstream &fin)
Process the input file.
void processLine (const string &line, unsigned int outputIndex)
Process the provided line.
vector< double > splitLineInConcentrations (const string &line, double &simulationTime)
Split the line in concentrations.
void splitLineInConcentrations (vector< double > &concentrations, vector< string > &tokens, unsigned int rowIndex)
Split line into concentrations.
double computeSimulationTime (const string &token)
Compute the simulation time from the given token and check if it is valid.
double computeNextPositionConcentration (int concentrationIndex, vector< string > &tokens)
Compute the concentration for the next position.
double computeConcentration (const string &concentration)
Compute the concentration from the given string.
double computeNonScaledConcentration (const string &concentration)
Compute the non-scaled concentration from the given string.
double computeScaledConcentration (const string &concentration)
Compute the scaled concentration from the given string.
double computeNormalisedConcentration (double concentration)
Normalise the given concentration by dividing it to the maximum concentration.
void updateMaximumConcentration (const string &line, double &maximumConcentration)
Update the maximum concentration if the values from the given line are greater than it.
Private Attributes
string inputFilepath
string outputFilepath
unsigned int height
unsigned int width
unsigned int nrOfConcentrationsForPosition
unsigned int concentrationsIndex
unsigned int selectedConcentrationIndex
bool useLogScaling
double maximumConcentration
NumberIterator * rowsIterator
NumberIterator * columnsIterator
Detailed Description
Csv file to input file converter considering cartesian coordinates.
Definition at line 31 of file RectangularCsvToInputFilesConverter.hpp.
Constructor & Destructor Documentation
RectangularCsvToInputFilesConverter::RectangularCsvToInputFilesConverter (const string & inputFilepath, const string & outputFilepath, unsigned int height, unsigned int width, unsigned int nrOfConcentrationsForPosition, unsigned int selectedConcentrationIndex, bool useLogScaling, NumberIteratorType numberIteratorType)
Definition at line 19 of file RectangularCsvToInputFilesConverter.cpp.
RectangularCsvToInputFilesConverter::~RectangularCsvToInputFilesConverter ()
Definition at line 43 of file RectangularCsvToInputFilesConverter.cpp.
Member Function Documentation
double RectangularCsvToInputFilesConverter::computeConcentration (const string & concentration) inline private
Compute the concentration from the given string.
Parameters
concentration String representing the concentration
Definition at line 282 of file RectangularCsvToInputFilesConverter.cpp.
double RectangularCsvToInputFilesConverter::computeNextPositionConcentration (int concentrationIndex, vector< string > & tokens) inline private
Compute the concentration for the next position.
Parameters
concentrationIndex Index of the current concentration from the vector of tokens
tokens Vector of tokens
Definition at line 255 of file RectangularCsvToInputFilesConverter.cpp.
double RectangularCsvToInputFilesConverter::computeNonScaledConcentration (const string & concentration) inline private
Compute the non-scaled concentration from the given string.
Parameters
concentration String representing the concentration
Definition at line 288 of file RectangularCsvToInputFilesConverter.cpp.
double RectangularCsvToInputFilesConverter::computeNormalisedConcentration (double concentration) inline private
Normalise the given concentration by dividing it to the maximum concentration.
Parameters
concentration The concentration
Definition at line 304 of file RectangularCsvToInputFilesConverter.cpp.
double RectangularCsvToInputFilesConverter::computeScaledConcentration (const string & concentration) inline private
Compute the scaled concentration from the given string.
Compute the scaled concentration from the given string by applying a logit transformation to it
Parameters
concentration String representing the concentration
Definition at line 292 of file RectangularCsvToInputFilesConverter.cpp.
double RectangularCsvToInputFilesConverter::computeSimulationTime (const string & token) inline private
Compute the simulation time from the given token and check if it is valid.
Parameters
token Token (string)
Definition at line 245 of file RectangularCsvToInputFilesConverter.cpp.
References ERR_NEG_SIM_TIME.
void RectangularCsvToInputFilesConverter::convert ()
Start the conversion.
Definition at line 48 of file RectangularCsvToInputFilesConverter.cpp.
Referenced by main().
void RectangularCsvToInputFilesConverter::initInputFile (ifstream & fin) private
Initialise the input file stream over the given input file.
Parameters
fin Input file stream
Definition at line 61 of file RectangularCsvToInputFilesConverter.cpp.
References ERR_INPUT_OPEN.
void RectangularCsvToInputFilesConverter::initIterators (const NumberIteratorType & numberIteratorType) private
Initialise the iterators considering the given number iterator type.
Parameters
numberIteratorType The type of the number iterator
Definition at line 110 of file RectangularCsvToInputFilesConverter.cpp.
References multiscale::LEXICOGRAPHIC, and multiscale::STANDARD.
void RectangularCsvToInputFilesConverter::initMaximumConcentration (ifstream & fin) private
Compute the value of member maximum concentration.
Parameters
fin Input file stream
Definition at line 69 of file RectangularCsvToInputFilesConverter.cpp.
References ERR_INPUT_OPEN.
void RectangularCsvToInputFilesConverter::initOutputFile (ofstream & fout, unsigned int index, double & simulationTime) private
Initialise the output file with the given index and simulation time.
Parameters
fout Output file stream
index Index of the output file
simulationTime Simulation time
Definition at line 93 of file RectangularCsvToInputFilesConverter.cpp.
References OUTPUT_EXTENSION, OUTPUT_FILE_SEPARATOR, OUTPUT_SEPARATOR, and multiscale::StringManipulator::toString().
void RectangularCsvToInputFilesConverter::processInputFile (ifstream & fin) private
Process the input file.
Read the concentrations and normalise them if it is the case.
Parameters
fin Input file stream
Definition at line 177 of file RectangularCsvToInputFilesConverter.cpp.
void RectangularCsvToInputFilesConverter::processLine (const string & line, unsigned int outputIndex) private
Process the provided line.
Parameters
line Line
outputIndex Index integrated in the name of the output file
Definition at line 192 of file RectangularCsvToInputFilesConverter.cpp.
References OUTPUT_SEPARATOR.
vector< double > RectangularCsvToInputFilesConverter::splitLineInConcentrations (const string & line, double & simulationTime) private
Split the line in concentrations.
Parameters
line Line
simulationTime Simulation time associated with the line
Definition at line 209 of file RectangularCsvToInputFilesConverter.cpp.
References INPUT_FILE_SEPARATOR, and multiscale::StringManipulator::split().
void RectangularCsvToInputFilesConverter::splitLineInConcentrations (vector< double > & concentrations, vector< string > & tokens, unsigned int rowIndex) private
Split line into concentrations.
Parameters
concentrations Concentrations extracted from tokens
tokens Tokens representing the line
rowIndex Index of the current row
Definition at line 230 of file RectangularCsvToInputFilesConverter.cpp.
void RectangularCsvToInputFilesConverter::updateMaximumConcentration (const string & line, double & maximumConcentration) private
Update the maximum concentration if the values from the given line are greater than it.
Parameters
line Line from input file
maximumConcentration The maximum concentration
Definition at line 308 of file RectangularCsvToInputFilesConverter.cpp.
void RectangularCsvToInputFilesConverter::validateInput (ifstream & fin) private
Validate the input.
Parameters
fin Input file stream
Definition at line 133 of file RectangularCsvToInputFilesConverter.cpp.
References ERR_INPUT_OPEN.
void RectangularCsvToInputFilesConverter::validateInputLine (const string & line, unsigned int lineNumber) private
Validate the provided line identified by a line number.
Parameters
line Line from input file
lineNumber Number of the line
Definition at line 157 of file RectangularCsvToInputFilesConverter.cpp.
References ERR_INVALID_VALUE_LINE, ERR_INVALID_VALUE_TOKEN, ERR_NR_CONCENTRATIONS, INPUT_FILE_SEPARATOR, and multiscale::StringManipulator::split().
void RectangularCsvToInputFilesConverter::validateSelectedConcentrationIndex () private
Validate the selected concentration index in case of more than one concentration for each position.
Definition at line 127 of file RectangularCsvToInputFilesConverter.cpp.
References ERR_SELECTED_CONCENTRATION_INDEX.
Member Data Documentation
NumberIterator* multiscale::video::RectangularCsvToInputFilesConverter::columnsIterator private
Iterator over the number of columns
Definition at line 56 of file RectangularCsvToInputFilesConverter.hpp.
unsigned int multiscale::video::RectangularCsvToInputFilesConverter::concentrationsIndex private
Index of the current concentration
Definition at line 42 of file RectangularCsvToInputFilesConverter.hpp.
unsigned int multiscale::video::RectangularCsvToInputFilesConverter::height private
Height of the grid
Definition at line 38 of file RectangularCsvToInputFilesConverter.hpp.
string multiscale::video::RectangularCsvToInputFilesConverter::inputFilepath private
Path to the input file
Definition at line 35 of file RectangularCsvToInputFilesConverter.hpp.
double multiscale::video::RectangularCsvToInputFilesConverter::maximumConcentration private
The maximum concentration in the input file
Definition at line 53 of file RectangularCsvToInputFilesConverter.hpp.
unsigned int multiscale::video::RectangularCsvToInputFilesConverter::nrOfConcentrationsForPosition private
Number of concentrations for each position
Definition at line 40 of file RectangularCsvToInputFilesConverter.hpp.
string multiscale::video::RectangularCsvToInputFilesConverter::outputFilepath private
Path to the output file
Definition at line 36 of file RectangularCsvToInputFilesConverter.hpp.
NumberIterator* multiscale::video::RectangularCsvToInputFilesConverter::rowsIterator private
Iterator over the number of rows
Definition at line 55 of file RectangularCsvToInputFilesConverter.hpp.
unsigned int multiscale::video::RectangularCsvToInputFilesConverter::selectedConcentrationIndex private
    Index of the concentration A in case the number of
concentrations for each position is greater than 1
finalConcentration = A / (A1 + A2 + ... + AN), where N is the number of concentrations for each position
Definition at line 44 of file RectangularCsvToInputFilesConverter.hpp.
bool multiscale::video::RectangularCsvToInputFilesConverter::useLogScaling private
Flag for using logarithmic scaling for concentrations or not
Definition at line 51 of file RectangularCsvToInputFilesConverter.hpp.
unsigned int multiscale::video::RectangularCsvToInputFilesConverter::width private
Width of the grid
Definition at line 39 of file RectangularCsvToInputFilesConverter.hpp.
The documentation for this class was generated from the following files:
include/multiscale/video/rectangular/RectangularCsvToInputFilesConverter.hpp
src/multiscale/video/rectangular/RectangularCsvToInputFilesConverter.cpp