Multiscale: multiscale::video::RectangularEntityCsvToInputFilesConverter Class Reference
multiscale::video::RectangularEntityCsvToInputFilesConverter Class Reference
Csv entity file to input file converter considering cartesian coordinates.
#include <RectangularEntityCsvToInputFilesConverter.hpp>
Public Member Functions
RectangularEntityCsvToInputFilesConverter (const string &inputFilepath, const string &outputFilepath, unsigned int height, unsigned int width, unsigned int nrOfEntities, unsigned int maxNrOfEntitiesPerPosition, NumberIteratorType numberIteratorType)
~RectangularEntityCsvToInputFilesConverter ()
void convert ()
Start the conversion.
Private Member Functions
void initInputFile (ifstream &fin)
Initialise the input file stream over the given input file.
void initOutputFile (ofstream &fout, unsigned int index, double &simulationTime)
Initialise the output file with the given index and simulation time.
void initIterators (const NumberIteratorType &numberIteratorType)
Initialise the iterators considering the given number iterator type.
void validateMaxNrOfEntitiesPerPosition ()
Check if the maximum number of entities per position is a non-zero natural number.
void validateInput (ifstream &fin)
Validate the input.
void validateInputLine (const string &line, unsigned int lineNumber)
Validate the provided line identified by a line number.
void processInputFile (ifstream &fin)
Process the input file.
void processLine (const string &line, unsigned int outputIndex)
Process the provided line.
vector< double > splitLineInCoordinates (const string &line, double &simulationTime)
Split the line in coordinates and return the grid of size height * width showing the position of the entities.
double computeSimulationTime (const string &token)
Compute the simulation time from the given token and check if it is valid.
unsigned int computeCoordinate (const string &token, bool isOxCoordinate)
Compute the coordinate from the given string and check if it is valid.
void validateSimulationTime (const string &token, unsigned int lineNumber)
Check if the simulation time is valid.
void validateCoordinate (const string &token, unsigned int lineNumber, bool isOxCoordinate)
Check if the coordinate is valid.
void validateEntitiesGrid (const vector< double > &entitiesGrid)
Check if the entities grid contains only values between zero and one.
Private Attributes
string inputFilepath
string outputFilepath
unsigned int height
unsigned int width
unsigned int nrOfEntities
unsigned int maxNrOfEntitiesPerPosition
NumberIterator * entitiesIterator
Detailed Description
Csv entity file to input file converter considering cartesian coordinates.
Definition at line 33 of file RectangularEntityCsvToInputFilesConverter.hpp.
Constructor & Destructor Documentation
RectangularEntityCsvToInputFilesConverter::RectangularEntityCsvToInputFilesConverter (const string & inputFilepath, const string & outputFilepath, unsigned int height, unsigned int width, unsigned int nrOfEntities, unsigned int maxNrOfEntitiesPerPosition, NumberIteratorType numberIteratorType)
Definition at line 18 of file RectangularEntityCsvToInputFilesConverter.cpp.
RectangularEntityCsvToInputFilesConverter::~RectangularEntityCsvToInputFilesConverter ()
Definition at line 37 of file RectangularEntityCsvToInputFilesConverter.cpp.
Member Function Documentation
unsigned int RectangularEntityCsvToInputFilesConverter::computeCoordinate (const string & token, bool isOxCoordinate) inline private
Compute the coordinate from the given string and check if it is valid.
Parameters
token Token (string)
isOxCoordinate Flag which indicates if the coordinate corresponds to Ox axis or not
Definition at line 200 of file RectangularEntityCsvToInputFilesConverter.cpp.
References ERR_INVALID_OX_COORDINATE, and ERR_INVALID_OY_COORDINATE.
double RectangularEntityCsvToInputFilesConverter::computeSimulationTime (const string & token) inline private
Compute the simulation time from the given token and check if it is valid.
Parameters
token Token (string)
Definition at line 192 of file RectangularEntityCsvToInputFilesConverter.cpp.
References ERR_NEG_SIM_TIME.
void RectangularEntityCsvToInputFilesConverter::convert ()
Start the conversion.
Definition at line 41 of file RectangularEntityCsvToInputFilesConverter.cpp.
Referenced by main().
void RectangularEntityCsvToInputFilesConverter::initInputFile (ifstream & fin) private
Initialise the input file stream over the given input file.
Parameters
fin Input file stream
Definition at line 53 of file RectangularEntityCsvToInputFilesConverter.cpp.
References ERR_INPUT_OPEN.
void RectangularEntityCsvToInputFilesConverter::initIterators (const NumberIteratorType & numberIteratorType) private
Initialise the iterators considering the given number iterator type.
Parameters
numberIteratorType The type of the number iterator
Definition at line 77 of file RectangularEntityCsvToInputFilesConverter.cpp.
References multiscale::LEXICOGRAPHIC, and multiscale::STANDARD.
void RectangularEntityCsvToInputFilesConverter::initOutputFile (ofstream & fout, unsigned int index, double & simulationTime) private
Initialise the output file with the given index and simulation time.
Parameters
fout Output file stream
index Index of the output file
simulationTime Simulation time
Definition at line 60 of file RectangularEntityCsvToInputFilesConverter.cpp.
References OUTPUT_EXTENSION, OUTPUT_FILE_SEPARATOR, OUTPUT_SEPARATOR, and multiscale::StringManipulator::toString().
void RectangularEntityCsvToInputFilesConverter::processInputFile (ifstream & fin) private
Process the input file.
Read the concentrations and normalise them if it is the case.
Parameters
fin Input file stream
Definition at line 136 of file RectangularEntityCsvToInputFilesConverter.cpp.
void RectangularEntityCsvToInputFilesConverter::processLine (const string & line, unsigned int outputIndex) private
Process the provided line.
Parameters
line Line
outputIndex Index integrated in the name of the output file
Definition at line 151 of file RectangularEntityCsvToInputFilesConverter.cpp.
References OUTPUT_SEPARATOR.
vector< double > RectangularEntityCsvToInputFilesConverter::splitLineInCoordinates (const string & line, double & simulationTime) private
Split the line in coordinates and return the grid of size height * width showing the position of the entities.
The number of entities per grid position is normalised to the range [0, 1]
Parameters
line Line
simulationTime Simulation time associated with the line
Definition at line 170 of file RectangularEntityCsvToInputFilesConverter.cpp.
References INPUT_FILE_SEPARATOR, and multiscale::StringManipulator::split().
void RectangularEntityCsvToInputFilesConverter::validateCoordinate (const string & token, unsigned int lineNumber, bool isOxCoordinate) inline private
Check if the coordinate is valid.
Parameters
token Token (string)
lineNumber Number of the line
isOxCoordinate Flag which indicates if the coordinate corresponds to Ox axis or not
Definition at line 222 of file RectangularEntityCsvToInputFilesConverter.cpp.
References ERR_INVALID_VALUE_LINE, and ERR_INVALID_VALUE_TOKEN.
void RectangularEntityCsvToInputFilesConverter::validateEntitiesGrid (const vector< double > & entitiesGrid) inline private
Check if the entities grid contains only values between zero and one.
Parameters
entitiesGrid The grid of entities
Definition at line 233 of file RectangularEntityCsvToInputFilesConverter.cpp.
References ERR_INVALID_NR_ENTITIES.
void RectangularEntityCsvToInputFilesConverter::validateInput (ifstream & fin) private
Validate the input.
Parameters
fin Input file stream
Definition at line 98 of file RectangularEntityCsvToInputFilesConverter.cpp.
References ERR_INPUT_OPEN.
void RectangularEntityCsvToInputFilesConverter::validateInputLine (const string & line, unsigned int lineNumber) private
Validate the provided line identified by a line number.
Parameters
line Line from input file
lineNumber Number of the line
Definition at line 120 of file RectangularEntityCsvToInputFilesConverter.cpp.
References ERR_NR_COORDINATES, INPUT_FILE_SEPARATOR, and multiscale::StringManipulator::split().
void RectangularEntityCsvToInputFilesConverter::validateMaxNrOfEntitiesPerPosition () private
Check if the maximum number of entities per position is a non-zero natural number.
Definition at line 93 of file RectangularEntityCsvToInputFilesConverter.cpp.
References ERR_MAX_NR_ENTITIES.
void RectangularEntityCsvToInputFilesConverter::validateSimulationTime (const string & token, unsigned int lineNumber) inline private
Check if the simulation time is valid.
Parameters
token Token (string)
lineNumber Number of the line
Definition at line 212 of file RectangularEntityCsvToInputFilesConverter.cpp.
References ERR_INVALID_VALUE_LINE, and ERR_INVALID_VALUE_TOKEN.
Member Data Documentation
NumberIterator* multiscale::video::RectangularEntityCsvToInputFilesConverter::entitiesIterator private
Iterator over the number of rows
Definition at line 46 of file RectangularEntityCsvToInputFilesConverter.hpp.
unsigned int multiscale::video::RectangularEntityCsvToInputFilesConverter::height private
Height of the grid
Definition at line 40 of file RectangularEntityCsvToInputFilesConverter.hpp.
string multiscale::video::RectangularEntityCsvToInputFilesConverter::inputFilepath private
Path to the input file
Definition at line 37 of file RectangularEntityCsvToInputFilesConverter.hpp.
unsigned int multiscale::video::RectangularEntityCsvToInputFilesConverter::maxNrOfEntitiesPerPosition private
The maximum number of entities per position
Definition at line 44 of file RectangularEntityCsvToInputFilesConverter.hpp.
unsigned int multiscale::video::RectangularEntityCsvToInputFilesConverter::nrOfEntities private
Number of entities
Definition at line 42 of file RectangularEntityCsvToInputFilesConverter.hpp.
string multiscale::video::RectangularEntityCsvToInputFilesConverter::outputFilepath private
Path to the output file
Definition at line 38 of file RectangularEntityCsvToInputFilesConverter.hpp.
unsigned int multiscale::video::RectangularEntityCsvToInputFilesConverter::width private
Width of the grid
Definition at line 41 of file RectangularEntityCsvToInputFilesConverter.hpp.
The documentation for this class was generated from the following files:
include/multiscale/video/rectangular/RectangularEntityCsvToInputFilesConverter.hpp
src/multiscale/video/rectangular/RectangularEntityCsvToInputFilesConverter.cpp