Multiscale: multiscale::video::CartesianToConcentrationsConverter Class Reference
multiscale::video::CartesianToConcentrationsConverter Class Reference
Scale the values of the rectangular geometry grid cells.
#include <CartesianToConcentrationsConverter.hpp>
Public Member Functions
CartesianToConcentrationsConverter (const string &inputFilepath, const string &outputFilepath)
~CartesianToConcentrationsConverter ()
void convert ()
Start the conversion.
Private Member Functions
void readInputData ()
Read the input data.
void readHeaderLine (ifstream &fin)
Read the header line.
void readConcentrations (ifstream &fin)
Read the concentrations.
void outputResults ()
Output the results.
Private Attributes
vector< double > concentrations
unsigned long height
unsigned long width
double simulationTime
string inputFilepath
string outputFilepath
Detailed Description
Scale the values of the rectangular geometry grid cells.
Definition at line 26 of file CartesianToConcentrationsConverter.hpp.
Constructor & Destructor Documentation
CartesianToConcentrationsConverter::CartesianToConcentrationsConverter (const string & inputFilepath, const string & outputFilepath)
Definition at line 15 of file CartesianToConcentrationsConverter.cpp.
References height, simulationTime, and width.
CartesianToConcentrationsConverter::~CartesianToConcentrationsConverter ()
Definition at line 24 of file CartesianToConcentrationsConverter.cpp.
Member Function Documentation
void CartesianToConcentrationsConverter::convert ()
Start the conversion.
Definition at line 26 of file CartesianToConcentrationsConverter.cpp.
References outputResults(), and readInputData().
Referenced by main().
void CartesianToConcentrationsConverter::outputResults () private
Output the results.
Definition at line 84 of file CartesianToConcentrationsConverter.cpp.
References concentrations, multiscale::video::RectangularGnuplotScriptGenerator::generateScript(), height, outputFilepath, simulationTime, and width.
Referenced by convert().
void CartesianToConcentrationsConverter::readConcentrations (ifstream & fin) private
Read the concentrations.
Parameters
fin Input file stream
Definition at line 64 of file CartesianToConcentrationsConverter.cpp.
References concentrations, ERR_CONC, height, and width.
Referenced by readInputData().
void CartesianToConcentrationsConverter::readHeaderLine (ifstream & fin) private
Read the header line.
The header line contains values for number of concentric circles, number of sectors and simulation time
Parameters
fin Input file stream
Definition at line 55 of file CartesianToConcentrationsConverter.cpp.
References ERR_NEG_SIM_TIME, ERR_NONPOS_DIMENSION, height, simulationTime, and width.
Referenced by readInputData().
void CartesianToConcentrationsConverter::readInputData () private
Read the input data.
Definition at line 31 of file CartesianToConcentrationsConverter.cpp.
References ERR_IN_EXTRA_DATA, ERR_INPUT_OPEN, inputFilepath, readConcentrations(), and readHeaderLine().
Referenced by convert().
Member Data Documentation
vector<double> multiscale::video::CartesianToConcentrationsConverter::concentrations private
Concentrations received as input
Definition at line 30 of file CartesianToConcentrationsConverter.hpp.
Referenced by outputResults(), and readConcentrations().
unsigned long multiscale::video::CartesianToConcentrationsConverter::height private
Height of the grid
Definition at line 32 of file CartesianToConcentrationsConverter.hpp.
Referenced by CartesianToConcentrationsConverter(), outputResults(), readConcentrations(), and readHeaderLine().
string multiscale::video::CartesianToConcentrationsConverter::inputFilepath private
Path to the input file
Definition at line 36 of file CartesianToConcentrationsConverter.hpp.
Referenced by readInputData().
string multiscale::video::CartesianToConcentrationsConverter::outputFilepath private
Path to the output file
Definition at line 37 of file CartesianToConcentrationsConverter.hpp.
Referenced by outputResults().
double multiscale::video::CartesianToConcentrationsConverter::simulationTime private
Simulation time
Definition at line 34 of file CartesianToConcentrationsConverter.hpp.
Referenced by CartesianToConcentrationsConverter(), outputResults(), and readHeaderLine().
unsigned long multiscale::video::CartesianToConcentrationsConverter::width private
Width of the grid
Definition at line 33 of file CartesianToConcentrationsConverter.hpp.
Referenced by CartesianToConcentrationsConverter(), outputResults(), readConcentrations(), and readHeaderLine().
The documentation for this class was generated from the following files:
include/multiscale/video/rectangular/CartesianToConcentrationsConverter.hpp
src/multiscale/video/rectangular/CartesianToConcentrationsConverter.cpp