Multiscale: multiscale::analysis::Region Class Reference
multiscale::analysis::Region Class Reference
Class for representing a region.
#include <Region.hpp>
Public Member Functions
Region (double clusterednessDegree, double density, double area, double distanceFromOrigin, double angleWrtOrigin, const vector< Point > &polygon)
~Region ()
double getDensity ()
Get the density.
const vector< Point > & getPolygon ()
Get the polygon defining the region.
Public Member Functions inherited from multiscale::analysis::SpatialCollection2D
SpatialCollection2D ()
virtual ~SpatialCollection2D ()
double getClusterednessDegree ()
Get the clusteredness degree.
double getArea ()
Get the area.
double getPerimeter ()
Get the perimeter.
double getDistanceFromOrigin ()
Get the distance from the origin.
double getAngle ()
Get the angle.
Shape2D getShape ()
Get the shape best fitting the spatial collection.
Point2f getCentre ()
Get the point defining the centre of the entity.
string toString ()
Get the string representation of all field values.
Static Public Member Functions
static string fieldNamesToString ()
Get a string representation of all the field names except polygon.
Private Member Functions
void validateInputValues (double clusterednessDegree, double density, double area, double distanceFromOrigin, double angleWrtOrigin, const vector< Point > &polygon)
Validate the input values.
bool areValidInputValues (double clusterednessDegree, double density, double area, double distanceFromOrigin, double angleWrtOrigin, const vector< Point > &polygon)
Check if the input values are valid or not.
void updateSpatialCollectionSpecificValues () override
Update the value of all class specific measures.
void updateClusterednessDegree () override
Update the value of the clusteredness degree.
void updateArea () override
Update the area.
void updatePerimeter () override
Update the perimeter.
double isTriangularMeasure () override
Get the measure that the cluster has a triangular shape.
double isRectangularMeasure () override
Get the measure that the cluster has a rectangular shape.
double isCircularMeasure () override
Get the measure that the cluster has a circular shape.
void updateCentrePoint () override
Update the centre of the region.
string fieldValuesToString () override
Get a string representation of all the field values except polygon.
Private Attributes
double density
vector< Point > polygon
Additional Inherited Members
Protected Member Functions inherited from multiscale::analysis::SpatialCollection2D
void updateMeasuresIfRequired ()
Update the values of all measures if required.
void updateMeasures ()
Update the values of all measures.
void updateShape ()
Update the shape of the cluster.
string shapeAsString ()
Return the shape of the cluster as a string.
vector< Point2f > convertPoints (const vector< Point > &points)
Convert the collection of points from type Point to type Point2f.
Protected Attributes inherited from multiscale::analysis::SpatialCollection2D
double clusterednessDegree
double area
double perimeter
double distanceFromOrigin
double angle
double triangularMeasure
double rectangularMeasure
double circularMeasure
Shape2D shape
Point2f centre
bool updateFlag
Detailed Description
Class for representing a region.
Definition at line 22 of file Region.hpp.
Constructor & Destructor Documentation
Region::Region (double clusterednessDegree, double density, double area, double distanceFromOrigin, double angleWrtOrigin, const vector< Point > & polygon)
Definition at line 11 of file Region.cpp.
References multiscale::analysis::SpatialCollection2D::angle, multiscale::analysis::SpatialCollection2D::area, multiscale::analysis::SpatialCollection2D::clusterednessDegree, density, multiscale::analysis::SpatialCollection2D::distanceFromOrigin, polygon, and validateInputValues().
Region::~Region ()
Definition at line 24 of file Region.cpp.
References polygon.
Member Function Documentation
bool Region::areValidInputValues (double clusterednessDegree, double density, double area, double distanceFromOrigin, double angleWrtOrigin, const vector< Point > & polygon) private
Check if the input values are valid or not.
Validation rules: 0 < clusterednessDegree 0 < density 0 < distanceFromOrigin 0 <= angleWrtOrigin <= 360
For each polygon point p: 0 <= p.x 0 <= p.y
Parameters
clusterednessDegree The clusteredness degree of the region
density The density of the region
area The area of the region considering holes
distanceFromOrigin The distance from the origin
angleWrtOrigin The angle computed wrt to the origin
polygon The polygon
Definition at line 49 of file Region.cpp.
References multiscale::Numeric::lessOrEqual().
Referenced by validateInputValues().
string Region::fieldNamesToString () static
Get a string representation of all the field names except polygon.
Definition at line 38 of file Region.cpp.
Referenced by multiscale::analysis::RegionDetector::outputResultsToCsvFile().
string Region::fieldValuesToString () override private virtual
Get a string representation of all the field values except polygon.
Implements multiscale::analysis::SpatialCollection2D.
Definition at line 118 of file Region.cpp.
References multiscale::analysis::SpatialCollection2D::angle, multiscale::analysis::SpatialCollection2D::area, multiscale::analysis::SpatialCollection2D::centre, multiscale::analysis::SpatialCollection2D::circularMeasure, multiscale::analysis::SpatialCollection2D::clusterednessDegree, density, multiscale::analysis::SpatialCollection2D::distanceFromOrigin, OUTPUT_SEPARATOR, multiscale::analysis::SpatialCollection2D::perimeter, multiscale::analysis::SpatialCollection2D::rectangularMeasure, multiscale::analysis::SpatialCollection2D::shapeAsString(), and multiscale::analysis::SpatialCollection2D::triangularMeasure.
double Region::getDensity ()
Get the density.
Definition at line 28 of file Region.cpp.
References density, and multiscale::analysis::SpatialCollection2D::updateMeasuresIfRequired().
const vector< Point > & Region::getPolygon ()
Get the polygon defining the region.
Definition at line 34 of file Region.cpp.
References polygon.
double Region::isCircularMeasure () override private virtual
Get the measure that the cluster has a circular shape.
Implements multiscale::analysis::SpatialCollection2D.
Definition at line 99 of file Region.cpp.
References multiscale::Numeric::almostEqual(), multiscale::analysis::SpatialCollection2D::area, PI, and polygon.
double Region::isRectangularMeasure () override private virtual
Get the measure that the cluster has a rectangular shape.
Implements multiscale::analysis::SpatialCollection2D.
Definition at line 89 of file Region.cpp.
References multiscale::Numeric::almostEqual(), multiscale::analysis::SpatialCollection2D::area, and polygon.
double Region::isTriangularMeasure () override private virtual
Get the measure that the cluster has a triangular shape.
Implements multiscale::analysis::SpatialCollection2D.
Definition at line 77 of file Region.cpp.
References multiscale::Numeric::almostEqual(), multiscale::analysis::SpatialCollection2D::area, multiscale::analysis::SpatialCollection2D::convertPoints(), CONVEX_HULL_CLOCKWISE, multiscale::MinEnclosingTriangleFinder::find(), and polygon.
void Region::updateArea () override private virtual
Update the area.
Implements multiscale::analysis::SpatialCollection2D.
Definition at line 71 of file Region.cpp.
void Region::updateCentrePoint () override private virtual
Update the centre of the region.
Implements multiscale::analysis::SpatialCollection2D.
Definition at line 112 of file Region.cpp.
References multiscale::analysis::SpatialCollection2D::centre, and polygon.
void Region::updateClusterednessDegree () override private virtual
Update the value of the clusteredness degree.
Implements multiscale::analysis::SpatialCollection2D.
Definition at line 69 of file Region.cpp.
void Region::updatePerimeter () override private virtual
Update the perimeter.
Implements multiscale::analysis::SpatialCollection2D.
Definition at line 73 of file Region.cpp.
References CONTOUR_CLOSED, multiscale::analysis::SpatialCollection2D::perimeter, and polygon.
void Region::updateSpatialCollectionSpecificValues () override private virtual
Update the value of all class specific measures.
Implements multiscale::analysis::SpatialCollection2D.
Definition at line 67 of file Region.cpp.
void Region::validateInputValues (double clusterednessDegree, double density, double area, double distanceFromOrigin, double angleWrtOrigin, const vector< Point > & polygon) private
Validate the input values.
Validation rules: 0 < clusterednessDegree 0 < density 0 < distanceFromOrigin 0 <= angleWrtOrigin <= 360
For each polygon point p: 0 <= p.x 0 <= p.y
Parameters
clusterednessDegree The clusteredness degree of the region
density The density of the region
area The area of the region considering holes
distanceFromOrigin The distance from the origin
angleWrtOrigin The angle computed wrt to the origin
polygon The polygon
Definition at line 42 of file Region.cpp.
References areValidInputValues(), and ERR_INPUT.
Referenced by Region().
Member Data Documentation
double multiscale::analysis::Region::density private
             The average intensity of the pixels in the region
normalised to the interval [0, 1]
Definition at line 26 of file Region.hpp.
Referenced by fieldValuesToString(), getDensity(), and Region().
vector<Point> multiscale::analysis::Region::polygon private
Polygon defining the region
Definition at line 29 of file Region.hpp.
Referenced by getPolygon(), isCircularMeasure(), isRectangularMeasure(), isTriangularMeasure(), Region(), updateCentrePoint(), updatePerimeter(), and ~Region().
The documentation for this class was generated from the following files:
include/multiscale/analysis/spatial/Region.hpp
src/multiscale/analysis/spatial/Region.cpp