Multiscale: multiscale::video::PolarGnuplotScriptGenerator Class Reference
multiscale::video::PolarGnuplotScriptGenerator Class Reference
Gnuplot script generator from the provided annular sectors.
#include <PolarGnuplotScriptGenerator.hpp>
Static Public Member Functions
static void generateScript (const vector< AnnularSector > &annularSectors, double simulationTime, const string &outputFilepath) throw (string)
Generate the script.
Static Private Member Functions
static void generateHeader (ofstream &fout, const string &outputFilepath, double simulationTime)
Generate the header of the script.
static void generateBody (const vector< AnnularSector > &annularSectors, ofstream &fout)
Generate the body/content of the script.
static void generateFooter (ofstream &fout)
Generate the footer of the script.
static void outputHeader (ifstream &fin, const string &outputFilename, double simulationTime, ofstream &fout)
Output the header of the script.
static void outputContent (const vector< AnnularSector > &annularSectors, const string &contentTemplate, ofstream &fout)
Output the content of the script.
static void outputFooter (ifstream &fin, ofstream &fout)
Output the footer of the script.
static string readContentTemplate (ifstream &fin)
Read content template.
Detailed Description
Gnuplot script generator from the provided annular sectors.
Definition at line 31 of file PolarGnuplotScriptGenerator.hpp.
Member Function Documentation
void PolarGnuplotScriptGenerator::generateBody (const vector< AnnularSector > & annularSectors, ofstream & fout) static private
Generate the body/content of the script.
Parameters
annularSectors Annular sectors
fout Output file stream
Definition at line 41 of file PolarGnuplotScriptGenerator.cpp.
References CONTENT_IN.
void PolarGnuplotScriptGenerator::generateFooter (ofstream & fout) static private
Generate the footer of the script.
Parameters
fout Output file stream
Definition at line 53 of file PolarGnuplotScriptGenerator.cpp.
References FOOTER_IN.
void PolarGnuplotScriptGenerator::generateHeader (ofstream & fout, const string & outputFilepath, double simulationTime) static private
Generate the header of the script.
Parameters
fout Output file stream
outputFilepath Path to the output file
simulationTime Simulation time
Definition at line 29 of file PolarGnuplotScriptGenerator.cpp.
References multiscale::StringManipulator::filenameFromPath(), and HEADER_IN.
void PolarGnuplotScriptGenerator::generateScript (const vector< AnnularSector > & annularSectors, double simulationTime, const string & outputFilepath) throw (string) static
Generate the script.
Parameters
annularSectors Annular sectors
simulationTime Simulation time
outputFilepath Path of the output file
Definition at line 14 of file PolarGnuplotScriptGenerator.cpp.
References GNUPLOT_EXTENSION.
Referenced by multiscale::video::CartesianToPolarConverter::outputResultsAsScript().
void PolarGnuplotScriptGenerator::outputContent (const vector< AnnularSector > & annularSectors, const string & contentTemplate, ofstream & fout) static private
Output the content of the script.
Parameters
annularSectors Annular sectors
contentTemplate Template used for generating output for each annular sector
fout Output file stream
Definition at line 76 of file PolarGnuplotScriptGenerator.cpp.
References multiscale::StringManipulator::replace(), REPLACE_CONTENT_CONCENTRATION, REPLACE_CONTENT_END_ANGLE, REPLACE_CONTENT_INDEX, REPLACE_CONTENT_RADIUS, and REPLACE_CONTENT_START_ANGLE.
void PolarGnuplotScriptGenerator::outputFooter (ifstream & fin, ofstream & fout) static private
Output the footer of the script.
Parameters
fin Input file stream
fout Output file stream
Definition at line 94 of file PolarGnuplotScriptGenerator.cpp.
void PolarGnuplotScriptGenerator::outputHeader (ifstream & fin, const string & outputFilename, double simulationTime, ofstream & fout) static private
Output the header of the script.
Parameters
fin Input file stream
outputFilename Name of the output file
simulationTime Simulation time
fout Output file stream
Definition at line 63 of file PolarGnuplotScriptGenerator.cpp.
References multiscale::StringManipulator::replace(), REPLACE_HEADER_FILENAME, and REPLACE_HEADER_SIM_TIME.
string PolarGnuplotScriptGenerator::readContentTemplate (ifstream & fin) static private
Read content template.
Parameters
fin Input file stream
Definition at line 104 of file PolarGnuplotScriptGenerator.cpp.
The documentation for this class was generated from the following files:
include/multiscale/video/circular/PolarGnuplotScriptGenerator.hpp
src/multiscale/video/circular/PolarGnuplotScriptGenerator.cpp