Multiscale: multiscale::NumberIterator Class Reference
multiscale::NumberIterator Class Reference abstract
Abstract class representing a number iterator.
#include <NumberIterator.hpp>
Public Member Functions
NumberIterator (unsigned int upperBound)
virtual ~NumberIterator ()
void init (unsigned int upperBound)
Initialise the iterator considering the given upper bound.
bool hasNext ()
Check if there is a next number.
virtual unsigned int number ()=0
Get the number pointed by the iterator.
void reset ()
Reset the iterator.
Protected Attributes
bool isInitialised
unsigned int upperBound
Private Member Functions
virtual void initialise ()=0
Initialisation of the members of the class.
virtual bool hasNextInitialised ()=0
Check if there is a next number when in initialised state.
bool hasNextNotInitialised ()
Check if there is a next number when in not initialised state.
virtual void resetCurrentNumber ()=0
Reset the current number to its initial value.
Detailed Description
Abstract class representing a number iterator.
Definition at line 7 of file NumberIterator.hpp.
Constructor & Destructor Documentation
NumberIterator::NumberIterator (unsigned int upperBound)
Definition at line 6 of file NumberIterator.cpp.
References init().
virtual multiscale::NumberIterator::~NumberIterator () inline virtual
Definition at line 17 of file NumberIterator.hpp.
Member Function Documentation
bool NumberIterator::hasNext ()
Check if there is a next number.
Definition at line 14 of file NumberIterator.cpp.
References hasNextInitialised(), hasNextNotInitialised(), and isInitialised.
virtual bool multiscale::NumberIterator::hasNextInitialised () private pure virtual
Check if there is a next number when in initialised state.
Implemented in multiscale::LexicographicNumberIterator, and multiscale::StandardNumberIterator.
Referenced by hasNext().
bool NumberIterator::hasNextNotInitialised () private
Check if there is a next number when in not initialised state.
Definition at line 28 of file NumberIterator.cpp.
References isInitialised.
Referenced by hasNext().
void NumberIterator::init (unsigned int upperBound)
Initialise the iterator considering the given upper bound.
Parameters
upperBound The upper bound
Definition at line 10 of file NumberIterator.cpp.
References upperBound.
Referenced by NumberIterator().
virtual void multiscale::NumberIterator::initialise () private pure virtual
Initialisation of the members of the class.
Implemented in multiscale::LexicographicNumberIterator, and multiscale::StandardNumberIterator.
virtual unsigned int multiscale::NumberIterator::number () pure virtual
Get the number pointed by the iterator.
Implemented in multiscale::LexicographicNumberIterator, and multiscale::StandardNumberIterator.
void NumberIterator::reset ()
Reset the iterator.
Reset the iterator such that it is not initialised and the value of the current number is reset to its initial value
Definition at line 22 of file NumberIterator.cpp.
References isInitialised, and resetCurrentNumber().
Referenced by multiscale::LexicographicNumberIterator::LexicographicNumberIterator(), and multiscale::StandardNumberIterator::StandardNumberIterator().
virtual void multiscale::NumberIterator::resetCurrentNumber () private pure virtual
Reset the current number to its initial value.
Implemented in multiscale::LexicographicNumberIterator, and multiscale::StandardNumberIterator.
Referenced by reset().
Member Data Documentation
bool multiscale::NumberIterator::isInitialised protected
Flag for checking if the iterator was initialised
Definition at line 11 of file NumberIterator.hpp.
Referenced by hasNext(), hasNextNotInitialised(), and reset().
unsigned int multiscale::NumberIterator::upperBound protected
Upper bound of the iterator
Definition at line 12 of file NumberIterator.hpp.
Referenced by multiscale::StandardNumberIterator::hasNextInitialised(), init(), multiscale::LexicographicNumberIterator::initialise(), and multiscale::LexicographicNumberIterator::padWithZeros().
The documentation for this class was generated from the following files:
include/multiscale/util/NumberIterator.hpp
src/multiscale/util/NumberIterator.cpp