Multiscale: multiscale::MinEnclosingTriangleFinder Class Reference
multiscale::MinEnclosingTriangleFinder Class Reference
Class for computing the minimum area enclosing triangle for a given polygon.
#include <MinEnclosingTriangleFinder.hpp>
Public Member Functions
MinEnclosingTriangleFinder ()
~MinEnclosingTriangleFinder ()
double find (const vector< Point2f > &points, vector< Point2f > &minEnclosingTriangle)
Find the minimum area enclosing triangle for the given 2D point set.
Private Member Functions
void initialise (const vector< Point2f > &points, vector< Point2f > &minEnclosingTriangle)
Initialisation function for the class.
void initialiseConvexPolygon (const vector< Point2f > &points)
Initialise polygon as the convex hull of the given set of points.
double findMinEnclosingTriangle (const vector< Point2f > &polygon, vector< Point2f > &minEnclosingTriangle)
Find the minimum area enclosing triangle for the given polygon.
double returnMinEnclosingTriangle (const vector< Point2f > &polygon, vector< Point2f > &minEnclosingTriangle)
Return the minimum area enclosing triangle in case the given polygon has at most three points.
void initialiseAlgorithmVariables ()
Initialisation of the algorithm variables.
void findMinEnclosingTriangle (vector< Point2f > &minEnclosingTriangle, double &minEnclosingTriangleArea)
Find the minimum area enclosing triangle for the given polygon.
void advanceBToRightChain ()
Advance b to the right chain.
void moveAIfLowAndBIfHigh ()
Move "a" if it is low and "b" if it is high.
void searchForBTangency ()
Search for the tangency of side B.
bool isNotBTangency ()
Check if tangency for side B was not obtained.
void updateSidesCA ()
Update sides A and C.
void updateSidesBA ()
Update sides B and possibly A if tangency for side B was not obtained.
void updateSideB ()
Set side B if tangency for side B was obtained.
bool isLocalMinimalTriangle ()
Update the triangle vertices after all sides were set and check if a local minimal triangle was found or not.
bool isValidMinimalTriangle ()
Check if the found minimal triangle is valid.
void updateMinEnclosingTriangle (vector< Point2f > &minEnclosingTriangle, double &minEnclosingTriangleArea)
Update the current minimum area enclosing triangle if the newly obtained one has a smaller area.
bool middlePointOfSideB (Point2f &middlePointOfSideB)
Return the middle point of side B.
bool intersectsBelow (const Point2f &gammaPoint, unsigned int polygonPointIndex)
Check if the line determined by gammaPoint and polygon[polygonPointIndex] intersects the polygon below the point polygon[polygonPointIndex].
bool intersectsAbove (const Point2f &gammaPoint, unsigned int polygonPointIndex)
Check if the line determined by gammaPoint and polygon[polygonPointIndex] intersects the polygon above the point polygon[polygonPointIndex].
unsigned int intersects (double angleOfGammaAndPoint, unsigned int polygonPointIndex)
Check if/where the line determined by gammaPoint and polygon[polygonPointIndex] intersects the polygon.
unsigned int intersectsAboveOrBelow (unsigned int successorOrPredecessorIndex, unsigned int pointIndex)
If (gamma(x) x) intersects P between successorOrPredecessorIndex and pointIntex is it above/below?
bool isFlushAngleBetweenPredecessorAndSuccessor (double &angleFlushEdge, double anglePredecessor, double angleSuccessor)
Check if the angle of the flush edge or its opposite angle lie between the angle of the predecessor and successor.
bool isGammaAngleBetween (double &gammaAngle, double angle1, double angle2)
Check if the angle of the line (gamma(p) p) or its opposite angle lie between angle1 and angle2.
bool isGammaAngleEqualTo (double &gammaAngle, double angle)
Check if the angle of the line (gamma(p) p) or its opposite angle is equal to the given angle.
double height (unsigned int polygonPointIndex)
Compute the height of the point specified by the given index.
double height (const Point2f &polygonPoint)
Compute the height of the point.
bool gamma (unsigned int polygonPointIndex, Point2f &gammaPoint)
Find gamma for a given point "p" specified by its index.
Point2f findVertexCOnSideB ()
Find vertex C which lies on side B at a distance = 2 * height(a-1) from side C.
bool findGammaIntersectionPoints (unsigned int polygonPointIndex, const Point2f &side1StartVertex, const Point2f &side1EndVertex, const Point2f &side2StartVertex, const Point2f &side2EndVertex, Point2f &intersectionPoint1, Point2f &intersectionPoint2)
Find the intersection points to compute gamma(point)
bool areIdenticalLines (const vector< double > &side1Params, const vector< double > &side2Params, double sideCExtraParam)
Check if the given lines are identical or not.
bool areIntersectingLines (const vector< double > &side1Params, const vector< double > &side2Params, double sideCExtraParam, Point2f &intersectionPoint1, Point2f &intersectionPoint2)
Check if the given lines intersect or not. If the lines intersect find their intersection points.
vector< double > lineEquationParameters (const Point2f &p, const Point2f &q)
Get the line equation parameters "a", "b" and "c" for the line determined by points "p" and "q".
void advance (unsigned int &index)
Advance the given index with one position.
unsigned int successor (unsigned int index)
Return the succesor of the provided point index.
unsigned int predecessor (unsigned int index)
Return the predecessor of the provided point index.
Private Attributes
unsigned int validationFlag
Point2f vertexA
Point2f vertexB
Point2f vertexC
Point2f sideAStartVertex
Point2f sideAEndVertex
Point2f sideBStartVertex
Point2f sideBEndVertex
Point2f sideCStartVertex
Point2f sideCEndVertex
double area
unsigned int a
unsigned int b
unsigned int c
unsigned int nrOfPoints
vector< Point2f > polygon
Detailed Description
Class for computing the minimum area enclosing triangle for a given polygon.
This implementation has a linear complexity (theta(n)) with respect to the number of points defining the convex polygon and is based on the algorithm described in the following paper:
J. O’Rourke, A. Aggarwal, S. Maddila, and M. Baldwin, ‘An optimal algorithm for finding minimal enclosing triangles’, Journal of Algorithms, vol. 7, no. 2, pp. 258–269, Jun. 1986.
Definition at line 36 of file MinEnclosingTriangleFinder.hpp.
Constructor & Destructor Documentation
MinEnclosingTriangleFinder::MinEnclosingTriangleFinder ()
Definition at line 12 of file MinEnclosingTriangleFinder.cpp.
MinEnclosingTriangleFinder::~MinEnclosingTriangleFinder ()
Definition at line 14 of file MinEnclosingTriangleFinder.cpp.
Member Function Documentation
void MinEnclosingTriangleFinder::advance (unsigned int & index) private
Advance the given index with one position.
Parameters
index Index of the point
Definition at line 395 of file MinEnclosingTriangleFinder.cpp.
References successor().
Referenced by advanceBToRightChain(), moveAIfLowAndBIfHigh(), and searchForBTangency().
void MinEnclosingTriangleFinder::advanceBToRightChain () private
Advance b to the right chain.
See paper for more details
Definition at line 92 of file MinEnclosingTriangleFinder.cpp.
References advance(), b, multiscale::Numeric::greaterOrEqual(), height(), and successor().
Referenced by findMinEnclosingTriangle().
bool MinEnclosingTriangleFinder::areIdenticalLines (const vector< double > & side1Params, const vector< double > & side2Params, double sideCExtraParam) private
Check if the given lines are identical or not.
The lines are specified as: ax + by + c = 0 OR ax + by + c (+/-) sideCExtraParam = 0
Parameters
side1Params Vector containing the values of a, b and c for side 1
side2Params Vector containing the values of a, b and c for side 2
sideCExtraParam Extra parameter for the flush edge C
Definition at line 360 of file MinEnclosingTriangleFinder.cpp.
References multiscale::Geometry2D::areIdenticalLines().
Referenced by findGammaIntersectionPoints().
bool MinEnclosingTriangleFinder::areIntersectingLines (const vector< double > & side1Params, const vector< double > & side2Params, double sideCExtraParam, Point2f & intersectionPoint1, Point2f & intersectionPoint2) private
Check if the given lines intersect or not. If the lines intersect find their intersection points.
The lines are specified as: ax + by + c = 0 OR ax + by + c (+/-) sideCExtraParam = 0
Parameters
side1Params Vector containing the values of a, b and c for side 1
side2Params Vector containing the values of a, b and c for side 2
sideCExtraParam Extra parameter for the flush edge C
intersectionPoint1 The first intersection point, if it exists
intersectionPoint2 The second intersection point, if it exists
Definition at line 370 of file MinEnclosingTriangleFinder.cpp.
References multiscale::Geometry2D::lineIntersection().
Referenced by findGammaIntersectionPoints().
double MinEnclosingTriangleFinder::find (const vector< Point2f > & points, vector< Point2f > & minEnclosingTriangle)
Find the minimum area enclosing triangle for the given 2D point set.
Precondition: Number of points in the set is at least 1.
Parameters
points Set of points
minEnclosingTriangle Minimum area triangle enclosing the given polygon
Definition at line 16 of file MinEnclosingTriangleFinder.cpp.
References findMinEnclosingTriangle(), initialise(), polygon, and returnMinEnclosingTriangle().
Referenced by multiscale::analysis::Region::isTriangularMeasure(), and multiscale::analysis::Cluster::isTriangularMeasure().
bool MinEnclosingTriangleFinder::findGammaIntersectionPoints (unsigned int polygonPointIndex, const Point2f & side1StartVertex, const Point2f & side1EndVertex, const Point2f & side2StartVertex, const Point2f & side2EndVertex, Point2f & intersectionPoint1, Point2f & intersectionPoint2) private
Find the intersection points to compute gamma(point)
Parameters
polygonPointIndex Index of the polygon point for which the distance is known
side1StartVertex Start vertex for side 1
side1EndVertex End vertex for side 1
side2StartVertex Start vertex for side 2
side2EndVertex End vertex for side 2
intersectionPoint1 First intersection point between one pair of lines
intersectionPoint2 Second intersection point between another pair of lines
Definition at line 337 of file MinEnclosingTriangleFinder.cpp.
References areIdenticalLines(), areIntersectingLines(), height(), and lineEquationParameters().
Referenced by findVertexCOnSideB(), and gamma().
double MinEnclosingTriangleFinder::findMinEnclosingTriangle (const vector< Point2f > & polygon, vector< Point2f > & minEnclosingTriangle) private
Find the minimum area enclosing triangle for the given polygon.
Parameters
polygon Polygon of points for which the minimum area enclosing triangle will be found
minEnclosingTriangle Minimum area triangle enclosing the given polygon
Definition at line 41 of file MinEnclosingTriangleFinder.cpp.
References initialiseAlgorithmVariables().
Referenced by find().
void MinEnclosingTriangleFinder::findMinEnclosingTriangle (vector< Point2f > & minEnclosingTriangle, double & minEnclosingTriangleArea) private
Find the minimum area enclosing triangle for the given polygon.
Parameters
minEnclosingTriangle Minimum area triangle enclosing the given polygon
minEnclosingTriangleArea Area of the minimum area enclosing triangle
Definition at line 71 of file MinEnclosingTriangleFinder.cpp.
References advanceBToRightChain(), c, isLocalMinimalTriangle(), isNotBTangency(), moveAIfLowAndBIfHigh(), nrOfPoints, searchForBTangency(), updateMinEnclosingTriangle(), updateSideB(), updateSidesBA(), and updateSidesCA().
Point2f MinEnclosingTriangleFinder::findVertexCOnSideB () private
Find vertex C which lies on side B at a distance = 2 * height(a-1) from side C.
Considering that line (x y) is a line parallel to (c c-1) and that the distance between the lines is equal to 2 * height(a-1), we can have two possible (x y) lines.
Therefore, we will compute two intersection points between the lines (x y) and (b b-1) and take the point which is closest to point polygon[b].
See paper and formula for distance from point to a line for more details
Definition at line 320 of file MinEnclosingTriangleFinder.cpp.
References a, multiscale::Geometry2D::areOnTheSameSideOfLine(), c, ERR_VERTEX_C_ON_SIDE_B, findGammaIntersectionPoints(), polygon, predecessor(), sideBEndVertex, sideBStartVertex, sideCEndVertex, sideCStartVertex, and successor().
Referenced by updateSidesBA().
bool MinEnclosingTriangleFinder::gamma (unsigned int polygonPointIndex, Point2f & gammaPoint) private
Find gamma for a given point "p" specified by its index.
The function returns true if gamma exists i.e. if lines (a a-1) and (x y) intersect and false otherwise. In case the two lines intersect in point intersectionPoint, gamma is computed.
Considering that line (x y) is a line parallel to (c c-1) and that the distance between the lines is equal to 2 * height(p), we can have two possible (x y) lines.
Therefore, we will compute two intersection points between the lines (x y) and (a a-1) and take the point which is closest to point polygon[a].
See paper and formula for distance from point to a line for more details
Parameters
polygonPointIndex Index of the polygon point
gammaPoint Point2f gamma(polygon[polygonPointIndex])
Definition at line 301 of file MinEnclosingTriangleFinder.cpp.
References a, multiscale::Geometry2D::areOnTheSameSideOfLine(), c, findGammaIntersectionPoints(), polygon, predecessor(), and successor().
Referenced by isNotBTangency(), moveAIfLowAndBIfHigh(), searchForBTangency(), and updateSideB().
double MinEnclosingTriangleFinder::height (unsigned int polygonPointIndex) private
Compute the height of the point specified by the given index.
See paper for more details
Parameters
polygonPointIndex Index of the polygon point
Definition at line 285 of file MinEnclosingTriangleFinder.cpp.
References c, multiscale::Geometry2D::distanceFromPointToLine(), polygon, and predecessor().
Referenced by advanceBToRightChain(), findGammaIntersectionPoints(), intersectsAboveOrBelow(), isNotBTangency(), moveAIfLowAndBIfHigh(), searchForBTangency(), and updateSidesBA().
double MinEnclosingTriangleFinder::height (const Point2f & polygonPoint) private
Compute the height of the point.
See paper for more details
Parameters
polygonPoint Polygon point
Definition at line 294 of file MinEnclosingTriangleFinder.cpp.
References c, multiscale::Geometry2D::distanceFromPointToLine(), polygon, and predecessor().
void MinEnclosingTriangleFinder::initialise (const vector< Point2f > & points, vector< Point2f > & minEnclosingTriangle) private
Initialisation function for the class.
Initialise the polygon and other class' fields.
Parameters
points Set of points
minEnclosingTriangle Minimum area triangle enclosing the given polygon
Definition at line 28 of file MinEnclosingTriangleFinder.cpp.
References initialiseConvexPolygon().
Referenced by find().
void MinEnclosingTriangleFinder::initialiseAlgorithmVariables () private
Initialisation of the algorithm variables.
Definition at line 63 of file MinEnclosingTriangleFinder.cpp.
References a, b, c, nrOfPoints, and polygon.
Referenced by findMinEnclosingTriangle().
void MinEnclosingTriangleFinder::initialiseConvexPolygon (const vector< Point2f > & points) private
Initialise polygon as the convex hull of the given set of points.
Parameters
points Set of points
Definition at line 35 of file MinEnclosingTriangleFinder.cpp.
References CONVEX_HULL_CLOCKWISE, and polygon.
Referenced by initialise().
unsigned int MinEnclosingTriangleFinder::intersects (double angleOfGammaAndPoint, unsigned int polygonPointIndex) private
Check if/where the line determined by gammaPoint and polygon[polygonPointIndex] intersects the polygon.
Parameters
angleOfGammaAndPoint Angle between gammaPoint and polygon[polygonPointIndex]
polygonPointIndex Index of the polygon point which is considered when determining the line
Definition at line 232 of file MinEnclosingTriangleFinder.cpp.
References multiscale::Numeric::almostEqual(), multiscale::Geometry2D::angleOfLineWrtOxAxis(), c, INTERSECTS_BELOW, INTERSECTS_CRITICAL, intersectsAboveOrBelow(), isFlushAngleBetweenPredecessorAndSuccessor(), isGammaAngleBetween(), isGammaAngleEqualTo(), polygon, predecessor(), and successor().
Referenced by intersectsAbove(), and intersectsBelow().
bool MinEnclosingTriangleFinder::intersectsAbove (const Point2f & gammaPoint, unsigned int polygonPointIndex) private
Check if the line determined by gammaPoint and polygon[polygonPointIndex] intersects the polygon above the point polygon[polygonPointIndex].
Parameters
gammaPoint Gamma(p)
polygonPointIndex Index of the polygon point which is considered when determining the line
Definition at line 226 of file MinEnclosingTriangleFinder.cpp.
References multiscale::Geometry2D::angleOfLineWrtOxAxis(), intersects(), INTERSECTS_ABOVE, and polygon.
Referenced by isNotBTangency().
unsigned int MinEnclosingTriangleFinder::intersectsAboveOrBelow (unsigned int successorOrPredecessorIndex, unsigned int pointIndex) private
If (gamma(x) x) intersects P between successorOrPredecessorIndex and pointIntex is it above/below?
Parameters
successorOrPredecessorIndex Index of the successor or predecessor
pointIndex Index of the point x in the polygon
Definition at line 256 of file MinEnclosingTriangleFinder.cpp.
References height(), INTERSECTS_ABOVE, and INTERSECTS_BELOW.
Referenced by intersects().
bool MinEnclosingTriangleFinder::intersectsBelow (const Point2f & gammaPoint, unsigned int polygonPointIndex) private
Check if the line determined by gammaPoint and polygon[polygonPointIndex] intersects the polygon below the point polygon[polygonPointIndex].
Parameters
gammaPoint Gamma(p)
polygonPointIndex Index of the polygon point which is considered when determining the line
Definition at line 220 of file MinEnclosingTriangleFinder.cpp.
References multiscale::Geometry2D::angleOfLineWrtOxAxis(), intersects(), INTERSECTS_BELOW, and polygon.
Referenced by moveAIfLowAndBIfHigh(), and searchForBTangency().
bool MinEnclosingTriangleFinder::isFlushAngleBetweenPredecessorAndSuccessor (double & angleFlushEdge, double anglePredecessor, double angleSuccessor) private
Check if the angle of the flush edge or its opposite angle lie between the angle of the predecessor and successor.
Parameters
angleFlushEdge Angle of the flush edge
anglePredecessor Angle of the predecessor
angleSuccessor Angle of the successor
Definition at line 264 of file MinEnclosingTriangleFinder.cpp.
References multiscale::Geometry2D::isAngleBetweenNonReflex(), multiscale::Geometry2D::isOppositeAngleBetweenNonReflex(), and multiscale::Geometry2D::oppositeAngle().
Referenced by intersects().
bool MinEnclosingTriangleFinder::isGammaAngleBetween (double & gammaAngle, double angle1, double angle2) private
Check if the angle of the line (gamma(p) p) or its opposite angle lie between angle1 and angle2.
Parameters
gammaAngle Angle of the line (gamma(p) p)
angle1 One of the boundary angles
angle2 Another boundary angle
Definition at line 277 of file MinEnclosingTriangleFinder.cpp.
References multiscale::Geometry2D::isAngleBetweenNonReflex().
Referenced by intersects().
bool MinEnclosingTriangleFinder::isGammaAngleEqualTo (double & gammaAngle, double angle) private
Check if the angle of the line (gamma(p) p) or its opposite angle is equal to the given angle.
Parameters
gammaAngle Angle of the line (gamma(p) p)
angle Angle to compare against
Definition at line 281 of file MinEnclosingTriangleFinder.cpp.
References multiscale::Numeric::almostEqual().
Referenced by intersects().
bool MinEnclosingTriangleFinder::isLocalMinimalTriangle () private
Update the triangle vertices after all sides were set and check if a local minimal triangle was found or not.
See paper for more details
Definition at line 165 of file MinEnclosingTriangleFinder.cpp.
References isValidMinimalTriangle(), multiscale::Geometry2D::lineIntersection(), sideAEndVertex, sideAStartVertex, sideBEndVertex, sideBStartVertex, sideCEndVertex, sideCStartVertex, vertexA, vertexB, and vertexC.
Referenced by findMinEnclosingTriangle().
bool MinEnclosingTriangleFinder::isNotBTangency () private
Check if tangency for side B was not obtained.
See paper for more details
Definition at line 119 of file MinEnclosingTriangleFinder.cpp.
References a, b, gamma(), height(), intersectsAbove(), and predecessor().
Referenced by findMinEnclosingTriangle().
bool MinEnclosingTriangleFinder::isValidMinimalTriangle () private
Check if the found minimal triangle is valid.
This means that all midpoints of the triangle should touch the polygon
See paper for more details
Definition at line 175 of file MinEnclosingTriangleFinder.cpp.
References a, multiscale::Geometry2D::areEqualPoints(), b, multiscale::Geometry2D::isPointOnLineSegment(), multiscale::Geometry2D::middlePoint(), polygon, predecessor(), sideAEndVertex, sideAStartVertex, sideBEndVertex, sideBStartVertex, sideCEndVertex, sideCStartVertex, VALIDATION_SIDE_A_TANGENT, VALIDATION_SIDE_B_TANGENT, validationFlag, vertexA, vertexB, and vertexC.
Referenced by isLocalMinimalTriangle().
vector< double > MinEnclosingTriangleFinder::lineEquationParameters (const Point2f & p, const Point2f & q) private
Get the line equation parameters "a", "b" and "c" for the line determined by points "p" and "q".
The equation of the line is considered in the general form: ax + by + c = 0
Parameters
p One point for defining the equation of the line
q Second point for defining the equation of the line
Definition at line 382 of file MinEnclosingTriangleFinder.cpp.
References a, b, c, and multiscale::Geometry2D::lineEquationDeterminedByPoints().
Referenced by findGammaIntersectionPoints().
bool MinEnclosingTriangleFinder::middlePointOfSideB (Point2f & middlePointOfSideB) private
Return the middle point of side B.
Definition at line 207 of file MinEnclosingTriangleFinder.cpp.
References multiscale::Geometry2D::lineIntersection(), multiscale::Geometry2D::middlePoint(), sideAEndVertex, sideAStartVertex, sideBEndVertex, sideBStartVertex, sideCEndVertex, sideCStartVertex, vertexA, and vertexC.
Referenced by updateSidesBA().
void MinEnclosingTriangleFinder::moveAIfLowAndBIfHigh () private
Move "a" if it is low and "b" if it is high.
See paper for more details
Definition at line 98 of file MinEnclosingTriangleFinder.cpp.
References a, advance(), b, gamma(), height(), and intersectsBelow().
Referenced by findMinEnclosingTriangle().
unsigned int MinEnclosingTriangleFinder::predecessor (unsigned int index) private
Return the predecessor of the provided point index.
The predecessor of the first polygon point is the last polygon point (circular referencing)
Parameters
index Index of the point
Definition at line 403 of file MinEnclosingTriangleFinder.cpp.
References nrOfPoints.
Referenced by findVertexCOnSideB(), gamma(), height(), intersects(), isNotBTangency(), isValidMinimalTriangle(), searchForBTangency(), updateSidesBA(), and updateSidesCA().
double MinEnclosingTriangleFinder::returnMinEnclosingTriangle (const vector< Point2f > & polygon, vector< Point2f > & minEnclosingTriangle) private
Return the minimum area enclosing triangle in case the given polygon has at most three points.
Parameters
polygon Polygon of points for which the minimum area enclosing triangle will be found
minEnclosingTriangle Minimum area triangle enclosing the given polygon
Definition at line 52 of file MinEnclosingTriangleFinder.cpp.
References multiscale::Geometry2D::areaOfTriangle().
Referenced by find().
void MinEnclosingTriangleFinder::searchForBTangency () private
Search for the tangency of side B.
See paper for more details
Definition at line 110 of file MinEnclosingTriangleFinder.cpp.
References a, advance(), b, gamma(), multiscale::Numeric::greaterOrEqual(), height(), intersectsBelow(), and predecessor().
Referenced by findMinEnclosingTriangle().
unsigned int MinEnclosingTriangleFinder::successor (unsigned int index) private
Return the succesor of the provided point index.
The succesor of the last polygon point is the first polygon point (circular referencing)
Parameters
index Index of the point
Definition at line 399 of file MinEnclosingTriangleFinder.cpp.
References nrOfPoints.
Referenced by advance(), advanceBToRightChain(), findVertexCOnSideB(), gamma(), and intersects().
void MinEnclosingTriangleFinder::updateMinEnclosingTriangle (vector< Point2f > & minEnclosingTriangle, double & minEnclosingTriangleArea) private
Update the current minimum area enclosing triangle if the newly obtained one has a smaller area.
Parameters
minEnclosingTriangle Minimum area triangle enclosing the given polygon
minEnclosingTriangleArea Area of the minimum area triangle enclosing the given polygon
Definition at line 193 of file MinEnclosingTriangleFinder.cpp.
References area, multiscale::Geometry2D::areaOfTriangle(), vertexA, vertexB, and vertexC.
Referenced by findMinEnclosingTriangle().
void MinEnclosingTriangleFinder::updateSideB () private
Set side B if tangency for side B was obtained.
See paper for more details
Definition at line 155 of file MinEnclosingTriangleFinder.cpp.
References b, ERR_SIDE_B_GAMMA, gamma(), polygon, sideBEndVertex, sideBStartVertex, VALIDATION_SIDE_B_TANGENT, and validationFlag.
Referenced by findMinEnclosingTriangle().
void MinEnclosingTriangleFinder::updateSidesBA () private
Update sides B and possibly A if tangency for side B was not obtained.
See paper for more details
Definition at line 137 of file MinEnclosingTriangleFinder.cpp.
References a, b, findVertexCOnSideB(), height(), middlePointOfSideB(), polygon, predecessor(), sideAEndVertex, sideAStartVertex, sideBEndVertex, sideBStartVertex, VALIDATION_SIDE_A_TANGENT, VALIDATION_SIDES_FLUSH, and validationFlag.
Referenced by findMinEnclosingTriangle().
void MinEnclosingTriangleFinder::updateSidesCA () private
Update sides A and C.
Side C will have as start and end vertices the polygon points "c" and "c-1" Side A will have as start and end vertices the polygon points "a" and "a-1"
Definition at line 129 of file MinEnclosingTriangleFinder.cpp.
References a, c, polygon, predecessor(), sideAEndVertex, sideAStartVertex, sideCEndVertex, and sideCStartVertex.
Referenced by findMinEnclosingTriangle().
Member Data Documentation
unsigned int multiscale::MinEnclosingTriangleFinder::a private
Index of point "a"; see paper for more details
Definition at line 61 of file MinEnclosingTriangleFinder.hpp.
Referenced by findVertexCOnSideB(), gamma(), initialiseAlgorithmVariables(), isNotBTangency(), isValidMinimalTriangle(), lineEquationParameters(), moveAIfLowAndBIfHigh(), searchForBTangency(), updateSidesBA(), and updateSidesCA().
double multiscale::MinEnclosingTriangleFinder::area private
Area of the current considered enclosing triangle
Definition at line 59 of file MinEnclosingTriangleFinder.hpp.
Referenced by updateMinEnclosingTriangle().
unsigned int multiscale::MinEnclosingTriangleFinder::b private
Index of point "b"; see paper for more details
Definition at line 62 of file MinEnclosingTriangleFinder.hpp.
Referenced by advanceBToRightChain(), initialiseAlgorithmVariables(), isNotBTangency(), isValidMinimalTriangle(), lineEquationParameters(), moveAIfLowAndBIfHigh(), searchForBTangency(), updateSideB(), and updateSidesBA().
unsigned int multiscale::MinEnclosingTriangleFinder::c private
Index of point "c"; see paper for more details
Definition at line 63 of file MinEnclosingTriangleFinder.hpp.
Referenced by findMinEnclosingTriangle(), findVertexCOnSideB(), gamma(), height(), initialiseAlgorithmVariables(), intersects(), lineEquationParameters(), and updateSidesCA().
unsigned int multiscale::MinEnclosingTriangleFinder::nrOfPoints private
Number of points defining the polygon
Definition at line 65 of file MinEnclosingTriangleFinder.hpp.
Referenced by findMinEnclosingTriangle(), initialiseAlgorithmVariables(), predecessor(), and successor().
vector<Point2f> multiscale::MinEnclosingTriangleFinder::polygon private
Polygon for which the minimum area enclosing triangle is computed
Definition at line 67 of file MinEnclosingTriangleFinder.hpp.
Referenced by find(), findVertexCOnSideB(), gamma(), height(), initialiseAlgorithmVariables(), initialiseConvexPolygon(), intersects(), intersectsAbove(), intersectsBelow(), isValidMinimalTriangle(), updateSideB(), updateSidesBA(), and updateSidesCA().
Point2f multiscale::MinEnclosingTriangleFinder::sideAEndVertex private
Ending vertex for side A of triangle
Definition at line 51 of file MinEnclosingTriangleFinder.hpp.
Referenced by isLocalMinimalTriangle(), isValidMinimalTriangle(), middlePointOfSideB(), updateSidesBA(), and updateSidesCA().
Point2f multiscale::MinEnclosingTriangleFinder::sideAStartVertex private
Starting vertex for side A of triangle
Definition at line 50 of file MinEnclosingTriangleFinder.hpp.
Referenced by isLocalMinimalTriangle(), isValidMinimalTriangle(), middlePointOfSideB(), updateSidesBA(), and updateSidesCA().
Point2f multiscale::MinEnclosingTriangleFinder::sideBEndVertex private
Ending vertex for side B of triangle
Definition at line 54 of file MinEnclosingTriangleFinder.hpp.
Referenced by findVertexCOnSideB(), isLocalMinimalTriangle(), isValidMinimalTriangle(), middlePointOfSideB(), updateSideB(), and updateSidesBA().
Point2f multiscale::MinEnclosingTriangleFinder::sideBStartVertex private
Starting vertex for side B of triangle
Definition at line 53 of file MinEnclosingTriangleFinder.hpp.
Referenced by findVertexCOnSideB(), isLocalMinimalTriangle(), isValidMinimalTriangle(), middlePointOfSideB(), updateSideB(), and updateSidesBA().
Point2f multiscale::MinEnclosingTriangleFinder::sideCEndVertex private
Ending vertex for side C of triangle
Definition at line 57 of file MinEnclosingTriangleFinder.hpp.
Referenced by findVertexCOnSideB(), isLocalMinimalTriangle(), isValidMinimalTriangle(), middlePointOfSideB(), and updateSidesCA().
Point2f multiscale::MinEnclosingTriangleFinder::sideCStartVertex private
Starting vertex for side C of triangle
Definition at line 56 of file MinEnclosingTriangleFinder.hpp.
Referenced by findVertexCOnSideB(), isLocalMinimalTriangle(), isValidMinimalTriangle(), middlePointOfSideB(), and updateSidesCA().
unsigned int multiscale::MinEnclosingTriangleFinder::validationFlag private
Validation flag can take the following values:
VALIDATION_SIDE_A_TANGENT;
VALIDATION_SIDE_B_TANGENT;
VALIDATION_SIDES_FLUSH.
Definition at line 40 of file MinEnclosingTriangleFinder.hpp.
Referenced by isValidMinimalTriangle(), updateSideB(), and updateSidesBA().
Point2f multiscale::MinEnclosingTriangleFinder::vertexA private
Vertex A of the current considered enclosing triangle
Definition at line 46 of file MinEnclosingTriangleFinder.hpp.
Referenced by isLocalMinimalTriangle(), isValidMinimalTriangle(), middlePointOfSideB(), and updateMinEnclosingTriangle().
Point2f multiscale::MinEnclosingTriangleFinder::vertexB private
Vertex B of the current considered enclosing triangle
Definition at line 47 of file MinEnclosingTriangleFinder.hpp.
Referenced by isLocalMinimalTriangle(), isValidMinimalTriangle(), and updateMinEnclosingTriangle().
Point2f multiscale::MinEnclosingTriangleFinder::vertexC private
Vertex C of the current considered enclosing triangle
Definition at line 48 of file MinEnclosingTriangleFinder.hpp.
Referenced by isLocalMinimalTriangle(), isValidMinimalTriangle(), middlePointOfSideB(), and updateMinEnclosingTriangle().
The documentation for this class was generated from the following files:
include/multiscale/util/MinEnclosingTriangleFinder.hpp
src/multiscale/util/MinEnclosingTriangleFinder.cpp