Multiscale: multiscale::StandardNumberIterator Class Reference
multiscale::StandardNumberIterator Class Reference
Iterator class starting at 1 and iterating over all natural numbers until the provided upper bound is reached.
#include <StandardNumberIterator.hpp>
Public Member Functions
StandardNumberIterator (unsigned int upperBound)
~StandardNumberIterator ()
unsigned int number ()
Get the number pointed by the iterator.
Public Member Functions inherited from multiscale::NumberIterator
NumberIterator (unsigned int upperBound)
virtual ~NumberIterator ()
void init (unsigned int upperBound)
Initialise the iterator considering the given upper bound.
bool hasNext ()
Check if there is a next number.
void reset ()
Reset the iterator.
Private Member Functions
void initialise ()
Initialise the value of the current number.
bool hasNextInitialised ()
Check if there is a next number when in initialised state.
void resetCurrentNumber ()
Reset the current number to the initial value.
Private Attributes
unsigned int currentNumber
Additional Inherited Members
Protected Attributes inherited from multiscale::NumberIterator
bool isInitialised
unsigned int upperBound
Detailed Description
Iterator class starting at 1 and iterating over all natural numbers until the provided upper bound is reached.
Definition at line 10 of file StandardNumberIterator.hpp.
Constructor & Destructor Documentation
StandardNumberIterator::StandardNumberIterator (unsigned int upperBound)
Definition at line 6 of file StandardNumberIterator.cpp.
References initialise(), and multiscale::NumberIterator::reset().
StandardNumberIterator::~StandardNumberIterator ()
Definition at line 11 of file StandardNumberIterator.cpp.
Member Function Documentation
bool StandardNumberIterator::hasNextInitialised () private virtual
Check if there is a next number when in initialised state.
Implements multiscale::NumberIterator.
Definition at line 19 of file StandardNumberIterator.cpp.
References currentNumber, and multiscale::NumberIterator::upperBound.
void StandardNumberIterator::initialise () private virtual
Initialise the value of the current number.
Implements multiscale::NumberIterator.
Definition at line 17 of file StandardNumberIterator.cpp.
Referenced by StandardNumberIterator().
unsigned int StandardNumberIterator::number () virtual
Get the number pointed by the iterator.
Implements multiscale::NumberIterator.
Definition at line 13 of file StandardNumberIterator.cpp.
References currentNumber.
void StandardNumberIterator::resetCurrentNumber () private virtual
Reset the current number to the initial value.
Implements multiscale::NumberIterator.
Definition at line 29 of file StandardNumberIterator.cpp.
References currentNumber.
Member Data Documentation
unsigned int multiscale::StandardNumberIterator::currentNumber private
The current number
Definition at line 14 of file StandardNumberIterator.hpp.
Referenced by hasNextInitialised(), number(), and resetCurrentNumber().
The documentation for this class was generated from the following files:
include/multiscale/util/iterator/StandardNumberIterator.hpp
src/multiscale/util/iterator/StandardNumberIterator.cpp