Multiscale: multiscale::analysis::Entity Class Reference
multiscale::analysis::Entity Class Reference
Class for representing an entity in an image (e.g. cell, organism etc.)
#include <Entity.hpp>
Public Member Functions
Entity (unsigned int pileUpDegree, double area, const Point2f &centre, const vector< Point2f > &contourPoints)
Entity (const Entity &entity)
~Entity ()
unsigned int getPileUpDegree () const
Get the degree of pile up.
double getArea () const
Get the area.
Point2f getCentre () const
Get the point defining the centre of the entity.
vector< Point2f > getContourPoints () const
Get the set of points defining the contour of the entity.
string toString ()
Get a string representation of all the field values.
double distanceTo (shared_ptr< DataPoint > point) override
Get the distance between this entity and another one.
double distanceTo (const Entity &entity)
Get the distance between this entity and another one.
Public Member Functions inherited from multiscale::analysis::DataPoint
virtual ~DataPoint ()
Private Member Functions
void validateInputValues (unsigned int pileUpDegree, double area, const Point2f &centre, const vector< Point2f > &contourPoints)
bool areValid (unsigned int pileUpDegree, double area, const Point2f &centre, const vector< Point2f > &contourPoints)
Check if the provided degree of pile up, area, centre and contour points are valid.
Private Attributes
unsigned int pileUpDegree
double area
Point2f centre
vector< Point2f > contourPoints
Detailed Description
Class for representing an entity in an image (e.g. cell, organism etc.)
Definition at line 24 of file Entity.hpp.
Constructor & Destructor Documentation
Entity::Entity (unsigned int pileUpDegree, double area, const Point2f & centre, const vector< Point2f > & contourPoints)
Definition at line 9 of file Entity.cpp.
References area, centre, contourPoints, pileUpDegree, and validateInputValues().
Entity::Entity (const Entity & entity)
Definition at line 18 of file Entity.cpp.
References area, centre, contourPoints, pileUpDegree, and validateInputValues().
Entity::~Entity ()
Definition at line 27 of file Entity.cpp.
Member Function Documentation
bool Entity::areValid (unsigned int pileUpDegree, double area, const Point2f & centre, const vector< Point2f > & contourPoints) private
Check if the provided degree of pile up, area, centre and contour points are valid.
Parameters
pileUpDegree Degree of pile up
area Area
centre Centre of the entity
contourPoints Points defining the contour of the entity
Definition at line 66 of file Entity.cpp.
Referenced by validateInputValues().
double Entity::distanceTo (shared_ptr< DataPoint > point) override virtual
Get the distance between this entity and another one.
Implements multiscale::analysis::DataPoint.
Definition at line 51 of file Entity.cpp.
References centre, and multiscale::Geometry2D::distanceBtwPoints().
double Entity::distanceTo (const Entity & entity)
Get the distance between this entity and another one.
Definition at line 57 of file Entity.cpp.
References centre, and multiscale::Geometry2D::distanceBtwPoints().
double Entity::getArea () const
Get the area.
Definition at line 33 of file Entity.cpp.
References area.
Point2f Entity::getCentre () const
Get the point defining the centre of the entity.
Definition at line 37 of file Entity.cpp.
References centre.
vector< Point2f > Entity::getContourPoints () const
Get the set of points defining the contour of the entity.
Definition at line 41 of file Entity.cpp.
References contourPoints.
unsigned int Entity::getPileUpDegree () const
Get the degree of pile up.
Definition at line 29 of file Entity.cpp.
References pileUpDegree.
string Entity::toString ()
Get a string representation of all the field values.
Definition at line 45 of file Entity.cpp.
References centre, OUTPUT_SEPARATOR, and pileUpDegree.
void Entity::validateInputValues (unsigned int pileUpDegree, double area, const Point2f & centre, const vector< Point2f > & contourPoints) private
Parameters
pileUpDegree Degree of pile up
area Area
centre Centre of the entity
contourPoints Points defining the contour of the entity
Definition at line 61 of file Entity.cpp.
References areValid(), and ERR_INPUT.
Referenced by Entity().
Member Data Documentation
double multiscale::analysis::Entity::area private
Area of the entity
Definition at line 29 of file Entity.hpp.
Referenced by Entity(), and getArea().
Point2f multiscale::analysis::Entity::centre private
Point defining the centre of the entity
Definition at line 31 of file Entity.hpp.
Referenced by distanceTo(), Entity(), getCentre(), and toString().
vector<Point2f> multiscale::analysis::Entity::contourPoints private
Set of points defining the contour of the entity
Definition at line 32 of file Entity.hpp.
Referenced by Entity(), and getContourPoints().
unsigned int multiscale::analysis::Entity::pileUpDegree private
Degree of pile up (relevant only if entities can pile up onto each other)
Definition at line 28 of file Entity.hpp.
Referenced by Entity(), getPileUpDegree(), and toString().
The documentation for this class was generated from the following files:
include/multiscale/analysis/spatial/Entity.hpp
src/multiscale/analysis/spatial/Entity.cpp