Multiscale: multiscale::Numeric Class Reference
multiscale::Numeric Class Reference
Class for manipulating numbers (shorts, ints, floats, doubles etc.)
#include <Numeric.hpp>
Static Public Member Functions
static bool greaterOrEqual (double number1, double number2)
Check if the first number is greater than or equal to the second number.
static bool lessOrEqual (double number1, double number2)
Check if the first number is less than or equal to the second number.
static bool almostEqual (double number1, double number2)
Check if the two numbers are equal (almost)
static double maximum (double number1, double number2, double number3)
Return the maximum of the provided numbers.
static int sign (double number)
Return the sign of the number.
Static Private Attributes
static double epsilon = 1E-5
Detailed Description
Class for manipulating numbers (shorts, ints, floats, doubles etc.)
Definition at line 14 of file Numeric.hpp.
Member Function Documentation
bool Numeric::almostEqual (double number1, double number2) static
Check if the two numbers are equal (almost)
The expression for determining if two real numbers are equal is: if (Abs(x - y) <= EPSILON * Max(1.0f, Abs(x), Abs(y))).
Parameters
number1 First number
number2 Second number
Definition at line 17 of file Numeric.cpp.
References epsilon, and maximum().
Referenced by multiscale::Geometry2D::areCollinear(), multiscale::Geometry2D::areEqualPoints(), multiscale::Geometry2D::areIdenticalLines(), greaterOrEqual(), multiscale::MinEnclosingTriangleFinder::intersects(), multiscale::analysis::Region::isCircularMeasure(), multiscale::analysis::Cluster::isCircularMeasure(), multiscale::MinEnclosingTriangleFinder::isGammaAngleEqualTo(), multiscale::Geometry2D::isPointOnLineSegment(), multiscale::analysis::Region::isRectangularMeasure(), multiscale::analysis::Cluster::isRectangularMeasure(), multiscale::analysis::Region::isTriangularMeasure(), multiscale::analysis::Cluster::isTriangularMeasure(), lessOrEqual(), and multiscale::Geometry2D::lineIntersection().
bool Numeric::greaterOrEqual (double number1, double number2) static
Check if the first number is greater than or equal to the second number.
Definition at line 9 of file Numeric.cpp.
References almostEqual().
Referenced by multiscale::MinEnclosingTriangleFinder::advanceBToRightChain(), multiscale::analysis::Entity::areValid(), and multiscale::MinEnclosingTriangleFinder::searchForBTangency().
bool Numeric::lessOrEqual (double number1, double number2) static
Check if the first number is less than or equal to the second number.
Definition at line 13 of file Numeric.cpp.
References almostEqual().
Referenced by multiscale::analysis::Region::areValidInputValues(), and multiscale::Geometry2D::isAngleBetweenNonReflex().
double Numeric::maximum (double number1, double number2, double number3) static
Return the maximum of the provided numbers.
Definition at line 21 of file Numeric.cpp.
Referenced by almostEqual().
int Numeric::sign (double number) static
Return the sign of the number.
The sign function returns: -1, if number < 0 +1, if number > 0 0, otherwise
Definition at line 25 of file Numeric.cpp.
Referenced by multiscale::Geometry2D::areOnTheSameSideOfLine().
Member Data Documentation
double Numeric::epsilon = 1E-5 static private
Value of epsilon used to compare two real numbers
Definition at line 18 of file Numeric.hpp.
Referenced by almostEqual().
The documentation for this class was generated from the following files:
modules/util/include/multiscale/util/Numeric.hpp
modules/util/src/Numeric.cpp