Multiscale: multiscale::analysis::DBSCAN Class Reference
multiscale::analysis::DBSCAN Class Reference
#include <DBSCAN.hpp>
Static Public Member Functions
static void run (const vector< shared_ptr< DataPoint >> &dataPoints, vector< int > &clusterIndexes, int &nrOfClusters, double eps, int minPoints)
Run the improved DBSCAN algorithm on the provided set of points.
Static Private Member Functions
static void runAlgorithm (const vector< shared_ptr< DataPoint >> &dataPoints, vector< int > &clusterIndexes, int &nrOfClusters)
Run the improved DBSCAN algorithm on the provided set of points.
static void constructDistanceMatrix (const vector< shared_ptr< DataPoint >> &dataPoints)
Construct the distance matrix between any two data points.
static bool expandCoreCluster (vector< int > &clusterIndexes, int coreDataPointIndex, int clusterId)
Expand the cluster around the given core data point.
static void addUnclassifiedNodesToSeedsList (const vector< int > &neighbours, const vector< int > &clusterIndexes, vector< int > &seeds)
Add all unclassified neighbour nodes to the seeds list.
static void labelUnclassifiedAndNoiseAsBorder (const vector< int > &neighbours, vector< int > &clusterIndexes)
Label all unclassified and noise neighbour nodes as border nodes.
static vector< int > retrieveNeighbours (int dataPointIndex)
Retrieve the list of neighbour indexes which are at a distance < eps far from the given data point.
static void assignBorderNodesToClusters (vector< int > &clusterIndexes)
Assign the border nodes to the clusters to which the closest core objects belong.
static int findClosestCoreDataPoint (const vector< int > &neighbours, int borderDataPointIndex, const vector< int > &clusterIndexes)
Find the closest core data point from the given set of neighbours to the given border data point.
static void allocateDistanceMatrix ()
Allocate the distance matrix.
Static Private Attributes
static double eps = 0
static unsigned int minPoints = 0
static unsigned int nrOfDataPoints = 0
static vector< vector< double > > distanceMatrix
Detailed Description
Definition at line 20 of file DBSCAN.hpp.
Member Function Documentation
void DBSCAN::addUnclassifiedNodesToSeedsList (const vector< int > & neighbours, const vector< int > & clusterIndexes, vector< int > & seeds) static private
Add all unclassified neighbour nodes to the seeds list.
Parameters
neighbours Neighbour nodes
clusterIndexes Indexes to which cluster each data point belongs
seeds List of seeds (see DBSCAN algorithm)
Definition at line 85 of file DBSCAN.cpp.
References CLUSTERING_UNCLASSIFIED.
Referenced by expandCoreCluster().
void DBSCAN::allocateDistanceMatrix () static private
Allocate the distance matrix.
Definition at line 148 of file DBSCAN.cpp.
References distanceMatrix, and nrOfDataPoints.
Referenced by constructDistanceMatrix().
void DBSCAN::assignBorderNodesToClusters (vector< int > & clusterIndexes) static private
Assign the border nodes to the clusters to which the closest core objects belong.
Parameters
clusterIndexes Indexes to which cluster each data point belongs
Definition at line 117 of file DBSCAN.cpp.
References CLUSTERING_BORDER, findClosestCoreDataPoint(), nrOfDataPoints, and retrieveNeighbours().
Referenced by runAlgorithm().
void DBSCAN::constructDistanceMatrix (const vector< shared_ptr< DataPoint >> & dataPoints) static private
Construct the distance matrix between any two data points.
Parameters
dataPoints Data points
Definition at line 44 of file DBSCAN.cpp.
References allocateDistanceMatrix(), distanceMatrix, and nrOfDataPoints.
Referenced by run().
bool DBSCAN::expandCoreCluster (vector< int > & clusterIndexes, int coreDataPointIndex, int clusterId) static private
Expand the cluster around the given core data point.
Parameters
clusterIndexes Indexes to which cluster each data point belongs
coreDataPointIndex Core data point index
clusterId Id of the cluster to which the core data point belongs
Definition at line 57 of file DBSCAN.cpp.
References addUnclassifiedNodesToSeedsList(), CLUSTERING_NOISE, labelUnclassifiedAndNoiseAsBorder(), minPoints, and retrieveNeighbours().
Referenced by runAlgorithm().
int DBSCAN::findClosestCoreDataPoint (const vector< int > & neighbours, int borderDataPointIndex, const vector< int > & clusterIndexes) static private
Find the closest core data point from the given set of neighbours to the given border data point.
Parameters
neighbours Set of neighbours
borderDataPointIndex Index of the border data point
clusterIndexes Indexes to which cluster each data point belongs
Definition at line 128 of file DBSCAN.cpp.
References distanceMatrix.
Referenced by assignBorderNodesToClusters().
void DBSCAN::labelUnclassifiedAndNoiseAsBorder (const vector< int > & neighbours, vector< int > & clusterIndexes) static private
Label all unclassified and noise neighbour nodes as border nodes.
Parameters
neighbours Neighbour nodes
clusterIndexes Indexes to which cluster each data point belongs
Definition at line 94 of file DBSCAN.cpp.
References CLUSTERING_BORDER, CLUSTERING_NOISE, and CLUSTERING_UNCLASSIFIED.
Referenced by expandCoreCluster().
vector< int > DBSCAN::retrieveNeighbours (int dataPointIndex) static private
Retrieve the list of neighbour indexes which are at a distance < eps far from the given data point.
Parameters
dataPointIndex Index of the data point for which the neighbours will be retrieved
Definition at line 103 of file DBSCAN.cpp.
References distanceMatrix, eps, and nrOfDataPoints.
Referenced by assignBorderNodesToClusters(), and expandCoreCluster().
void DBSCAN::run (const vector< shared_ptr< DataPoint >> & dataPoints, vector< int > & clusterIndexes, int & nrOfClusters, double eps, int minPoints) static
Run the improved DBSCAN algorithm on the provided set of points.
The implementation of the improved DBSCAN algorithm is based on the paper: T. N. Tran, K. Drab, and M. Daszykowski, Revised DBSCAN algorithm to cluster data with dense adjacent clusters, Chemometrics and Intelligent Laboratory Systems, vol. 120, pp. 9296, Jan. 2013.
Clusters start from index 1, because cluster 0 contains only noise data/points.
Parameters
dataPoints Collection of data points
clusterIndexes Indexes to which cluster each data point belongs
nrOfClusters Total number of clusters
eps Maximum distance between two neighbours
minPoints Minimum number of points in one cluster
Definition at line 15 of file DBSCAN.cpp.
References constructDistanceMatrix(), eps, minPoints, nrOfDataPoints, and runAlgorithm().
Referenced by multiscale::analysis::ClusterDetector::detectClusters().
void DBSCAN::runAlgorithm (const vector< shared_ptr< DataPoint >> & dataPoints, vector< int > & clusterIndexes, int & nrOfClusters) static private
Run the improved DBSCAN algorithm on the provided set of points.
The implementation of the improved DBSCAN algorithm is based on the paper: T. N. Tran, K. Drab, and M. Daszykowski, Revised DBSCAN algorithm to cluster data with dense adjacent clusters, Chemometrics and Intelligent Laboratory Systems, vol. 120, pp. 9296, Jan. 2013.
Clusters start from index 1, because cluster 0 contains only noise data/points.
Parameters
dataPoints Collection of data points
clusterIndexes Indexes to which cluster each data point belongs
nrOfClusters Total number of clusters
Definition at line 26 of file DBSCAN.cpp.
References assignBorderNodesToClusters(), CLUSTERING_UNCLASSIFIED, expandCoreCluster(), and nrOfDataPoints.
Referenced by run().
Member Data Documentation
vector< vector< double > > DBSCAN::distanceMatrix static private
The matrix containing the distances between any two data points
Definition at line 31 of file DBSCAN.hpp.
Referenced by allocateDistanceMatrix(), constructDistanceMatrix(), findClosestCoreDataPoint(), and retrieveNeighbours().
double DBSCAN::eps = 0 static private
                              DBSCAN algorithm parameter for specifying the maximum radius
of the neighbourhood
Definition at line 24 of file DBSCAN.hpp.
Referenced by retrieveNeighbours(), and run().
unsigned int DBSCAN::minPoints = 0 static private
                  DBSCAN algorithm parameter for specifying the minimum number
of points in an eps-neighbourhood of that point
Definition at line 26 of file DBSCAN.hpp.
Referenced by expandCoreCluster(), and run().
unsigned int DBSCAN::nrOfDataPoints = 0 static private
Number of data points in the data set
Definition at line 29 of file DBSCAN.hpp.
Referenced by allocateDistanceMatrix(), assignBorderNodesToClusters(), constructDistanceMatrix(), retrieveNeighbours(), run(), and runAlgorithm().
The documentation for this class was generated from the following files:
include/multiscale/analysis/spatial/DBSCAN.hpp
src/multiscale/analysis/spatial/DBSCAN.cpp