Multiscale: multiscale::analysis::Silhouette Class Reference
multiscale::analysis::Silhouette Class Reference
Class for computing the "Silhouette" clustering index.
#include <Silhouette.hpp>
Static Public Member Functions
static double computeOverallAverageMeasure (const vector< Cluster > &clusters)
Compute the overall average silhouette measure for the given collection of clusters.
static double computeAverageMeasure (unsigned int clusterIndex, const vector< Cluster > &clusters)
Compute the average silhouette measure for the given cluster.
static double computeMeasure (unsigned int entityIndex, unsigned int clusterIndex, const vector< Cluster > &clusters)
Compute the silhouette measure for the given entity.
Static Private Member Functions
static double computeAverageDissimilarityWithinCluster (unsigned int entityIndex, unsigned int clusterIndex, const vector< Cluster > &clusters)
Compute the average dissimilarity within cluster to which the entity belongs.
static double computeAverageDissimilarityToOtherClusters (unsigned int entityIndex, unsigned int clusterIndex, const vector< Cluster > &clusters)
Compute the average dissimilarity of the entity to the other clusters (i.e. clusters which are different from the cluster to which the entity belongs)
static double computeAverageDissimilarityBtwEntityAndCluster (unsigned int entityIndex, unsigned int entityClusterIndex, unsigned int clusterIndex, const vector< Cluster > &clusters)
Compute the average dissimilarity between entity and cluster.
Detailed Description
Class for computing the "Silhouette" clustering index.
Definition at line 14 of file Silhouette.hpp.
Member Function Documentation
double Silhouette::computeAverageDissimilarityBtwEntityAndCluster (unsigned int entityIndex, unsigned int entityClusterIndex, unsigned int clusterIndex, const vector< Cluster > & clusters) static private
Compute the average dissimilarity between entity and cluster.
Parameters
entityIndex The index of the entity in the cluster for which the distance is computed
entityClusterIndex The index of the cluster to which the entity belongs
clusterIndex The index of the cluster to which the average distance is computed
clusters Collection of all clusters
Definition at line 84 of file Silhouette.cpp.
References multiscale::Geometry2D::distanceBtwPoints().
double Silhouette::computeAverageDissimilarityToOtherClusters (unsigned int entityIndex, unsigned int clusterIndex, const vector< Cluster > & clusters) static private
Compute the average dissimilarity of the entity to the other clusters (i.e. clusters which are different from the cluster to which the entity belongs)
Parameters
entityIndex The index of the entity in the cluster for which the silhouette measure is computed
clusterIndex The index of the cluster to which the entity belongs
clusters Collection of all clusters
Definition at line 66 of file Silhouette.cpp.
double Silhouette::computeAverageDissimilarityWithinCluster (unsigned int entityIndex, unsigned int clusterIndex, const vector< Cluster > & clusters) static private
Compute the average dissimilarity within cluster to which the entity belongs.
Parameters
entityIndex The index of the entity in the cluster for which the silhouette measure is computed
clusterIndex The index of the cluster to which the entity belongs
clusters Collection of all clusters
Definition at line 52 of file Silhouette.cpp.
References multiscale::Geometry2D::distanceBtwPoints().
double Silhouette::computeAverageMeasure (unsigned int clusterIndex, const vector< Cluster > & clusters) static
Compute the average silhouette measure for the given cluster.
Parameters
clusterIndex The index of the cluster for which the average silhouette measure is computed
clusters Collection of all clusters
Definition at line 26 of file Silhouette.cpp.
double Silhouette::computeMeasure (unsigned int entityIndex, unsigned int clusterIndex, const vector< Cluster > & clusters) static
Compute the silhouette measure for the given entity.
Parameters
entityIndex The index of the entity in the cluster for which the silhouette measure is computed
clusterIndex The index of the cluster to which the entity belongs
clusters Collection of all clusters
Definition at line 42 of file Silhouette.cpp.
double Silhouette::computeOverallAverageMeasure (const vector< Cluster > & clusters) static
Compute the overall average silhouette measure for the given collection of clusters.
Parameters
clusters Collection of all clusters
Definition at line 11 of file Silhouette.cpp.
Referenced by multiscale::analysis::ClusterDetector::computeClusterednessIndex().
The documentation for this class was generated from the following files:
modules/analysis/spatial/include/multiscale/analysis/spatial/Silhouette.hpp
modules/analysis/spatial/src/Silhouette.cpp