Multiscale: multiscale::LexicographicNumberIterator Class Reference
multiscale::LexicographicNumberIterator Class Reference
#include <LexicographicNumberIterator.hpp>
Public Member Functions
LexicographicNumberIterator (unsigned int upperBound)
~LexicographicNumberIterator ()
unsigned int number ()
Public Member Functions inherited from multiscale::NumberIterator
NumberIterator (unsigned int upperBound)
virtual ~NumberIterator ()
void init (unsigned int upperBound)
bool hasNext ()
void reset ()
Private Member Functions
void initialise ()
bool hasNextInitialised ()
void resetCurrentNumber ()
void numberToDigits (unsigned int number, vector< unsigned char > &digits)
void reverseDigits (vector< unsigned char > &digits)
unsigned int digitsToNumber (vector< unsigned char > &digits)
bool isLargerThanUpperBound (unsigned char lastDigit)
void padWithZeros ()
Private Attributes
vector< unsigned char > upperBoundDigits
vector< unsigned char > currentNumberDigits
Additional Inherited Members
Protected Attributes inherited from multiscale::NumberIterator
bool isInitialised
unsigned int upperBound
Detailed Description
Definition at line 16 of file LexicographicNumberIterator.hpp.
Constructor & Destructor Documentation
LexicographicNumberIterator::LexicographicNumberIterator (unsigned int upperBound)
Definition at line 7 of file LexicographicNumberIterator.cpp.
References initialise(), and multiscale::NumberIterator::reset().
LexicographicNumberIterator::~LexicographicNumberIterator ()
Definition at line 13 of file LexicographicNumberIterator.cpp.
References currentNumberDigits, and upperBoundDigits.
Member Function Documentation
unsigned int LexicographicNumberIterator::digitsToNumber (vector< unsigned char > & digits) private
Definition at line 83 of file LexicographicNumberIterator.cpp.
References number().
Referenced by number(), and padWithZeros().
bool LexicographicNumberIterator::hasNextInitialised () private virtual
Implements multiscale::NumberIterator.
Definition at line 31 of file LexicographicNumberIterator.cpp.
References currentNumberDigits, isLargerThanUpperBound(), and padWithZeros().
void LexicographicNumberIterator::initialise () private virtual
Implements multiscale::NumberIterator.
Definition at line 24 of file LexicographicNumberIterator.cpp.
References currentNumberDigits, numberToDigits(), multiscale::NumberIterator::upperBound, and upperBoundDigits.
Referenced by LexicographicNumberIterator().
bool LexicographicNumberIterator::isLargerThanUpperBound (unsigned char lastDigit) private
Definition at line 100 of file LexicographicNumberIterator.cpp.
References currentNumberDigits, and upperBoundDigits.
Referenced by hasNextInitialised().
unsigned int LexicographicNumberIterator::number () virtual
Implements multiscale::NumberIterator.
Definition at line 19 of file LexicographicNumberIterator.cpp.
References currentNumberDigits, and digitsToNumber().
Referenced by digitsToNumber().
void LexicographicNumberIterator::numberToDigits (unsigned int number, vector< unsigned char > & digits) private
Definition at line 60 of file LexicographicNumberIterator.cpp.
References reverseDigits().
Referenced by initialise().
void LexicographicNumberIterator::padWithZeros () private
Definition at line 125 of file LexicographicNumberIterator.cpp.
References currentNumberDigits, digitsToNumber(), multiscale::NumberIterator::upperBound, and upperBoundDigits.
Referenced by hasNextInitialised().
void LexicographicNumberIterator::resetCurrentNumber () private virtual
Implements multiscale::NumberIterator.
Definition at line 48 of file LexicographicNumberIterator.cpp.
References currentNumberDigits, and upperBoundDigits.
void LexicographicNumberIterator::reverseDigits (vector< unsigned char > & digits) private
Definition at line 71 of file LexicographicNumberIterator.cpp.
Referenced by numberToDigits().
Member Data Documentation
vector<unsigned char> multiscale::LexicographicNumberIterator::currentNumberDigits private
Definition at line 21 of file LexicographicNumberIterator.hpp.
Referenced by hasNextInitialised(), initialise(), isLargerThanUpperBound(), number(), padWithZeros(), resetCurrentNumber(), and ~LexicographicNumberIterator().
vector<unsigned char> multiscale::LexicographicNumberIterator::upperBoundDigits private
Definition at line 20 of file LexicographicNumberIterator.hpp.
Referenced by initialise(), isLargerThanUpperBound(), padWithZeros(), resetCurrentNumber(), and ~LexicographicNumberIterator().
The documentation for this class was generated from the following files:
include/multiscale/util/iterator/LexicographicNumberIterator.hpp
src/multiscale/util/iterator/LexicographicNumberIterator.cpp