Multiscale: multiscale::analysis::RegionDetector Class Reference
multiscale::analysis::RegionDetector Class Reference
Class for detecting regions of high intensity in grayscale images.
#include <RegionDetector.hpp>
Public Member Functions
RegionDetector (bool debugMode=false)
~RegionDetector ()
int getAlpha ()
Get the value of field alpha.
int getBeta ()
Get the value of field beta.
int getBlurKernelSize ()
Get the value of field blurKernelSize.
int getEpsilon ()
Get the value of field epsilon.
int getMorphologicalCloseIterations ()
Get the value of field morphologicalCloseIterations.
int getOriginXCoordinate ()
Get the value of field originXCoordinate.
int getOriginYCoordinate ()
Get the value of field originYCoordinate.
int getRegionAreaThresh ()
Get the value of field regionAreaThresh.
int getThresholdValue ()
Get the value of field thresholdValue.
vector< Region > const & getRegions ()
Get a const reference to the vector of detected regions.
void setAlpha (int alpha)
Set the value of field alpha.
void setBeta (int beta)
Set the value of field beta.
void setBlurKernelSize (int blurKernelSize)
Set the value of field blurKernelSize.
void setEpsilon (int epsilon)
Set the value of field epsilon.
void setMorphologicalCloseIterations (int morphologicalCloseIterations)
Set the value of field morphologicalCloseIterations.
void setOriginXCoordinate (int originXCoordinate)
Set the value of field originXCoordinate.
void setOriginYCoordinate (int originYCoordinate)
Set the value of field originYCoordinate.
void setRegionAreaThresh (int regionAreaThresh)
Set the value of field regionAreaThresh.
void setThresholdValue (int thresholdValue)
Set the value of field thresholdValue.
Public Member Functions inherited from multiscale::analysis::Detector
Detector (bool debugMode=false)
virtual ~Detector ()
void detect (const Mat &inputImage)
Run the detection procedure on the given image.
void outputResults (const string &outputFilepath)
Output the results to the given file.
Private Member Functions
void initialiseDetectorSpecificFields () override
Initialise the vision members.
void initialiseDetectorSpecificImageDependentFields () override
Initialisation of the detector specific image dependent values.
void createDetectorSpecificTrackbars () override
Create the trackbars.
void processImageAndDetect () override
Process the given image.
void changeContrastAndBrightness (Mat &processedImage)
Change the contrast and brightness of the image.
void smoothImage (Mat &image)
Smooth out differences in the image.
void morphologicalClose (Mat &image)
Apply the morphological close operator on the image.
void thresholdImage (const Mat &image, Mat &thresholdedImage)
Apply the threshold filter on the image.
void findRegions (const Mat &image, vector< Region > &regions)
Find the regions in the image.
void computeAverageMeasures (vector< Region > &regions)
Compute the average clusteredness degree and average density.
vector< vector< Point > > findContoursInImage (const Mat &image)
Find contours in image.
Region createRegionFromPolygon (const vector< Point > &polygon)
Create a new region from the given polygon.
bool isValidRegion (const vector< Point > &polygon)
Check if the region is valid.
double regionClusterednessDegree (const vector< Point > &polygon)
Compute the clusteredness degree of the region delimited by the given polygon.
double regionDensity (const vector< Point > &polygon)
Compute the density of the area delimited by the given polygon.
double regionArea (const vector< Point > &polygon)
Compute the area of the given polygon considering holes.
double regionHolesArea (const Mat &matrix)
Compute the area of the white holes in the given matrix.
void clearPreviousDetectionResults () override
Clear the element present in the regions vector.
void outputResultsToCsvFile (ofstream &fout) override
Output the regions and averaged measures to a csv file.
void outputRegionsToCsvFile (ofstream &fout)
Output the regions to a csv file.
void outputAveragedMeasuresToCsvFile (ofstream &fout)
Output the averaged measures to a csv file.
void outputResultsToImage () override
Output the results to the outputImage instance.
double convertAlpha (int alpha)
Convert alpha from the range [0, ALPHA_MAX] to [ALPHA_REAL_MIN, ALPHA_REAL_MAX].
int convertBeta (int beta)
Convert beta from the range [0, BETA_MAX] to [BETA_REAL_MIN, BETA_REAL_MAX].
Private Attributes
double avgClusterednessDegree
double avgDensity
int alpha
int beta
int blurKernelSize
int morphologicalCloseIterations
int epsilon
int regionAreaThresh
int thresholdValue
vector< Region > regions
Additional Inherited Members
Protected Member Functions inherited from multiscale::analysis::Detector
void initialise ()
Initialisation function for the class.
void initialiseDetectorSpecificFieldsIfNotSet ()
Initialisation of the detector specific values in case they were not set.
void setDetectorSpecificFieldsInitialisationFlag (bool flag=true)
Set the detector specific fields initialisation flag to true.
void initialiseImageDependentFields ()
Initialisation of the image dependent values.
void initialiseImageOrigin ()
bool isValidInputImage (const Mat &inputImage)
Check if the image is valid.
void detect ()
Run the detection procedure.
void detectInDebugMode ()
Run the detection procedure when in debug mode.
void detectInReleaseMode ()
Run the detection procedure when in release mode (i.e. non-debug mode)
double polygonAngle (const vector< Point > &polygon, unsigned int closestPointIndex)
Compute the angle of the polygon.
double polygonAngle (const vector< Point > &polygonConvexHull, const Point &closestPoint)
Compute the angle of the polygon.
void minAreaRectCentre (const vector< Point > &polygon, Point &centre)
Get the centre of the minimum area bounding rectangle.
void findGoodPointsForAngle (const vector< Point > &polygonConvexHull, const Point &boundingRectCentre, const Point &closestPoint, vector< Point > &goodPointsForAngle)
Find the points for determining the angle of the polygon.
void findGoodIntersectionPoints (const vector< Point > &polygonConvexHull, const Point &edgePointA, const Point &edgePointB, vector< Point > &goodPointsForAngle)
Find good intersection points for computing the angle of the polygon.
void displayResultsInWindow ()
Display the results in a window.
void outputResultsToFile ()
Output the results to file(s)
void storeOutputImageOnDisk ()
Store the image with the output results on disk.
void outputResultsToCsvFile ()
Output the results to a file.
void createTrackbars ()
Create the trackbars which allow the user to change the values of the parameters.
void createTrackbarsWindow ()
Create the window in which the trackbars are placed.
void processPressedKeyRequest (char &pressedKey)
Process the request of the user by pressing the key.
void displayImage (const Mat &image, const string &windowName)
Display an image in a particular window.
void printOutputErrorMessage ()
Print error message, because the detect method was not called before calling the output method.
Protected Attributes inherited from multiscale::analysis::Detector
Mat image
string outputFilepath
bool debugMode
Mat outputImage
bool detectMethodCalled
bool detectorSpecificFieldsInitialised
Point origin
Detailed Description
Class for detecting regions of high intensity in grayscale images.
Definition at line 56 of file RegionDetector.hpp.
Constructor & Destructor Documentation
RegionDetector::RegionDetector (bool debugMode = false)
Definition at line 15 of file RegionDetector.cpp.
References alpha, avgClusterednessDegree, avgDensity, beta, blurKernelSize, epsilon, morphologicalCloseIterations, regionAreaThresh, and thresholdValue.
RegionDetector::~RegionDetector ()
Definition at line 28 of file RegionDetector.cpp.
Member Function Documentation
void RegionDetector::changeContrastAndBrightness (Mat & processedImage) private
Change the contrast and brightness of the image.
Change the contrast and brightness of the image by the factors alpha and gamma
Parameters
processedImage The processed image
Definition at line 158 of file RegionDetector.cpp.
References alpha, beta, convertAlpha(), convertBeta(), and multiscale::analysis::Detector::image.
Referenced by processImageAndDetect().
void RegionDetector::clearPreviousDetectionResults () override private virtual
Clear the element present in the regions vector.
Implements multiscale::analysis::Detector.
Definition at line 288 of file RegionDetector.cpp.
References regions.
void RegionDetector::computeAverageMeasures (vector< Region > & regions) private
Compute the average clusteredness degree and average density.
Parameters
regions The regions in the image
Definition at line 198 of file RegionDetector.cpp.
References avgClusterednessDegree, and avgDensity.
Referenced by processImageAndDetect().
double RegionDetector::convertAlpha (int alpha) private
Convert alpha from the range [0, ALPHA_MAX] to [ALPHA_REAL_MIN, ALPHA_REAL_MAX].
Parameters
alpha Alpha
Definition at line 335 of file RegionDetector.cpp.
References alpha, ALPHA_MAX, ALPHA_REAL_MAX, and ALPHA_REAL_MIN.
Referenced by changeContrastAndBrightness().
int RegionDetector::convertBeta (int beta) private
Convert beta from the range [0, BETA_MAX] to [BETA_REAL_MIN, BETA_REAL_MAX].
Parameters
beta Beta
Definition at line 339 of file RegionDetector.cpp.
References beta, BETA_MAX, BETA_REAL_MAX, and BETA_REAL_MIN.
Referenced by changeContrastAndBrightness().
void RegionDetector::createDetectorSpecificTrackbars () override private virtual
Create the trackbars.
Implements multiscale::analysis::Detector.
Definition at line 136 of file RegionDetector.cpp.
References alpha, ALPHA_MAX, beta, BETA_MAX, blurKernelSize, epsilon, EPSILON_MAX, KERNEL_MAX, MORPH_ITER_MAX, morphologicalCloseIterations, REGION_AREA_THRESH_MAX, regionAreaThresh, THRESHOLD_MAX, thresholdValue, TRACKBAR_ALPHA, TRACKBAR_BETA, TRACKBAR_EPSILON, TRACKBAR_KERNEL, TRACKBAR_MORPH, TRACKBAR_REGION_AREA_THRESH, TRACKBAR_THRESHOLD, and WIN_OUTPUT_IMAGE.
Region RegionDetector::createRegionFromPolygon (const vector< Point > & polygon) private
Create a new region from the given polygon.
Process the polygon in order to get the required information and create a region using this information
Parameters
polygon Polygon determining the region
Definition at line 226 of file RegionDetector.cpp.
References multiscale::Geometry2D::distanceBtwPoints(), multiscale::Geometry2D::minimumDistancePointIndex(), multiscale::analysis::Detector::origin, multiscale::analysis::Detector::polygonAngle(), regionArea(), regionClusterednessDegree(), and regionDensity().
Referenced by findRegions().
vector< vector< Point > > RegionDetector::findContoursInImage (const Mat & image) private
Find contours in image.
Parameters
image The image
Definition at line 211 of file RegionDetector.cpp.
Referenced by findRegions(), and regionHolesArea().
void RegionDetector::findRegions (const Mat & image, vector< Region > & regions) private
Find the regions in the image.
Find the contours, approximate the polygons and extract the required information from them.
Parameters
image The image
regions The regions in the image
Definition at line 180 of file RegionDetector.cpp.
References createRegionFromPolygon(), epsilon, findContoursInImage(), and isValidRegion().
Referenced by processImageAndDetect().
int RegionDetector::getAlpha ()
Get the value of field alpha.
Definition at line 30 of file RegionDetector.cpp.
References alpha.
Referenced by saveDetectorParameterValues().
int RegionDetector::getBeta ()
Get the value of field beta.
Definition at line 34 of file RegionDetector.cpp.
References beta.
Referenced by saveDetectorParameterValues().
int RegionDetector::getBlurKernelSize ()
Get the value of field blurKernelSize.
Definition at line 38 of file RegionDetector.cpp.
References blurKernelSize.
Referenced by saveDetectorParameterValues().
int RegionDetector::getEpsilon ()
Get the value of field epsilon.
Definition at line 46 of file RegionDetector.cpp.
References epsilon.
Referenced by saveDetectorParameterValues().
int RegionDetector::getMorphologicalCloseIterations ()
Get the value of field morphologicalCloseIterations.
Definition at line 42 of file RegionDetector.cpp.
References morphologicalCloseIterations.
Referenced by saveDetectorParameterValues().
int RegionDetector::getOriginXCoordinate ()
Get the value of field originXCoordinate.
Definition at line 54 of file RegionDetector.cpp.
References multiscale::analysis::Detector::origin.
int RegionDetector::getOriginYCoordinate ()
Get the value of field originYCoordinate.
Definition at line 58 of file RegionDetector.cpp.
References multiscale::analysis::Detector::origin.
int RegionDetector::getRegionAreaThresh ()
Get the value of field regionAreaThresh.
Definition at line 50 of file RegionDetector.cpp.
References regionAreaThresh.
Referenced by saveDetectorParameterValues().
vector< Region > const & RegionDetector::getRegions ()
Get a const reference to the vector of detected regions.
Definition at line 66 of file RegionDetector.cpp.
References regions.
int RegionDetector::getThresholdValue ()
Get the value of field thresholdValue.
Definition at line 62 of file RegionDetector.cpp.
References thresholdValue.
Referenced by saveDetectorParameterValues().
void RegionDetector::initialiseDetectorSpecificFields () override private virtual
Initialise the vision members.
Implements multiscale::analysis::Detector.
Definition at line 124 of file RegionDetector.cpp.
References alpha, beta, blurKernelSize, epsilon, morphologicalCloseIterations, regionAreaThresh, and thresholdValue.
void RegionDetector::initialiseDetectorSpecificImageDependentFields () override private virtual
Initialisation of the detector specific image dependent values.
Implements multiscale::analysis::Detector.
Definition at line 134 of file RegionDetector.cpp.
bool RegionDetector::isValidRegion (const vector< Point > & polygon) private
Check if the region is valid.
Check if the area of the region > regionAreaThreshold
Parameters
polygon The polygon defining the region
Definition at line 238 of file RegionDetector.cpp.
References CONTOUR_AREA_ORIENTED, and regionAreaThresh.
Referenced by findRegions().
void RegionDetector::morphologicalClose (Mat & image) private
Apply the morphological close operator on the image.
Parameters
image The image
Definition at line 170 of file RegionDetector.cpp.
References morphologicalCloseIterations.
Referenced by processImageAndDetect().
void RegionDetector::outputAveragedMeasuresToCsvFile (ofstream & fout) private
Output the averaged measures to a csv file.
Parameters
fout Output file stream
Definition at line 312 of file RegionDetector.cpp.
References avgClusterednessDegree, avgDensity, OUTPUT_CLUSTEREDNESS, and OUTPUT_DENSITY.
Referenced by outputResultsToCsvFile().
void RegionDetector::outputRegionsToCsvFile (ofstream & fout) private
Output the regions to a csv file.
Parameters
fout Output file stream
Definition at line 306 of file RegionDetector.cpp.
References regions.
Referenced by outputResultsToCsvFile().
void RegionDetector::outputResultsToCsvFile (ofstream & fout) override private virtual
Output the regions and averaged measures to a csv file.
Parameters
fout Output file stream
Implements multiscale::analysis::Detector.
Definition at line 292 of file RegionDetector.cpp.
References multiscale::analysis::Region::fieldNamesToString(), outputAveragedMeasuresToCsvFile(), outputRegionsToCsvFile(), and regions.
void RegionDetector::outputResultsToImage () override private virtual
Output the results to the outputImage instance.
Implements multiscale::analysis::Detector.
Definition at line 317 of file RegionDetector.cpp.
References DISPLAY_LINE_THICKNESS, multiscale::analysis::Detector::image, INTENSITY_MAX, multiscale::analysis::Detector::outputImage, POLYGON_CLOSED, and regions.
void RegionDetector::processImageAndDetect () override private virtual
Process the given image.
Apply filters to the image, threshold it, find its contours, approximate the polygons from these contours. Afterwards, process the polygons to find their distance from the origin, their area and the angle determined by the points from the contour which are on the edge and the closest point to the origin. Return all the polygons together with the processed information as a vector of regions.
Implements multiscale::analysis::Detector.
Definition at line 146 of file RegionDetector.cpp.
References changeContrastAndBrightness(), computeAverageMeasures(), findRegions(), morphologicalClose(), regions, smoothImage(), and thresholdImage().
double RegionDetector::regionArea (const vector< Point > & polygon) private
Compute the area of the given polygon considering holes.
Parameters
polygon The given polygon
Definition at line 266 of file RegionDetector.cpp.
References CONTOUR_AREA_ORIENTED, multiscale::analysis::Detector::image, INTENSITY_MAX, regionHolesArea(), THRESHOLD_CLUSTEREDNESS, and THRESHOLD_MAX.
Referenced by createRegionFromPolygon().
double RegionDetector::regionClusterednessDegree (const vector< Point > & polygon) private
Compute the clusteredness degree of the region delimited by the given polygon.
The density is equal to the average intensity of the pixels in the area delimited by the given polygon divided by INTENSITY_MAX. The intensities are considered from the thresholded image where the threshold value is 1 i.e. only the black patches are discarded.
Parameters
polygon The given polygon
Definition at line 244 of file RegionDetector.cpp.
References multiscale::analysis::Detector::image, INTENSITY_MAX, THRESHOLD_CLUSTEREDNESS, and THRESHOLD_MAX.
Referenced by createRegionFromPolygon().
double RegionDetector::regionDensity (const vector< Point > & polygon) private
Compute the density of the area delimited by the given polygon.
The density is equal to the average intensity of the pixels in the area delimited by the given polygon divided by INTENSITY_MAX.
Parameters
polygon The given polygon
Definition at line 256 of file RegionDetector.cpp.
References multiscale::analysis::Detector::image, and INTENSITY_MAX.
Referenced by createRegionFromPolygon().
double RegionDetector::regionHolesArea (const Mat & matrix) private
Compute the area of the white holes in the given matrix.
Parameters
matrix The given matrix
Definition at line 277 of file RegionDetector.cpp.
References CONTOUR_AREA_ORIENTED, and findContoursInImage().
Referenced by regionArea().
void RegionDetector::setAlpha (int alpha)
Set the value of field alpha.
Parameters
alpha Value of alpha
Definition at line 70 of file RegionDetector.cpp.
References alpha, and multiscale::analysis::Detector::setDetectorSpecificFieldsInitialisationFlag().
Referenced by loadDetectorParameterValues().
void RegionDetector::setBeta (int beta)
Set the value of field beta.
Parameters
beta Value of beta
Definition at line 76 of file RegionDetector.cpp.
References beta, and multiscale::analysis::Detector::setDetectorSpecificFieldsInitialisationFlag().
Referenced by loadDetectorParameterValues().
void RegionDetector::setBlurKernelSize (int blurKernelSize)
Set the value of field blurKernelSize.
Parameters
blurKernelSize Value of blurKernelSize
Definition at line 82 of file RegionDetector.cpp.
References blurKernelSize, and multiscale::analysis::Detector::setDetectorSpecificFieldsInitialisationFlag().
Referenced by loadDetectorParameterValues().
void RegionDetector::setEpsilon (int epsilon)
Set the value of field epsilon.
Parameters
epsilon Value of epsilon
Definition at line 88 of file RegionDetector.cpp.
References epsilon, and multiscale::analysis::Detector::setDetectorSpecificFieldsInitialisationFlag().
Referenced by loadDetectorParameterValues().
void RegionDetector::setMorphologicalCloseIterations (int morphologicalCloseIterations)
Set the value of field morphologicalCloseIterations.
Parameters
morphologicalCloseIterations Value of morphologicalCloseIterations
Definition at line 94 of file RegionDetector.cpp.
References morphologicalCloseIterations, and multiscale::analysis::Detector::setDetectorSpecificFieldsInitialisationFlag().
Referenced by loadDetectorParameterValues().
void RegionDetector::setOriginXCoordinate (int originXCoordinate)
Set the value of field originXCoordinate.
Parameters
originXCoordinate Value of originXCoordinate
Definition at line 100 of file RegionDetector.cpp.
References multiscale::analysis::Detector::origin, and multiscale::analysis::Detector::setDetectorSpecificFieldsInitialisationFlag().
void RegionDetector::setOriginYCoordinate (int originYCoordinate)
Set the value of field originYCoordinate.
Parameters
originYCoordinate Value of originYCoordinate
Definition at line 106 of file RegionDetector.cpp.
References multiscale::analysis::Detector::origin, and multiscale::analysis::Detector::setDetectorSpecificFieldsInitialisationFlag().
void RegionDetector::setRegionAreaThresh (int regionAreaThresh)
Set the value of field regionAreaThresh.
Parameters
regionAreaThresh Value of regionAreaThresh
Definition at line 112 of file RegionDetector.cpp.
References regionAreaThresh, and multiscale::analysis::Detector::setDetectorSpecificFieldsInitialisationFlag().
Referenced by loadDetectorParameterValues().
void RegionDetector::setThresholdValue (int thresholdValue)
Set the value of field thresholdValue.
Parameters
thresholdValue Value of thresholdValue
Definition at line 118 of file RegionDetector.cpp.
References multiscale::analysis::Detector::setDetectorSpecificFieldsInitialisationFlag(), and thresholdValue.
Referenced by loadDetectorParameterValues().
void RegionDetector::smoothImage (Mat & image) private
Smooth out differences in the image.
Apply a Gaussian blur filter
Parameters
image The image
Definition at line 162 of file RegionDetector.cpp.
References blurKernelSize.
Referenced by processImageAndDetect().
void RegionDetector::thresholdImage (const Mat & image, Mat & thresholdedImage) private
Apply the threshold filter on the image.
Parameters
image The image
thresholdedImage The thresholded image
Definition at line 176 of file RegionDetector.cpp.
References THRESHOLD_MAX, and thresholdValue.
Referenced by processImageAndDetect().
Member Data Documentation
int multiscale::analysis::RegionDetector::alpha private
Alpha for brightness and contrast adjustments
Definition at line 63 of file RegionDetector.hpp.
Referenced by changeContrastAndBrightness(), convertAlpha(), createDetectorSpecificTrackbars(), getAlpha(), initialiseDetectorSpecificFields(), RegionDetector(), and setAlpha().
double multiscale::analysis::RegionDetector::avgClusterednessDegree private
Average degree of clusteredness of all regions
Definition at line 60 of file RegionDetector.hpp.
Referenced by computeAverageMeasures(), outputAveragedMeasuresToCsvFile(), and RegionDetector().
double multiscale::analysis::RegionDetector::avgDensity private
Average density of all regions
Definition at line 61 of file RegionDetector.hpp.
Referenced by computeAverageMeasures(), outputAveragedMeasuresToCsvFile(), and RegionDetector().
int multiscale::analysis::RegionDetector::beta private
Beta for brightness and contrast adjustments
Definition at line 64 of file RegionDetector.hpp.
Referenced by changeContrastAndBrightness(), convertBeta(), createDetectorSpecificTrackbars(), getBeta(), initialiseDetectorSpecificFields(), RegionDetector(), and setBeta().
int multiscale::analysis::RegionDetector::blurKernelSize private
Kernel size for Gaussian blur
Definition at line 65 of file RegionDetector.hpp.
Referenced by createDetectorSpecificTrackbars(), getBlurKernelSize(), initialiseDetectorSpecificFields(), RegionDetector(), setBlurKernelSize(), and smoothImage().
int multiscale::analysis::RegionDetector::epsilon private
Epsilon for polygon approximation
Definition at line 67 of file RegionDetector.hpp.
Referenced by createDetectorSpecificTrackbars(), findRegions(), getEpsilon(), initialiseDetectorSpecificFields(), RegionDetector(), and setEpsilon().
int multiscale::analysis::RegionDetector::morphologicalCloseIterations private
Number of iterations for morphological close operator
Definition at line 66 of file RegionDetector.hpp.
Referenced by createDetectorSpecificTrackbars(), getMorphologicalCloseIterations(), initialiseDetectorSpecificFields(), morphologicalClose(), RegionDetector(), and setMorphologicalCloseIterations().
int multiscale::analysis::RegionDetector::regionAreaThresh private
Threshold for considering a region
Definition at line 68 of file RegionDetector.hpp.
Referenced by createDetectorSpecificTrackbars(), getRegionAreaThresh(), initialiseDetectorSpecificFields(), isValidRegion(), RegionDetector(), and setRegionAreaThresh().
vector<Region> multiscale::analysis::RegionDetector::regions private
Regions detected in the image
Definition at line 71 of file RegionDetector.hpp.
Referenced by clearPreviousDetectionResults(), getRegions(), outputRegionsToCsvFile(), outputResultsToCsvFile(), outputResultsToImage(), and processImageAndDetect().
int multiscale::analysis::RegionDetector::thresholdValue private
Value of the threshold for the threshold filter
Definition at line 69 of file RegionDetector.hpp.
Referenced by createDetectorSpecificTrackbars(), getThresholdValue(), initialiseDetectorSpecificFields(), RegionDetector(), setThresholdValue(), and thresholdImage().
The documentation for this class was generated from the following files:
include/multiscale/analysis/spatial/RegionDetector.hpp
src/multiscale/analysis/spatial/RegionDetector.cpp