Multiscale: multiscale::analysis::CircularMatFactory Class Reference
multiscale::analysis::CircularMatFactory Class Reference
Class for creating a Mat object considering a circular grid.
#include <CircularMatFactory.hpp>
Public Member Functions
CircularMatFactory ()
~CircularMatFactory ()
Mat createFromViewerImage (const string &inputFile) override
Create a Mat object from the image file obtained from the CircularGeometryViewer.
double maxColourBarIntensityFromViewerImage (const string &inputFile) override
Get the maximum grayscale intensity of the colour bar in the image.
Public Member Functions inherited from multiscale::analysis::MatFactory
MatFactory ()
virtual ~MatFactory ()
Mat create (const string &inputFile)
Create a Mat object from the input file.
Protected Member Functions
unsigned char * processConcentrations (ifstream &fin) override
Process the concentrations from the input file.
bool isValidViewerImage (const Mat &image) override
Check if the image generated by the viewer has the required resolution.
Protected Member Functions inherited from multiscale::analysis::MatFactory
void initInputFile (ifstream &fin, const string &inputFile)
Initialise the input file.
unsigned char convertToIntensity (double concentration)
Convert concentration to intensity.
Private Member Functions
Mat createCircularMask (unsigned int originX, unsigned int originY, unsigned int radius, const Mat &image)
Create a mask with 255 intensity pixels inside the circle with origin at (originX, originY) and the given radius.
Additional Inherited Members
Protected Attributes inherited from multiscale::analysis::MatFactory
int rows
int cols
double simulationTime
Detailed Description
Class for creating a Mat object considering a circular grid.
Definition at line 29 of file CircularMatFactory.hpp.
Constructor & Destructor Documentation
CircularMatFactory::CircularMatFactory ()
Definition at line 9 of file CircularMatFactory.cpp.
CircularMatFactory::~CircularMatFactory ()
Definition at line 11 of file CircularMatFactory.cpp.
Member Function Documentation
Mat CircularMatFactory::createCircularMask (unsigned int originX, unsigned int originY, unsigned int radius, const Mat & image) private
Create a mask with 255 intensity pixels inside the circle with origin at (originX, originY) and the given radius.
All the other pixels have intensity zero.
The original image is provided only for getting the size correctly
Parameters
originX The x coordinate for the origin
originY The y coordinate for the origin
radius The size of the radius
image The original image
Definition at line 44 of file CircularMatFactory.cpp.
References INTENSITY_MAX.
Referenced by createFromViewerImage().
Mat CircularMatFactory::createFromViewerImage (const string & inputFile) override virtual
Create a Mat object from the image file obtained from the CircularGeometryViewer.
Create the Mat instance from the given image file
Parameters
inputFile The path to the image file
Implements multiscale::analysis::MatFactory.
Definition at line 13 of file CircularMatFactory.cpp.
References createCircularMask(), isValidViewerImage(), ROI_RADIUS, ROI_START_X, and ROI_START_Y.
Referenced by main().
bool CircularMatFactory::isValidViewerImage (const Mat & image) override protected virtual
Check if the image generated by the viewer has the required resolution.
Parameters
image Image generated by the viewer
Implements multiscale::analysis::MatFactory.
Definition at line 53 of file CircularMatFactory.cpp.
References ERR_IMG_RESOLUTION, ERR_INPUT_OPEN, INPUT_IMG_HEIGHT, and INPUT_IMG_WIDTH.
Referenced by createFromViewerImage(), and maxColourBarIntensityFromViewerImage().
double CircularMatFactory::maxColourBarIntensityFromViewerImage (const string & inputFile) override virtual
Get the maximum grayscale intensity of the colour bar in the image.
Parameters
inputFile The path to the image file
Implements multiscale::analysis::MatFactory.
Definition at line 32 of file CircularMatFactory.cpp.
References COLOURBAR_MAX_X, COLOURBAR_MAX_Y, and isValidViewerImage().
unsigned char * CircularMatFactory::processConcentrations (ifstream & fin) override protected virtual
Process the concentrations from the input file.
REMARK: This method is not implemented and throws an error when called.
Parameters
fin Input file stream from which the concentrations are read
Implements multiscale::analysis::MatFactory.
Definition at line 40 of file CircularMatFactory.cpp.
References ERR_UNIMPLEMENTED_METHOD.
The documentation for this class was generated from the following files:
include/multiscale/analysis/spatial/factory/CircularMatFactory.hpp
src/multiscale/analysis/spatial/factory/CircularMatFactory.cpp