Multiscale: multiscale::StringManipulator Class Reference
multiscale::StringManipulator Class Reference
Class for manipulating strings.
#include <StringManipulator.hpp>
Static Public Member Functions
static string filenameFromPath (const string &filepath)
Obtain the file name from the given file path.
static string replace (const string &initialString, const string &replaceWhat, const string &replaceTo)
Replace a substring of the given string with another string.
static vector< string > split (const string &initialString, const string &delimiter)
Split the given string into a vector of strings considering the given delimiter.
template<class T >
static string toString (T variable)
Convert the variable to a string.
Detailed Description
Class for manipulating strings.
Definition at line 15 of file StringManipulator.hpp.
Member Function Documentation
string StringManipulator::filenameFromPath (const string & filepath) static
Obtain the file name from the given file path.
Parameters
filepath File path
Definition at line 9 of file StringManipulator.cpp.
References DIR_SEPARATOR.
Referenced by multiscale::video::PolarGnuplotScriptGenerator::generateHeader(), and multiscale::video::RectangularGnuplotScriptGenerator::generateHeader().
string StringManipulator::replace (const string & initialString, const string & replaceWhat, const string & replaceTo) static
Replace a substring of the given string with another string.
Parameters
initialString Initial string
replaceWhat Substring which will be replaced
replaceTo String which will be inserted instead of the replaceWhat string
Definition at line 19 of file StringManipulator.cpp.
Referenced by multiscale::video::PolarGnuplotScriptGenerator::outputContent(), multiscale::video::PolarGnuplotScriptGenerator::outputHeader(), and multiscale::video::RectangularGnuplotScriptGenerator::outputHeader().
vector< string > StringManipulator::split (const string & initialString, const string & delimiter) static
Split the given string into a vector of strings considering the given delimiter.
Parameters
initialString Initial string
delimiter Delimiter
Definition at line 32 of file StringManipulator.cpp.
Referenced by multiscale::video::RectangularCsvToInputFilesConverter::splitLineInConcentrations(), multiscale::video::PolarCsvToInputFilesConverter::splitLineInConcentrations(), multiscale::video::RectangularEntityCsvToInputFilesConverter::splitLineInCoordinates(), multiscale::video::RectangularEntityCsvToInputFilesConverter::validateInputLine(), multiscale::video::RectangularCsvToInputFilesConverter::validateInputLine(), and multiscale::video::PolarCsvToInputFilesConverter::validateInputLine().
template<class T > static string multiscale::StringManipulator::toString (T variable) inline static
Convert the variable to a string.
Parameters
variable Variable
Definition at line 47 of file StringManipulator.hpp.
Referenced by multiscale::video::RectangularEntityCsvToInputFilesConverter::initOutputFile(), multiscale::video::RectangularCsvToInputFilesConverter::initOutputFile(), and multiscale::video::PolarCsvToInputFilesConverter::initOutputFile().
The documentation for this class was generated from the following files:
include/multiscale/util/StringManipulator.hpp
src/multiscale/util/StringManipulator.cpp