Multiscale: multiscale::video::PolarCsvToInputFilesConverter Class Reference
multiscale::video::PolarCsvToInputFilesConverter Class Reference
Csv file to input file converter considering polar coordinates.
#include <PolarCsvToInputFilesConverter.hpp>
Public Member Functions
PolarCsvToInputFilesConverter (const string &inputFilepath, const string &outputFilepath, unsigned int nrOfConcentricCircles, unsigned int nrOfSectors, unsigned int nrOfConcentrationsForPosition, unsigned int selectedConcentrationIndex, bool useLogScaling, NumberIteratorType numberIteratorType)
~PolarCsvToInputFilesConverter ()
void convert ()
Start the conversion.
Private Member Functions
void initInputFile (ifstream &fin)
Initialise the input file stream over the given input file.
void initMaximumConcentration (ifstream &fin)
Compute the value of member maximum concentration.
void initOutputFile (ofstream &fout, unsigned int index, double &simulationTime)
Initialise the output file with the given index and simulation time.
void initIterators (const NumberIteratorType &numberIteratorType)
Initialise the iterators considering the given number iterator type.
void validateSelectedConcentrationIndex ()
Validate the selected concentration index in case of more than one concentration for each position.
void validateInput (ifstream &fin)
Validate the input.
void validateInputLine (const string &line, unsigned int lineNumber)
Validate the provided line identified by a line number.
void processInputFile (ifstream &fin)
Process the input file.
void processLine (const string &line, unsigned int outputIndex)
Process the provided line.
vector< double > splitLineInConcentrations (const string &line, double &simulationTime)
Split the line in concentrations.
void splitFirstPartInConcentrations (vector< double > &concentrations, const vector< string > &tokens, unsigned int circleIndex)
Split first part of the line (i.e. part representing the origin) into concentrations.
void splitOtherPartsInConcentrations (vector< double > &concentrations, const vector< string > &tokens, unsigned int circleIndex)
Split other parts of the line (i.e. non-first part) into concentrations.
double computeSimulationTime (const string &token)
Compute the simulation time from the given token and check if it is valid.
double computeNextPositionConcentration (unsigned int circleIndex, int concentrationIndex, const vector< string > &tokens)
Compute the concentration for the next position.
double computeConcentration (const string &concentration, int circleIndex)
Compute the concentration from the given string considering the index of the current concentric circle.
double computeNonScaledConcentration (const string &concentration, int circleIndex)
Compute the non-scaled concentration from the given string considering the index of the current concentric circle.
double computeScaledConcentration (const string &concentration, int circleIndex)
Compute the scaled concentration from the given string considering the index of the current concentric circle.
double computeConcentrationWrtArea (double amount, int circleIndex)
Compute the concentration wrt. the area of the annular sector.
double computeNormalisedConcentration (double concentration, int circleIndex)
Normalise the concentration considering the index of the current concentric circle by dividing it to the maximum concentration.
void updateMaximumConcentration (const string &line, double &maximumConcentration)
Update the maximum concentration if the values from the given line are greater than it.
Private Attributes
string inputFilepath
string outputFilepath
unsigned int nrOfConcentricCircles
unsigned int nrOfSectors
unsigned int nrOfConcentrationsForPosition
unsigned int concentrationsIndex
unsigned int selectedConcentrationIndex
bool useLogScaling
double maximumConcentration
NumberIterator * circlesIterator
NumberIterator * sectorsIterator
Detailed Description
Csv file to input file converter considering polar coordinates.
Definition at line 33 of file PolarCsvToInputFilesConverter.hpp.
Constructor & Destructor Documentation
PolarCsvToInputFilesConverter::PolarCsvToInputFilesConverter (const string & inputFilepath, const string & outputFilepath, unsigned int nrOfConcentricCircles, unsigned int nrOfSectors, unsigned int nrOfConcentrationsForPosition, unsigned int selectedConcentrationIndex, bool useLogScaling, NumberIteratorType numberIteratorType)
Definition at line 20 of file PolarCsvToInputFilesConverter.cpp.
PolarCsvToInputFilesConverter::~PolarCsvToInputFilesConverter ()
Definition at line 44 of file PolarCsvToInputFilesConverter.cpp.
Member Function Documentation
double PolarCsvToInputFilesConverter::computeConcentration (const string & concentration, int circleIndex) inline private
Compute the concentration from the given string considering the index of the current concentric circle.
Parameters
concentration String representing the concentration
circleIndex Index of the concentric circle
Definition at line 306 of file PolarCsvToInputFilesConverter.cpp.
double PolarCsvToInputFilesConverter::computeConcentrationWrtArea (double amount, int circleIndex) inline private
Compute the concentration wrt. the area of the annular sector.
Parameters
amount Amount in annular sector
circleIndex Index of the concentric circle which will be used to determine the area
Definition at line 332 of file PolarCsvToInputFilesConverter.cpp.
double PolarCsvToInputFilesConverter::computeNextPositionConcentration (unsigned int circleIndex, int concentrationIndex, const vector< string > & tokens) inline private
Compute the concentration for the next position.
Parameters
circleIndex Index of the current concentric circle
concentrationIndex Index of the current concentration from the vector of tokens
tokens Vector of tokens
Definition at line 277 of file PolarCsvToInputFilesConverter.cpp.
double PolarCsvToInputFilesConverter::computeNonScaledConcentration (const string & concentration, int circleIndex) inline private
Compute the non-scaled concentration from the given string considering the index of the current concentric circle.
Parameters
concentration String representing the concentration
circleIndex Index of the concentric circle
Definition at line 312 of file PolarCsvToInputFilesConverter.cpp.
double PolarCsvToInputFilesConverter::computeNormalisedConcentration (double concentration, int circleIndex) inline private
Normalise the concentration considering the index of the current concentric circle by dividing it to the maximum concentration.
Parameters
concentration The concentration
circleIndex Index of the concentric circle
Definition at line 336 of file PolarCsvToInputFilesConverter.cpp.
double PolarCsvToInputFilesConverter::computeScaledConcentration (const string & concentration, int circleIndex) inline private
Compute the scaled concentration from the given string considering the index of the current concentric circle.
Compute the scaled concentration from the given string by applying a logit transformation to it
Parameters
concentration String representing the concentration
circleIndex Index of the concentric circle
Definition at line 318 of file PolarCsvToInputFilesConverter.cpp.
double PolarCsvToInputFilesConverter::computeSimulationTime (const string & token) inline private
Compute the simulation time from the given token and check if it is valid.
Parameters
token Token (string)
Definition at line 267 of file PolarCsvToInputFilesConverter.cpp.
References ERR_NEG_SIM_TIME.
void PolarCsvToInputFilesConverter::convert ()
Start the conversion.
Definition at line 49 of file PolarCsvToInputFilesConverter.cpp.
Referenced by main().
void PolarCsvToInputFilesConverter::initInputFile (ifstream & fin) private
Initialise the input file stream over the given input file.
Parameters
fin Input file stream
Definition at line 62 of file PolarCsvToInputFilesConverter.cpp.
References ERR_INPUT_OPEN.
void PolarCsvToInputFilesConverter::initIterators (const NumberIteratorType & numberIteratorType) private
Initialise the iterators considering the given number iterator type.
Parameters
numberIteratorType The type of the number iterator
Definition at line 111 of file PolarCsvToInputFilesConverter.cpp.
References multiscale::LEXICOGRAPHIC, and multiscale::STANDARD.
void PolarCsvToInputFilesConverter::initMaximumConcentration (ifstream & fin) private
Compute the value of member maximum concentration.
Parameters
fin Input file stream
Definition at line 70 of file PolarCsvToInputFilesConverter.cpp.
References ERR_INPUT_OPEN.
void PolarCsvToInputFilesConverter::initOutputFile (ofstream & fout, unsigned int index, double & simulationTime) private
Initialise the output file with the given index and simulation time.
Parameters
fout Output file stream
index Index of the output file
simulationTime Simulation time
Definition at line 94 of file PolarCsvToInputFilesConverter.cpp.
References OUTPUT_EXTENSION, OUTPUT_FILE_SEPARATOR, OUTPUT_SEPARATOR, and multiscale::StringManipulator::toString().
void PolarCsvToInputFilesConverter::processInputFile (ifstream & fin) private
Process the input file.
Read the concentrations and normalise them if it is the case.
Parameters
fin Input file stream
Definition at line 178 of file PolarCsvToInputFilesConverter.cpp.
void PolarCsvToInputFilesConverter::processLine (const string & line, unsigned int outputIndex) private
Process the provided line.
Parameters
line Line
outputIndex Index integrated in the name of the output file
Definition at line 193 of file PolarCsvToInputFilesConverter.cpp.
References OUTPUT_SEPARATOR.
void PolarCsvToInputFilesConverter::splitFirstPartInConcentrations (vector< double > & concentrations, const vector< string > & tokens, unsigned int circleIndex) private
Split first part of the line (i.e. part representing the origin) into concentrations.
Parameters
concentrations Concentrations extracted from tokens
tokens Tokens representing the line
circleIndex Index of the current concentric circle
Definition at line 237 of file PolarCsvToInputFilesConverter.cpp.
vector< double > PolarCsvToInputFilesConverter::splitLineInConcentrations (const string & line, double & simulationTime) private
Split the line in concentrations.
Parameters
line Line
simulationTime Simulation time associated with the line
Definition at line 212 of file PolarCsvToInputFilesConverter.cpp.
References INPUT_FILE_SEPARATOR, and multiscale::StringManipulator::split().
void PolarCsvToInputFilesConverter::splitOtherPartsInConcentrations (vector< double > & concentrations, const vector< string > & tokens, unsigned int circleIndex) private
Split other parts of the line (i.e. non-first part) into concentrations.
Parameters
concentrations Concentrations extracted from tokens
tokens Tokens representing the line
circleIndex Index of the current concentric circle
Definition at line 251 of file PolarCsvToInputFilesConverter.cpp.
void PolarCsvToInputFilesConverter::updateMaximumConcentration (const string & line, double & maximumConcentration) private
Update the maximum concentration if the values from the given line are greater than it.
Parameters
line Line from input file
maximumConcentration The maximum concentration
Definition at line 340 of file PolarCsvToInputFilesConverter.cpp.
void PolarCsvToInputFilesConverter::validateInput (ifstream & fin) private
Validate the input.
Parameters
fin Input file stream
Definition at line 134 of file PolarCsvToInputFilesConverter.cpp.
References ERR_INPUT_OPEN.
void PolarCsvToInputFilesConverter::validateInputLine (const string & line, unsigned int lineNumber) private
Validate the provided line identified by a line number.
Parameters
line Line from input file
lineNumber Number of the line
Definition at line 158 of file PolarCsvToInputFilesConverter.cpp.
References ERR_INVALID_VALUE_LINE, ERR_INVALID_VALUE_TOKEN, ERR_NR_CONCENTRATIONS, INPUT_FILE_SEPARATOR, and multiscale::StringManipulator::split().
void PolarCsvToInputFilesConverter::validateSelectedConcentrationIndex () private
Validate the selected concentration index in case of more than one concentration for each position.
Definition at line 128 of file PolarCsvToInputFilesConverter.cpp.
References ERR_SELECTED_CONCENTRATION_INDEX.
Member Data Documentation
NumberIterator* multiscale::video::PolarCsvToInputFilesConverter::circlesIterator private
Iterator over the number of concentric circles
Definition at line 57 of file PolarCsvToInputFilesConverter.hpp.
unsigned int multiscale::video::PolarCsvToInputFilesConverter::concentrationsIndex private
Index of the current concentration
Definition at line 44 of file PolarCsvToInputFilesConverter.hpp.
string multiscale::video::PolarCsvToInputFilesConverter::inputFilepath private
Path to the input file
Definition at line 37 of file PolarCsvToInputFilesConverter.hpp.
double multiscale::video::PolarCsvToInputFilesConverter::maximumConcentration private
The maximum concentration in the input file
Definition at line 55 of file PolarCsvToInputFilesConverter.hpp.
unsigned int multiscale::video::PolarCsvToInputFilesConverter::nrOfConcentrationsForPosition private
Number of concentrations for each position
Definition at line 42 of file PolarCsvToInputFilesConverter.hpp.
unsigned int multiscale::video::PolarCsvToInputFilesConverter::nrOfConcentricCircles private
Number of concentric circles
Definition at line 40 of file PolarCsvToInputFilesConverter.hpp.
unsigned int multiscale::video::PolarCsvToInputFilesConverter::nrOfSectors private
Number of sectors
Definition at line 41 of file PolarCsvToInputFilesConverter.hpp.
string multiscale::video::PolarCsvToInputFilesConverter::outputFilepath private
Path to the output file
Definition at line 38 of file PolarCsvToInputFilesConverter.hpp.
NumberIterator* multiscale::video::PolarCsvToInputFilesConverter::sectorsIterator private
Iterator over the number of sectors
Definition at line 58 of file PolarCsvToInputFilesConverter.hpp.
unsigned int multiscale::video::PolarCsvToInputFilesConverter::selectedConcentrationIndex private
    Index of the concentration A in case the number of
concentrations for each position is greater than 1
finalConcentration = A / (A1 + A2 + ... + AN), where N is the number of concentrations for each position
Definition at line 46 of file PolarCsvToInputFilesConverter.hpp.
bool multiscale::video::PolarCsvToInputFilesConverter::useLogScaling private
Flag for using logarithmic scaling for concentrations or not
Definition at line 53 of file PolarCsvToInputFilesConverter.hpp.
The documentation for this class was generated from the following files:
include/multiscale/video/circular/PolarCsvToInputFilesConverter.hpp
src/multiscale/video/circular/PolarCsvToInputFilesConverter.cpp