Multiscale: src/multiscale/video/rectangular/MapCartesianToScript.cpp File Reference
MapCartesianToScript.cpp File Reference
#include "multiscale/video/rectangular/CartesianToConcentrationsConverter.hpp"
#include <boost/program_options.hpp>
#include <iostream>
Macros
#define ERR_CODE 1
#define ERR_MSG "An error occurred: "
Functions
po::variables_map initArgumentsConfig (po::options_description &usageDescription, int argc, char **argv)
void printHelpInformation (const po::variables_map &vm, const po::options_description &usageDescription)
void printWrongParameters ()
bool areValidParameters (string &inputFilepath, string &outputFilename, int argc, char **argv)
int main (int argc, char **argv)
Macro Definition Documentation
#define ERR_CODE 1
Definition at line 32 of file MapCartesianToScript.cpp.
Referenced by main().
#define ERR_MSG "An error occurred: "
Definition at line 33 of file MapCartesianToScript.cpp.
Referenced by main(), and printWrongParameters().
Function Documentation
bool areValidParameters (string & inputFilepath, string & outputFilename, int argc, char ** argv)
Definition at line 60 of file MapCartesianToScript.cpp.
References initArgumentsConfig(), and printHelpInformation().
po::variables_map initArgumentsConfig (po::options_description & usageDescription, int argc, char ** argv)
Definition at line 37 of file MapCartesianToScript.cpp.
int main (int argc, char ** argv)
Definition at line 84 of file MapCartesianToScript.cpp.
References areValidParameters(), multiscale::video::CartesianToConcentrationsConverter::convert(), ERR_CODE, ERR_MSG, and printWrongParameters().
void printHelpInformation (const po::variables_map & vm, const po::options_description & usageDescription)
Definition at line 49 of file MapCartesianToScript.cpp.
void printWrongParameters ()
Definition at line 54 of file MapCartesianToScript.cpp.
References ERR_MSG.