Multiscale: src/multiscale/video/circular/MapCartesianToPolarScript.cpp File Reference
MapCartesianToPolarScript.cpp File Reference
#include "multiscale/video/circular/CartesianToPolarConverter.hpp"
#include <boost/program_options.hpp>
#include <iostream>
Macros
#define ERR_CODE 1
#define ERR_MSG "An error occurred: "
Functions
po::variables_map initArgumentsConfig (po::options_description &usageDescription, int argc, char **argv)
void printHelpInformation (const po::variables_map &vm, const po::options_description &usageDescription)
void printWrongParameters ()
bool isValidOutputType (const po::variables_map &vm, bool &isScript)
bool areValidParameters (string &inputFilepath, string &outputFilename, bool &isScript, int argc, char **argv)
int main (int argc, char **argv)
Macro Definition Documentation
#define ERR_CODE 1
Definition at line 47 of file MapCartesianToPolarScript.cpp.
Referenced by main().
#define ERR_MSG "An error occurred: "
Definition at line 48 of file MapCartesianToPolarScript.cpp.
Referenced by isValidOutputType(), main(), and printWrongParameters().
Function Documentation
bool areValidParameters (string & inputFilepath, string & outputFilename, bool & isScript, int argc, char ** argv)
Definition at line 100 of file MapCartesianToPolarScript.cpp.
References initArgumentsConfig(), isValidOutputType(), and printHelpInformation().
po::variables_map initArgumentsConfig (po::options_description & usageDescription, int argc, char ** argv)
Definition at line 52 of file MapCartesianToPolarScript.cpp.
bool isValidOutputType (const po::variables_map & vm, bool & isScript)
Definition at line 79 of file MapCartesianToPolarScript.cpp.
References ERR_MSG.
Referenced by areValidParameters().
int main (int argc, char ** argv)
Definition at line 126 of file MapCartesianToPolarScript.cpp.
References areValidParameters(), multiscale::video::CartesianToPolarConverter::convert(), ERR_CODE, ERR_MSG, and printWrongParameters().
void printHelpInformation (const po::variables_map & vm, const po::options_description & usageDescription)
Definition at line 68 of file MapCartesianToPolarScript.cpp.
void printWrongParameters ()
Definition at line 73 of file MapCartesianToPolarScript.cpp.
References ERR_MSG.