Multiscale: src/multiscale/video/rectangular/RectangularMapCsvToInputFiles.cpp File Reference
RectangularMapCsvToInputFiles.cpp File Reference
#include "multiscale/video/rectangular/RectangularCsvToInputFilesConverter.hpp"
#include "multiscale/util/iterator/NumberIteratorType.hpp"
#include <boost/program_options.hpp>
#include <iostream>
Macros
#define ERR_CODE 1
#define ERR_MSG "An error occurred: "
Functions
po::variables_map initArgumentsConfig (po::options_description &usageDescription, int argc, char **argv)
void printHelpInformation (const po::variables_map &vm, const po::options_description &usageDescription)
void printWrongParameters ()
void setNumberIteratorType (const po::variables_map &vm, NumberIteratorType &numberIteratorType)
void setSelectedConcentrationIndex (const po::variables_map &vm, unsigned int &selectedConcentrationIndex)
void setLogScaling (const po::variables_map &vm, bool &useLogScaling)
bool isValidNrOfConcentrationsForPosition (const po::variables_map &vm, unsigned int &nrOfConcentrationsForPosition)
bool areValidParameters (string &inputFilepath, string &outputFilename, unsigned int &height, unsigned int &width, unsigned int &nrOfConcentrationsForPosition, unsigned int &selectedConcentrationIndex, bool &useLogScaling, NumberIteratorType &numberIteratorType, int argc, char **argv)
int main (int argc, char **argv)
Macro Definition Documentation
#define ERR_CODE 1
Definition at line 28 of file RectangularMapCsvToInputFiles.cpp.
Referenced by main().
#define ERR_MSG "An error occurred: "
Definition at line 29 of file RectangularMapCsvToInputFiles.cpp.
Referenced by isValidNrOfConcentrationsForPosition(), main(), and printWrongParameters().
Function Documentation
bool areValidParameters (string & inputFilepath, string & outputFilename, unsigned int & height, unsigned int & width, unsigned int & nrOfConcentrationsForPosition, unsigned int & selectedConcentrationIndex, bool & useLogScaling, NumberIteratorType & numberIteratorType, int argc, char ** argv)
Definition at line 92 of file RectangularMapCsvToInputFiles.cpp.
References initArgumentsConfig(), isValidNrOfConcentrationsForPosition(), printHelpInformation(), setLogScaling(), setNumberIteratorType(), and setSelectedConcentrationIndex().
po::variables_map initArgumentsConfig (po::options_description & usageDescription, int argc, char ** argv)
Definition at line 33 of file RectangularMapCsvToInputFiles.cpp.
bool isValidNrOfConcentrationsForPosition (const po::variables_map & vm, unsigned int & nrOfConcentrationsForPosition)
Definition at line 77 of file RectangularMapCsvToInputFiles.cpp.
References ERR_MSG.
int main (int argc, char ** argv)
Definition at line 135 of file RectangularMapCsvToInputFiles.cpp.
References areValidParameters(), multiscale::video::RectangularCsvToInputFilesConverter::convert(), ERR_CODE, ERR_MSG, printWrongParameters(), and multiscale::STANDARD.
void printHelpInformation (const po::variables_map & vm, const po::options_description & usageDescription)
Definition at line 51 of file RectangularMapCsvToInputFiles.cpp.
void printWrongParameters ()
Definition at line 56 of file RectangularMapCsvToInputFiles.cpp.
References ERR_MSG.
void setLogScaling (const po::variables_map & vm, bool & useLogScaling)
Definition at line 72 of file RectangularMapCsvToInputFiles.cpp.
void setNumberIteratorType (const po::variables_map & vm, NumberIteratorType & numberIteratorType)
Definition at line 62 of file RectangularMapCsvToInputFiles.cpp.
References multiscale::LEXICOGRAPHIC.
void setSelectedConcentrationIndex (const po::variables_map & vm, unsigned int & selectedConcentrationIndex)
Definition at line 67 of file RectangularMapCsvToInputFiles.cpp.