Multiscale: src/multiscale/analysis/spatial/RectangularDetectRegions.cpp File Reference
RectangularDetectRegions.cpp File Reference
#include "multiscale/analysis/spatial/RegionDetector.hpp"
#include "multiscale/analysis/spatial/factory/RectangularMatFactory.hpp"
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/xml_parser.hpp>
#include <boost/program_options.hpp>
#include <iostream>
Macros
#define CONFIG_FILE "config/analysis/spatial/rectangular_region_detector.xml"
#define LABEL_ROOT_COMMENT "<xmlcomment>"
#define LABEL_ALPHA "detector.alpha"
#define LABEL_BETA "detector.beta"
#define LABEL_BLUR_KERNEL_SIZE "detector.blurKernelSize"
#define LABEL_MORPHOLOGICAL_CLOSE_ITERATIONS "detector.morphologicalCloseIterations"
#define LABEL_EPSILON "detector.epsilon"
#define LABEL_REGION_AREA_THRESH "detector.regionAreaThresh"
#define LABEL_THRESHOLD_VALUE "detector.thresholdValue"
#define ROOT_COMMENT "Warning! This xml file was automatically generated by a C++ program using the Boost PropertyTree library."
#define ERR_CODE 1
#define ERR_MSG "An error occurred: "
Functions
po::variables_map initArgumentsConfig (po::options_description &usageDescription, int argc, char **argv)
void printHelpInformation (const po::variables_map &vm, const po::options_description &usageDescription)
void printWrongParameters ()
bool areValidParameters (string &inputFilepath, string &outputFilename, bool &debugFlag, int argc, char **argv)
void loadDetectorParameterValues (RegionDetector &detector)
void saveDetectorParameterValues (RegionDetector &detector)
void loadDetectorParameterValues (RegionDetector &detector, bool debugMode)
void saveDetectorParameterValues (RegionDetector &detector, bool debugMode)
int main (int argc, char **argv)
Macro Definition Documentation
#define CONFIG_FILE "config/analysis/spatial/rectangular_region_detector.xml"
Definition at line 30 of file RectangularDetectRegions.cpp.
Referenced by loadDetectorParameterValues(), and saveDetectorParameterValues().
#define ERR_CODE 1
Definition at line 43 of file RectangularDetectRegions.cpp.
Referenced by main().
#define ERR_MSG "An error occurred: "
Definition at line 44 of file RectangularDetectRegions.cpp.
Referenced by main(), and printWrongParameters().
#define LABEL_ALPHA "detector.alpha"
Definition at line 33 of file RectangularDetectRegions.cpp.
Referenced by loadDetectorParameterValues(), and saveDetectorParameterValues().
#define LABEL_BETA "detector.beta"
Definition at line 34 of file RectangularDetectRegions.cpp.
Referenced by loadDetectorParameterValues(), and saveDetectorParameterValues().
#define LABEL_BLUR_KERNEL_SIZE "detector.blurKernelSize"
Definition at line 35 of file RectangularDetectRegions.cpp.
Referenced by loadDetectorParameterValues(), and saveDetectorParameterValues().
#define LABEL_EPSILON "detector.epsilon"
Definition at line 37 of file RectangularDetectRegions.cpp.
Referenced by loadDetectorParameterValues(), and saveDetectorParameterValues().
#define LABEL_MORPHOLOGICAL_CLOSE_ITERATIONS "detector.morphologicalCloseIterations"
Definition at line 36 of file RectangularDetectRegions.cpp.
Referenced by loadDetectorParameterValues(), and saveDetectorParameterValues().
#define LABEL_REGION_AREA_THRESH "detector.regionAreaThresh"
Definition at line 38 of file RectangularDetectRegions.cpp.
Referenced by loadDetectorParameterValues(), and saveDetectorParameterValues().
#define LABEL_ROOT_COMMENT "<xmlcomment>"
Definition at line 32 of file RectangularDetectRegions.cpp.
Referenced by saveDetectorParameterValues().
#define LABEL_THRESHOLD_VALUE "detector.thresholdValue"
Definition at line 39 of file RectangularDetectRegions.cpp.
Referenced by loadDetectorParameterValues(), and saveDetectorParameterValues().
#define ROOT_COMMENT "Warning! This xml file was automatically generated by a C++ program using the Boost PropertyTree library."
Definition at line 41 of file RectangularDetectRegions.cpp.
Referenced by saveDetectorParameterValues().
Function Documentation
bool areValidParameters (string & inputFilepath, string & outputFilename, bool & debugFlag, int argc, char ** argv)
Definition at line 72 of file RectangularDetectRegions.cpp.
References initArgumentsConfig(), and printHelpInformation().
po::variables_map initArgumentsConfig (po::options_description & usageDescription, int argc, char ** argv)
Definition at line 48 of file RectangularDetectRegions.cpp.
void loadDetectorParameterValues (RegionDetector & detector)
Definition at line 100 of file RectangularDetectRegions.cpp.
References CONFIG_FILE, LABEL_ALPHA, LABEL_BETA, LABEL_BLUR_KERNEL_SIZE, LABEL_EPSILON, LABEL_MORPHOLOGICAL_CLOSE_ITERATIONS, LABEL_REGION_AREA_THRESH, LABEL_THRESHOLD_VALUE, multiscale::analysis::RegionDetector::setAlpha(), multiscale::analysis::RegionDetector::setBeta(), multiscale::analysis::RegionDetector::setBlurKernelSize(), multiscale::analysis::RegionDetector::setEpsilon(), multiscale::analysis::RegionDetector::setMorphologicalCloseIterations(), multiscale::analysis::RegionDetector::setRegionAreaThresh(), and multiscale::analysis::RegionDetector::setThresholdValue().
void loadDetectorParameterValues (RegionDetector & detector, bool debugMode)
Definition at line 134 of file RectangularDetectRegions.cpp.
References loadDetectorParameterValues().
int main (int argc, char ** argv)
Definition at line 146 of file RectangularDetectRegions.cpp.
References areValidParameters(), multiscale::analysis::RectangularMatFactory::createFromViewerImage(), multiscale::analysis::Detector::detect(), ERR_CODE, ERR_MSG, loadDetectorParameterValues(), multiscale::analysis::Detector::outputResults(), printWrongParameters(), and saveDetectorParameterValues().
void printHelpInformation (const po::variables_map & vm, const po::options_description & usageDescription)
Definition at line 61 of file RectangularDetectRegions.cpp.
void printWrongParameters ()
Definition at line 66 of file RectangularDetectRegions.cpp.
References ERR_MSG.
void saveDetectorParameterValues (RegionDetector & detector)
Definition at line 115 of file RectangularDetectRegions.cpp.
References CONFIG_FILE, multiscale::analysis::RegionDetector::getAlpha(), multiscale::analysis::RegionDetector::getBeta(), multiscale::analysis::RegionDetector::getBlurKernelSize(), multiscale::analysis::RegionDetector::getEpsilon(), multiscale::analysis::RegionDetector::getMorphologicalCloseIterations(), multiscale::analysis::RegionDetector::getRegionAreaThresh(), multiscale::analysis::RegionDetector::getThresholdValue(), LABEL_ALPHA, LABEL_BETA, LABEL_BLUR_KERNEL_SIZE, LABEL_EPSILON, LABEL_MORPHOLOGICAL_CLOSE_ITERATIONS, LABEL_REGION_AREA_THRESH, LABEL_ROOT_COMMENT, LABEL_THRESHOLD_VALUE, and ROOT_COMMENT.
void saveDetectorParameterValues (RegionDetector & detector, bool debugMode)
Definition at line 139 of file RectangularDetectRegions.cpp.
References saveDetectorParameterValues().