Multiscale: src/multiscale/analysis/spatial/SimulationDetectClusters.cpp File Reference
SimulationDetectClusters.cpp File Reference
#include "multiscale/analysis/spatial/cluster/SimulationClusterDetector.hpp"
#include "multiscale/analysis/spatial/factory/RectangularMatFactory.hpp"
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/xml_parser.hpp>
#include <boost/program_options.hpp>
#include <iostream>
#include <typeinfo>
Macros
#define CONFIG_FILE "config/analysis/spatial/simulation_cluster_detector.xml"
#define LABEL_ROOT_COMMENT "<xmlcomment>"
#define LABEL_EPS "detector.eps"
#define LABEL_MINPOINTS "detector.minPoints"
#define ROOT_COMMENT "Warning! This xml file was automatically generated by a C++ program using the Boost PropertyTree library."
#define ERR_CODE 1
#define ERR_MSG "An error occurred: "
Functions
po::variables_map initArgumentsConfig (po::options_description &usageDescription, int argc, char **argv)
void printHelpInformation (const po::variables_map &vm, const po::options_description &usageDescription)
void printWrongParameters ()
bool areValidParameters (string &inputFilepath, string &outputFilename, bool &debugFlag, unsigned int &height, unsigned int &width, unsigned int &maxPileup, int argc, char **argv)
void loadDetectorParameterValues (SimulationClusterDetector &detector)
void saveDetectorParameterValues (SimulationClusterDetector &detector)
void loadDetectorParameterValues (SimulationClusterDetector &detector, bool debugMode)
void saveDetectorParameterValues (SimulationClusterDetector &detector, bool debugMode)
int main (int argc, char **argv)
Macro Definition Documentation
#define CONFIG_FILE "config/analysis/spatial/simulation_cluster_detector.xml"
Definition at line 31 of file SimulationDetectClusters.cpp.
Referenced by loadDetectorParameterValues(), and saveDetectorParameterValues().
#define ERR_CODE 1
Definition at line 39 of file SimulationDetectClusters.cpp.
Referenced by main().
#define ERR_MSG "An error occurred: "
Definition at line 40 of file SimulationDetectClusters.cpp.
Referenced by main(), and printWrongParameters().
#define LABEL_EPS "detector.eps"
Definition at line 34 of file SimulationDetectClusters.cpp.
Referenced by loadDetectorParameterValues(), and saveDetectorParameterValues().
#define LABEL_MINPOINTS "detector.minPoints"
Definition at line 35 of file SimulationDetectClusters.cpp.
Referenced by loadDetectorParameterValues(), and saveDetectorParameterValues().
#define LABEL_ROOT_COMMENT "<xmlcomment>"
Definition at line 33 of file SimulationDetectClusters.cpp.
Referenced by saveDetectorParameterValues().
#define ROOT_COMMENT "Warning! This xml file was automatically generated by a C++ program using the Boost PropertyTree library."
Definition at line 37 of file SimulationDetectClusters.cpp.
Referenced by saveDetectorParameterValues().
Function Documentation
bool areValidParameters (string & inputFilepath, string & outputFilename, bool & debugFlag, unsigned int & height, unsigned int & width, unsigned int & maxPileup, int argc, char ** argv)
Definition at line 71 of file SimulationDetectClusters.cpp.
References initArgumentsConfig(), and printHelpInformation().
po::variables_map initArgumentsConfig (po::options_description & usageDescription, int argc, char ** argv)
Definition at line 44 of file SimulationDetectClusters.cpp.
void loadDetectorParameterValues (SimulationClusterDetector & detector)
Definition at line 105 of file SimulationDetectClusters.cpp.
References CONFIG_FILE, LABEL_EPS, LABEL_MINPOINTS, multiscale::analysis::ClusterDetector::setEps(), and multiscale::analysis::ClusterDetector::setMinPoints().
void loadDetectorParameterValues (SimulationClusterDetector & detector, bool debugMode)
Definition at line 129 of file SimulationDetectClusters.cpp.
References loadDetectorParameterValues().
int main (int argc, char ** argv)
Definition at line 141 of file SimulationDetectClusters.cpp.
References areValidParameters(), multiscale::analysis::RectangularMatFactory::createFromViewerImage(), multiscale::analysis::Detector::detect(), ERR_CODE, ERR_MSG, loadDetectorParameterValues(), multiscale::analysis::RectangularMatFactory::maxColourBarIntensityFromViewerImage(), multiscale::analysis::Detector::outputResults(), printWrongParameters(), and saveDetectorParameterValues().
void printHelpInformation (const po::variables_map & vm, const po::options_description & usageDescription)
Definition at line 60 of file SimulationDetectClusters.cpp.
void printWrongParameters ()
Definition at line 65 of file SimulationDetectClusters.cpp.
References ERR_MSG.
void saveDetectorParameterValues (SimulationClusterDetector & detector)
Definition at line 115 of file SimulationDetectClusters.cpp.
References CONFIG_FILE, multiscale::analysis::ClusterDetector::getEps(), multiscale::analysis::ClusterDetector::getMinPoints(), LABEL_EPS, LABEL_MINPOINTS, LABEL_ROOT_COMMENT, and ROOT_COMMENT.
void saveDetectorParameterValues (SimulationClusterDetector & detector, bool debugMode)
Definition at line 134 of file SimulationDetectClusters.cpp.
References saveDetectorParameterValues().