.TH "include/multiscale/analysis/spatial Directory Reference" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/multiscale/analysis/spatial Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBfactory\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMatFactory\&.hpp\fP"
.br
.in -1c
