.TH "include/multiscale/video/circular Directory Reference" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/multiscale/video/circular Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAnnularSector\&.hpp\fP"
.br
.ti -1c
.RI "file \fBCartesianToPolarConverter\&.hpp\fP"
.br
.ti -1c
.RI "file \fBPolarCsvToInputFilesConverter\&.hpp\fP"
.br
.ti -1c
.RI "file \fBPolarGnuplotScriptGenerator\&.hpp\fP"
.br
.in -1c
