.TH "include/multiscale/video/circular/AnnularSector.hpp" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/multiscale/video/circular/AnnularSector.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmultiscale::video::AnnularSector\fP"
.br
.RI "\fIAn annular sector is the basic element in the considered circular geometry\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmultiscale\fP"
.br
.ti -1c
.RI "namespace \fBmultiscale::video\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
