.TH "include/multiscale/video/rectangular/CartesianToConcentrationsConverter.hpp" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/multiscale/video/rectangular/CartesianToConcentrationsConverter.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmultiscale::video::CartesianToConcentrationsConverter\fP"
.br
.RI "\fIScale the values of the rectangular geometry grid cells\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmultiscale\fP"
.br
.ti -1c
.RI "namespace \fBmultiscale::video\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBERR_CONC\fP   'All concentrations have to be between 0 and 1\&.'"
.br
.ti -1c
.RI "#define \fBERR_NONPOS_DIMENSION\fP   'The dimensions N and M must be positive\&.'"
.br
.ti -1c
.RI "#define \fBERR_NEG_SIM_TIME\fP   'The simulation time must be non-negative\&.'"
.br
.ti -1c
.RI "#define \fBERR_INPUT_OPEN\fP   'The input file could not be opened'"
.br
.ti -1c
.RI "#define \fBERR_IN_EXTRA_DATA\fP   'The input file contains more data than required\&.'"
.br
.ti -1c
.RI "#define \fBOUTPUT_FILE_EXTENSION\fP   '\&.out'"
.br
.ti -1c
.RI "#define \fBRADIUS_MIN\fP   0\&.001"
.br
.ti -1c
.RI "#define \fBRADIUS_MAX\fP   0\&.3"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ERR_CONC   'All concentrations have to be between 0 and 1\&.'"

.PP
Definition at line 9 of file CartesianToConcentrationsConverter\&.hpp\&.
.SS "#define ERR_IN_EXTRA_DATA   'The input file contains more data than required\&.'"

.PP
Definition at line 13 of file CartesianToConcentrationsConverter\&.hpp\&.
.SS "#define ERR_INPUT_OPEN   'The input file could not be opened'"

.PP
Definition at line 12 of file CartesianToConcentrationsConverter\&.hpp\&.
.SS "#define ERR_NEG_SIM_TIME   'The simulation time must be non-negative\&.'"

.PP
Definition at line 11 of file CartesianToConcentrationsConverter\&.hpp\&.
.SS "#define ERR_NONPOS_DIMENSION   'The dimensions N and M must be positive\&.'"

.PP
Definition at line 10 of file CartesianToConcentrationsConverter\&.hpp\&.
.SS "#define OUTPUT_FILE_EXTENSION   '\&.out'"

.PP
Definition at line 15 of file CartesianToConcentrationsConverter\&.hpp\&.
.SS "#define RADIUS_MAX   0\&.3"

.PP
Definition at line 18 of file CartesianToConcentrationsConverter\&.hpp\&.
.SS "#define RADIUS_MIN   0\&.001"

.PP
Definition at line 17 of file CartesianToConcentrationsConverter\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
