.TH "include/multiscale/analysis/spatial/MatFactory.hpp" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/multiscale/analysis/spatial/MatFactory.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'opencv2/core/core\&.hpp'\fP
.br
\fC#include <fstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmultiscale::analysis::MatFactory\fP"
.br
.RI "\fIClass for creating a Mat object\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmultiscale\fP"
.br
.ti -1c
.RI "namespace \fBmultiscale::analysis\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBERR_INPUT_OPEN\fP   'The input file could not be opened\&.'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ERR_INPUT_OPEN   'The input file could not be opened\&.'"

.PP
Definition at line 10 of file MatFactory\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
