.TH "multiscale::NumericRangeManipulator" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiscale::NumericRangeManipulator \- 
.PP
Operations for ranges of numeric values\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NumericRangeManipulator\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<class T , class U > static U \fBconvertFromRange\fP (T oldRangeMin, T oldRangeMax, U newRangeMin, U newRangeMax, T oldValue)"
.br
.RI "\fIConvert a value from an old range to a new one\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Operations for ranges of numeric values\&. 
.PP
Definition at line 7 of file NumericRangeManipulator\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class T , class U > static U multiscale::NumericRangeManipulator::convertFromRange (ToldRangeMin, ToldRangeMax, UnewRangeMin, UnewRangeMax, ToldValue)\fC [inline]\fP, \fC [static]\fP"

.PP
Convert a value from an old range to a new one\&. \fBParameters:\fP
.RS 4
\fIoldRangeMin\fP The minimum of the old range 
.br
\fIoldRangeMax\fP The maximum of the old range 
.br
\fInewRangeMin\fP The minimum of the new range 
.br
\fInewRangeMax\fP The maximum of the new range 
.br
\fIoldValue\fP The old value 
.RE
.PP

.PP
Definition at line 20 of file NumericRangeManipulator\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
