.TH "multiscale::analysis" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiscale::analysis \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRectangularMatFactory\fP"
.br
.RI "\fIClass for creating a Mat object considering a rectangular grid\&. \fP"
.ti -1c
.RI "class \fBMatFactory\fP"
.br
.RI "\fIClass for creating a Mat object\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
