.TH "multiscale::StandardNumberIterator" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiscale::StandardNumberIterator \- 
.PP
Iterator class starting at 1 and iterating over all natural numbers until the provided upper bound is reached\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StandardNumberIterator\&.hpp>\fP
.PP
Inherits \fBmultiscale::NumberIterator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStandardNumberIterator\fP (unsigned int \fBupperBound\fP)"
.br
.ti -1c
.RI "\fB~StandardNumberIterator\fP ()"
.br
.ti -1c
.RI "unsigned int \fBnumber\fP ()"
.br
.RI "\fIGet the number pointed by the iterator\&. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialise\fP ()"
.br
.RI "\fIInitialise the value of the current number\&. \fP"
.ti -1c
.RI "bool \fBhasNextInitialised\fP ()"
.br
.RI "\fICheck if there is a next number when in initialised state\&. \fP"
.ti -1c
.RI "void \fBresetCurrentNumber\fP ()"
.br
.RI "\fIReset the current number to the initial value\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBcurrentNumber\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Iterator class starting at 1 and iterating over all natural numbers until the provided upper bound is reached\&. 
.PP
Definition at line 10 of file StandardNumberIterator\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "multiscale::StandardNumberIterator::StandardNumberIterator (unsigned intupperBound)"

.SS "multiscale::StandardNumberIterator::~StandardNumberIterator ()"

.SH "Member Function Documentation"
.PP 
.SS "bool multiscale::StandardNumberIterator::hasNextInitialised ()\fC [private]\fP, \fC [virtual]\fP"

.PP
Check if there is a next number when in initialised state\&. 
.PP
Implements \fBmultiscale::NumberIterator\fP\&.
.SS "void multiscale::StandardNumberIterator::initialise ()\fC [private]\fP, \fC [virtual]\fP"

.PP
Initialise the value of the current number\&. 
.PP
Implements \fBmultiscale::NumberIterator\fP\&.
.SS "unsigned int multiscale::StandardNumberIterator::number ()\fC [virtual]\fP"

.PP
Get the number pointed by the iterator\&. 
.PP
Implements \fBmultiscale::NumberIterator\fP\&.
.SS "void multiscale::StandardNumberIterator::resetCurrentNumber ()\fC [private]\fP, \fC [virtual]\fP"

.PP
Reset the current number to the initial value\&. 
.PP
Implements \fBmultiscale::NumberIterator\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned int multiscale::StandardNumberIterator::currentNumber\fC [private]\fP"
The current number 
.PP
Definition at line 14 of file StandardNumberIterator\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
