.TH "multiscale::video::CartesianToConcentrationsConverter" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiscale::video::CartesianToConcentrationsConverter \- 
.PP
Scale the values of the rectangular geometry grid cells\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CartesianToConcentrationsConverter\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCartesianToConcentrationsConverter\fP (const string &\fBinputFilepath\fP, const string &\fBoutputFilepath\fP)"
.br
.ti -1c
.RI "\fB~CartesianToConcentrationsConverter\fP ()"
.br
.ti -1c
.RI "void \fBconvert\fP ()"
.br
.RI "\fIStart the conversion\&. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBreadInputData\fP ()  throw (string)"
.br
.RI "\fIRead the input data\&. \fP"
.ti -1c
.RI "void \fBreadHeaderLine\fP (ifstream &fin)  throw (string)"
.br
.RI "\fIRead the header line\&. \fP"
.ti -1c
.RI "void \fBreadConcentrations\fP (ifstream &fin)  throw (string)"
.br
.RI "\fIRead the concentrations\&. \fP"
.ti -1c
.RI "void \fBoutputResults\fP ()"
.br
.RI "\fIOutput the results\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "vector< double > \fBconcentrations\fP"
.br
.ti -1c
.RI "unsigned long \fBheight\fP"
.br
.ti -1c
.RI "unsigned long \fBwidth\fP"
.br
.ti -1c
.RI "double \fBsimulationTime\fP"
.br
.ti -1c
.RI "string \fBinputFilepath\fP"
.br
.ti -1c
.RI "string \fBoutputFilepath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Scale the values of the rectangular geometry grid cells\&. 
.PP
Definition at line 26 of file CartesianToConcentrationsConverter\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "multiscale::video::CartesianToConcentrationsConverter::CartesianToConcentrationsConverter (const string &inputFilepath, const string &outputFilepath)"

.SS "multiscale::video::CartesianToConcentrationsConverter::~CartesianToConcentrationsConverter ()"

.SH "Member Function Documentation"
.PP 
.SS "void multiscale::video::CartesianToConcentrationsConverter::convert ()"

.PP
Start the conversion\&. 
.SS "void multiscale::video::CartesianToConcentrationsConverter::outputResults ()\fC [private]\fP"

.PP
Output the results\&. 
.SS "void multiscale::video::CartesianToConcentrationsConverter::readConcentrations (ifstream &fin)  throw (string)\fC [private]\fP"

.PP
Read the concentrations\&. \fBParameters:\fP
.RS 4
\fIfin\fP Input file stream 
.RE
.PP

.SS "void multiscale::video::CartesianToConcentrationsConverter::readHeaderLine (ifstream &fin)  throw (string)\fC [private]\fP"

.PP
Read the header line\&. The header line contains values for number of concentric circles, number of sectors and simulation time
.PP
\fBParameters:\fP
.RS 4
\fIfin\fP Input file stream 
.RE
.PP

.SS "void multiscale::video::CartesianToConcentrationsConverter::readInputData ()  throw (string)\fC [private]\fP"

.PP
Read the input data\&. 
.SH "Member Data Documentation"
.PP 
.SS "vector<double> multiscale::video::CartesianToConcentrationsConverter::concentrations\fC [private]\fP"
Concentrations received as input 
.PP
Definition at line 30 of file CartesianToConcentrationsConverter\&.hpp\&.
.SS "unsigned long multiscale::video::CartesianToConcentrationsConverter::height\fC [private]\fP"
Height of the grid 
.PP
Definition at line 32 of file CartesianToConcentrationsConverter\&.hpp\&.
.SS "string multiscale::video::CartesianToConcentrationsConverter::inputFilepath\fC [private]\fP"
Path to the input file 
.PP
Definition at line 36 of file CartesianToConcentrationsConverter\&.hpp\&.
.SS "string multiscale::video::CartesianToConcentrationsConverter::outputFilepath\fC [private]\fP"
Path to the output file 
.PP
Definition at line 37 of file CartesianToConcentrationsConverter\&.hpp\&.
.SS "double multiscale::video::CartesianToConcentrationsConverter::simulationTime\fC [private]\fP"
Simulation time 
.PP
Definition at line 34 of file CartesianToConcentrationsConverter\&.hpp\&.
.SS "unsigned long multiscale::video::CartesianToConcentrationsConverter::width\fC [private]\fP"
Width of the grid 
.PP
Definition at line 33 of file CartesianToConcentrationsConverter\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
