.TH "multiscale::StringManipulator" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiscale::StringManipulator \- 
.PP
Class for manipulating strings\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StringManipulator\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBfilenameFromPath\fP (const string &filepath)"
.br
.RI "\fIObtain the file name from the given file path\&. \fP"
.ti -1c
.RI "static string \fBreplace\fP (const string &initialString, const string &replaceWhat, const string &replaceTo)"
.br
.RI "\fIReplace a substring of the given string with another string\&. \fP"
.ti -1c
.RI "static vector< string > \fBsplit\fP (const string &initialString, const string &delimiter)"
.br
.RI "\fISplit the given string into a vector of strings considering the given delimiter\&. \fP"
.ti -1c
.RI "template<class T > static string \fBtoString\fP (T variable)"
.br
.RI "\fIConvert the variable to a string\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Class for manipulating strings\&. 
.PP
Definition at line 15 of file StringManipulator\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static string multiscale::StringManipulator::filenameFromPath (const string &filepath)\fC [static]\fP"

.PP
Obtain the file name from the given file path\&. \fBParameters:\fP
.RS 4
\fIfilepath\fP File path 
.RE
.PP

.SS "static string multiscale::StringManipulator::replace (const string &initialString, const string &replaceWhat, const string &replaceTo)\fC [static]\fP"

.PP
Replace a substring of the given string with another string\&. \fBParameters:\fP
.RS 4
\fIinitialString\fP Initial string 
.br
\fIreplaceWhat\fP Substring which will be replaced 
.br
\fIreplaceTo\fP String which will be inserted instead of the replaceWhat string 
.RE
.PP

.SS "static vector<string> multiscale::StringManipulator::split (const string &initialString, const string &delimiter)\fC [static]\fP"

.PP
Split the given string into a vector of strings considering the given delimiter\&. \fBParameters:\fP
.RS 4
\fIinitialString\fP Initial string 
.br
\fIdelimiter\fP Delimiter 
.RE
.PP

.SS "template<class T > static string multiscale::StringManipulator::toString (Tvariable)\fC [inline]\fP, \fC [static]\fP"

.PP
Convert the variable to a string\&. \fBParameters:\fP
.RS 4
\fIvariable\fP Variable 
.RE
.PP

.PP
Definition at line 47 of file StringManipulator\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
