.TH "multiscale::video" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiscale::video \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnnularSector\fP"
.br
.RI "\fIAn annular sector is the basic element in the considered circular geometry\&. \fP"
.ti -1c
.RI "class \fBCartesianToPolarConverter\fP"
.br
.RI "\fIConverter from the rectangular geometry grid cells to annular sectors\&. \fP"
.ti -1c
.RI "class \fBPolarCsvToInputFilesConverter\fP"
.br
.RI "\fICsv file to input file converter considering polar coordinates\&. \fP"
.ti -1c
.RI "class \fBPolarGnuplotScriptGenerator\fP"
.br
.RI "\fIGnuplot script generator from the provided annular sectors\&. \fP"
.ti -1c
.RI "class \fBCartesianToConcentrationsConverter\fP"
.br
.RI "\fIScale the values of the rectangular geometry grid cells\&. \fP"
.ti -1c
.RI "class \fBRectangularCsvToInputFilesConverter\fP"
.br
.RI "\fICsv file to input file converter considering cartesian coordinates\&. \fP"
.ti -1c
.RI "class \fBRectangularGnuplotScriptGenerator\fP"
.br
.RI "\fIGnuplot script generator from the provided concentrations considering a rectangular geometry\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
