.TH "multiscale::Geometry2D" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiscale::Geometry2D \- 
.PP
Two-dimensional geometric operations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Geometry2D\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBcomputeDistance\fP (Point a, Point b)"
.br
.RI "\fICompute the distance between two points\&. \fP"
.ti -1c
.RI "double \fBcomputeAngle\fP (Point a, Point b, Point c)"
.br
.RI "\fICompute the angle between three points\&. \fP"
.ti -1c
.RI "vector< Point > \fBfindPointsOnEdge\fP (const vector< Point > &points, unsigned int nrOfRows, unsigned int nrOfCols)"
.br
.RI "\fIFind the subset of points from the given set of points which lie on the edge\&. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "bool \fBisPointOnEdge\fP (Point p, int nrOfRows, int nrOfCols)"
.br
.RI "\fICheck if the given point is on the edge\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "const int \fBMATRIX_START_INDEX\fP = 1"
.br
.ti -1c
.RI "const double \fBPI\fP = 3\&.141592"
.br
.in -1c
.SH "Detailed Description"
.PP 
Two-dimensional geometric operations\&. 
.PP
Definition at line 11 of file Geometry2D\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "double multiscale::Geometry2D::computeAngle (Pointa, Pointb, Pointc)"

.PP
Compute the angle between three points\&. Compute the angle between the lines determined by points A, B and B, C 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Point a 
.br
\fIb\fP Point b 
.br
\fIc\fP Point c 
.RE
.PP

.SS "double multiscale::Geometry2D::computeDistance (Pointa, Pointb)"

.PP
Compute the distance between two points\&. Compute the Euclidean distance between two points 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Point a 
.br
\fIb\fP Point b 
.RE
.PP

.SS "vector<Point> multiscale::Geometry2D::findPointsOnEdge (const vector< Point > &points, unsigned intnrOfRows, unsigned intnrOfCols)"

.PP
Find the subset of points from the given set of points which lie on the edge\&. A point 'p' is considered to be on the edge if: ((p\&.x == 1) && (p\&.y > 1) && (p\&.y < nrOfCols)) OR ((p\&.x == nrOfRows) && (p\&.y > 1) && (p\&.y < nrOfCols)) OR ((p\&.y == 1) && (p\&.x > 1) && (p\&.x < nrOfRows)) OR ((p\&.y == nrOfCols) && (p\&.x > 1) && (p\&.x < nrOfRows))
.PP
\fBParameters:\fP
.RS 4
\fIpoints\fP The set of points 
.br
\fInrOfRows\fP The number of rows 
.br
\fInrOfCols\fP The number of columns 
.RE
.PP

.SS "bool multiscale::Geometry2D::isPointOnEdge (Pointp, intnrOfRows, intnrOfCols)\fC [private]\fP"

.PP
Check if the given point is on the edge\&. A point 'p' is considered to be on the edge if: ((p\&.x == 1) && (p\&.y > 1) && (p\&.y < nrOfCols)) OR ((p\&.x == nrOfRows) && (p\&.y > 1) && (p\&.y < nrOfCols)) OR ((p\&.y == 1) && (p\&.x > 1) && (p\&.x < nrOfRows)) OR ((p\&.y == nrOfCols) && (p\&.x > 1) && (p\&.x < nrOfRows))
.PP
\fBParameters:\fP
.RS 4
\fIp\fP Point p 
.br
\fInrOfRows\fP The number of rows 
.br
\fInrOfCols\fP The number of columns 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "const int multiscale::Geometry2D::MATRIX_START_INDEX = 1\fC [private]\fP"

.PP
Definition at line 15 of file Geometry2D\&.hpp\&.
.SS "const double multiscale::Geometry2D::PI = 3\&.141592\fC [private]\fP"

.PP
Definition at line 16 of file Geometry2D\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
