.TH "multiscale::RGBColourGenerator" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiscale::RGBColourGenerator \- 
.PP
Generate a RGB colour\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGBColourGenerator\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBgenerate\fP (double concentrationMin, double concentrationMax, double concentration)"
.br
.RI "\fIGenerate a RGB colour for the given concentration\&. \fP"
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static string \fBconvertHSVToRGB\fP (double hue, double saturation, double value)"
.br
.RI "\fIConvert a colour from HSV to RGB colour space\&. \fP"
.ti -1c
.RI "static void \fBcomputeRGBValues\fP (int huePrime, double X, double chroma, double m)"
.br
.RI "\fICompute RGB values from HSV specific values\&. \fP"
.ti -1c
.RI "static string \fBconvertRGBToString\fP ()"
.br
.RI "\fIConvert the RGB colour to a string\&. \fP"
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static double \fBred\fP"
.br
.ti -1c
.RI "static double \fBgreen\fP"
.br
.ti -1c
.RI "static double \fBblue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generate a RGB colour\&. 

Generate a RGB colour given the possible range for concentrations and the value of one of the concentrations
.PP
The conversion HSV->RGB is based on the wikipedia page on this topic 
.PP
Definition at line 22 of file RGBColourGenerator\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static void multiscale::RGBColourGenerator::computeRGBValues (inthuePrime, doubleX, doublechroma, doublem)\fC [static]\fP, \fC [private]\fP"

.PP
Compute RGB values from HSV specific values\&. \fBParameters:\fP
.RS 4
\fIhuePrime\fP Hue' 
.br
\fIX\fP X 
.br
\fIchroma\fP Chroma 
.br
\fIm\fP m 
.RE
.PP

.SS "static string multiscale::RGBColourGenerator::convertHSVToRGB (doublehue, doublesaturation, doublevalue)\fC [static]\fP, \fC [private]\fP"

.PP
Convert a colour from HSV to RGB colour space\&. \fBParameters:\fP
.RS 4
\fIhue\fP Hue 
.br
\fIsaturation\fP Saturation 
.br
\fIvalue\fP Value 
.RE
.PP

.SS "static string multiscale::RGBColourGenerator::convertRGBToString ()\fC [static]\fP, \fC [private]\fP"

.PP
Convert the RGB colour to a string\&. 
.SS "static string multiscale::RGBColourGenerator::generate (doubleconcentrationMin, doubleconcentrationMax, doubleconcentration)\fC [static]\fP"

.PP
Generate a RGB colour for the given concentration\&. Generate a RGB colour considering the range of values a concentration can have and the value of the concentration
.PP
\fBParameters:\fP
.RS 4
\fIconcentrationMin\fP The minimum of the range of values a concentration can take 
.br
\fIconcentrationMax\fP The maximum of the range of values a concentration can take 
.br
\fIconcentration\fP The concentration 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "double multiscale::RGBColourGenerator::blue\fC [static]\fP, \fC [private]\fP"
The amount of blue 
.PP
Definition at line 28 of file RGBColourGenerator\&.hpp\&.
.SS "double multiscale::RGBColourGenerator::green\fC [static]\fP, \fC [private]\fP"
The amount of green 
.PP
Definition at line 27 of file RGBColourGenerator\&.hpp\&.
.SS "double multiscale::RGBColourGenerator::red\fC [static]\fP, \fC [private]\fP"
The amount of red 
.PP
Definition at line 26 of file RGBColourGenerator\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
