.TH "multiscale::video::RectangularCsvToInputFilesConverter" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiscale::video::RectangularCsvToInputFilesConverter \- 
.PP
Csv file to input file converter considering cartesian coordinates\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RectangularCsvToInputFilesConverter\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRectangularCsvToInputFilesConverter\fP (const string &\fBinputFilepath\fP, const string &\fBoutputFilepath\fP, unsigned int \fBheight\fP, unsigned int \fBwidth\fP, unsigned int \fBnrOfConcentrationsForPosition\fP, unsigned int \fBselectedConcentrationIndex\fP, \fBNumberIteratorType\fP numberIteratorType)"
.br
.ti -1c
.RI "\fB~RectangularCsvToInputFilesConverter\fP ()"
.br
.ti -1c
.RI "void \fBconvert\fP ()"
.br
.RI "\fIStart the conversion\&. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitInputFile\fP (ifstream &fin)"
.br
.RI "\fIInitialise the input file stream over the given input file\&. \fP"
.ti -1c
.RI "void \fBinitMaximumConcentration\fP (ifstream &fin)"
.br
.RI "\fICompute the value of member maximum concentration\&. \fP"
.ti -1c
.RI "void \fBinitOutputFile\fP (ofstream &fout, unsigned int index, double &simulationTime)"
.br
.RI "\fIInitialise the output file with the given index and simulation time\&. \fP"
.ti -1c
.RI "void \fBinitIterators\fP (const \fBNumberIteratorType\fP &numberIteratorType)"
.br
.RI "\fIInitialise the iterators considering the given number iterator type\&. \fP"
.ti -1c
.RI "void \fBvalidateSelectedConcentrationIndex\fP ()"
.br
.RI "\fIValidate the selected concentration index in case of more than one concentration for each position\&. \fP"
.ti -1c
.RI "void \fBvalidateInput\fP (ifstream &fin)"
.br
.RI "\fIValidate the input\&. \fP"
.ti -1c
.RI "void \fBvalidateInputLine\fP (const string &line, unsigned int lineNumber)"
.br
.RI "\fIValidate the provided line identified by a line number\&. \fP"
.ti -1c
.RI "void \fBprocessInputFile\fP (ifstream &fin)"
.br
.RI "\fIProcess the input file\&. \fP"
.ti -1c
.RI "void \fBprocessLine\fP (const string &line, unsigned int outputIndex)"
.br
.RI "\fIProcess the provided line\&. \fP"
.ti -1c
.RI "vector< double > \fBsplitLineInConcentrations\fP (const string &line, double &simulationTime)"
.br
.RI "\fISplit the line in concentrations\&. \fP"
.ti -1c
.RI "void \fBsplitLineInConcentrations\fP (vector< double > &concentrations, vector< string > &tokens, unsigned int rowIndex)"
.br
.RI "\fISplit line into concentrations\&. \fP"
.ti -1c
.RI "double \fBcomputeSimulationTime\fP (const string &token)"
.br
.RI "\fICompute the simulation time from the given token and check if it is valid\&. \fP"
.ti -1c
.RI "double \fBcomputeNextPositionConcentration\fP (int concentrationIndex, vector< string > &tokens)"
.br
.RI "\fICompute the concentration for the next position\&. \fP"
.ti -1c
.RI "double \fBcomputeConcentration\fP (const string &concentration)"
.br
.RI "\fICompute the concentration from the given string\&. \fP"
.ti -1c
.RI "double \fBcomputeNonScaledConcentration\fP (const string &concentration)"
.br
.RI "\fICompute the non-scaled concentration from the given string\&. \fP"
.ti -1c
.RI "double \fBcomputeScaledConcentration\fP (const string &concentration)"
.br
.RI "\fICompute the scaled concentration from the given string\&. \fP"
.ti -1c
.RI "double \fBcomputeNormalisedConcentration\fP (double concentration)"
.br
.RI "\fINormalise the given concentration by dividing it to the maximum concentration\&. \fP"
.ti -1c
.RI "void \fBupdateMaximumConcentration\fP (const string &line, double &\fBmaximumConcentration\fP)"
.br
.RI "\fIUpdate the maximum concentration if the values from the given line are greater than it\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "string \fBinputFilepath\fP"
.br
.ti -1c
.RI "string \fBoutputFilepath\fP"
.br
.ti -1c
.RI "unsigned int \fBheight\fP"
.br
.ti -1c
.RI "unsigned int \fBwidth\fP"
.br
.ti -1c
.RI "unsigned int \fBnrOfConcentrationsForPosition\fP"
.br
.ti -1c
.RI "unsigned int \fBconcentrationsIndex\fP"
.br
.ti -1c
.RI "unsigned int \fBselectedConcentrationIndex\fP"
.br
.ti -1c
.RI "double \fBmaximumConcentration\fP"
.br
.ti -1c
.RI "\fBNumberIterator\fP * \fBrowsIterator\fP"
.br
.ti -1c
.RI "\fBNumberIterator\fP * \fBcolumnsIterator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Csv file to input file converter considering cartesian coordinates\&. 
.PP
Definition at line 31 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "multiscale::video::RectangularCsvToInputFilesConverter::RectangularCsvToInputFilesConverter (const string &inputFilepath, const string &outputFilepath, unsigned intheight, unsigned intwidth, unsigned intnrOfConcentrationsForPosition, unsigned intselectedConcentrationIndex, \fBNumberIteratorType\fPnumberIteratorType)"

.SS "multiscale::video::RectangularCsvToInputFilesConverter::~RectangularCsvToInputFilesConverter ()"

.SH "Member Function Documentation"
.PP 
.SS "double multiscale::video::RectangularCsvToInputFilesConverter::computeConcentration (const string &concentration)\fC [private]\fP"

.PP
Compute the concentration from the given string\&. \fBParameters:\fP
.RS 4
\fIconcentration\fP String representing the concentration 
.RE
.PP

.SS "double multiscale::video::RectangularCsvToInputFilesConverter::computeNextPositionConcentration (intconcentrationIndex, vector< string > &tokens)\fC [private]\fP"

.PP
Compute the concentration for the next position\&. \fBParameters:\fP
.RS 4
\fIconcentrationIndex\fP Index of the current concentration from the vector of tokens 
.br
\fItokens\fP Vector of tokens 
.RE
.PP

.SS "double multiscale::video::RectangularCsvToInputFilesConverter::computeNonScaledConcentration (const string &concentration)\fC [private]\fP"

.PP
Compute the non-scaled concentration from the given string\&. \fBParameters:\fP
.RS 4
\fIconcentration\fP String representing the concentration 
.RE
.PP

.SS "double multiscale::video::RectangularCsvToInputFilesConverter::computeNormalisedConcentration (doubleconcentration)\fC [private]\fP"

.PP
Normalise the given concentration by dividing it to the maximum concentration\&. \fBParameters:\fP
.RS 4
\fIconcentration\fP The concentration 
.RE
.PP

.SS "double multiscale::video::RectangularCsvToInputFilesConverter::computeScaledConcentration (const string &concentration)\fC [private]\fP"

.PP
Compute the scaled concentration from the given string\&. Compute the scaled concentration from the given string by applying a logit transformation to it
.PP
\fBParameters:\fP
.RS 4
\fIconcentration\fP String representing the concentration 
.RE
.PP

.SS "double multiscale::video::RectangularCsvToInputFilesConverter::computeSimulationTime (const string &token)\fC [private]\fP"

.PP
Compute the simulation time from the given token and check if it is valid\&. \fBParameters:\fP
.RS 4
\fItoken\fP Token (string) 
.RE
.PP

.SS "void multiscale::video::RectangularCsvToInputFilesConverter::convert ()"

.PP
Start the conversion\&. 
.SS "void multiscale::video::RectangularCsvToInputFilesConverter::initInputFile (ifstream &fin)\fC [private]\fP"

.PP
Initialise the input file stream over the given input file\&. \fBParameters:\fP
.RS 4
\fIfin\fP Input file stream 
.RE
.PP

.SS "void multiscale::video::RectangularCsvToInputFilesConverter::initIterators (const \fBNumberIteratorType\fP &numberIteratorType)\fC [private]\fP"

.PP
Initialise the iterators considering the given number iterator type\&. \fBParameters:\fP
.RS 4
\fInumberIteratorType\fP The type of the number iterator 
.RE
.PP

.SS "void multiscale::video::RectangularCsvToInputFilesConverter::initMaximumConcentration (ifstream &fin)\fC [private]\fP"

.PP
Compute the value of member maximum concentration\&. \fBParameters:\fP
.RS 4
\fIfin\fP Input file stream 
.RE
.PP

.SS "void multiscale::video::RectangularCsvToInputFilesConverter::initOutputFile (ofstream &fout, unsigned intindex, double &simulationTime)\fC [private]\fP"

.PP
Initialise the output file with the given index and simulation time\&. \fBParameters:\fP
.RS 4
\fIfout\fP Output file stream 
.br
\fIindex\fP Index of the output file 
.br
\fIsimulationTime\fP Simulation time 
.RE
.PP

.SS "void multiscale::video::RectangularCsvToInputFilesConverter::processInputFile (ifstream &fin)\fC [private]\fP"

.PP
Process the input file\&. Read the concentrations and normalise them if it is the case\&.
.PP
\fBParameters:\fP
.RS 4
\fIfin\fP Input file stream 
.RE
.PP

.SS "void multiscale::video::RectangularCsvToInputFilesConverter::processLine (const string &line, unsigned intoutputIndex)\fC [private]\fP"

.PP
Process the provided line\&. \fBParameters:\fP
.RS 4
\fIline\fP Line 
.br
\fIoutputIndex\fP Index integrated in the name of the output file 
.RE
.PP

.SS "vector<double> multiscale::video::RectangularCsvToInputFilesConverter::splitLineInConcentrations (const string &line, double &simulationTime)\fC [private]\fP"

.PP
Split the line in concentrations\&. \fBParameters:\fP
.RS 4
\fIline\fP Line 
.br
\fIsimulationTime\fP Simulation time associated with the line 
.RE
.PP

.SS "void multiscale::video::RectangularCsvToInputFilesConverter::splitLineInConcentrations (vector< double > &concentrations, vector< string > &tokens, unsigned introwIndex)\fC [private]\fP"

.PP
Split line into concentrations\&. \fBParameters:\fP
.RS 4
\fIconcentrations\fP Concentrations extracted from tokens 
.br
\fItokens\fP Tokens representing the line 
.br
\fIrowIndex\fP Index of the current row 
.RE
.PP

.SS "void multiscale::video::RectangularCsvToInputFilesConverter::updateMaximumConcentration (const string &line, double &maximumConcentration)\fC [private]\fP"

.PP
Update the maximum concentration if the values from the given line are greater than it\&. \fBParameters:\fP
.RS 4
\fIline\fP Line from input file 
.br
\fImaximumConcentration\fP The maximum concentration 
.RE
.PP

.SS "void multiscale::video::RectangularCsvToInputFilesConverter::validateInput (ifstream &fin)\fC [private]\fP"

.PP
Validate the input\&. \fBParameters:\fP
.RS 4
\fIfin\fP Input file stream 
.RE
.PP

.SS "void multiscale::video::RectangularCsvToInputFilesConverter::validateInputLine (const string &line, unsigned intlineNumber)\fC [private]\fP"

.PP
Validate the provided line identified by a line number\&. \fBParameters:\fP
.RS 4
\fIline\fP Line from input file 
.br
\fIlineNumber\fP Number of the line 
.RE
.PP

.SS "void multiscale::video::RectangularCsvToInputFilesConverter::validateSelectedConcentrationIndex ()\fC [private]\fP"

.PP
Validate the selected concentration index in case of more than one concentration for each position\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBNumberIterator\fP* multiscale::video::RectangularCsvToInputFilesConverter::columnsIterator\fC [private]\fP"
Iterator over the number of columns 
.PP
Definition at line 54 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SS "unsigned int multiscale::video::RectangularCsvToInputFilesConverter::concentrationsIndex\fC [private]\fP"
Index of the current concentration 
.PP
Definition at line 42 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SS "unsigned int multiscale::video::RectangularCsvToInputFilesConverter::height\fC [private]\fP"
Height of the grid 
.PP
Definition at line 38 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SS "string multiscale::video::RectangularCsvToInputFilesConverter::inputFilepath\fC [private]\fP"
Path to the input file 
.PP
Definition at line 35 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SS "double multiscale::video::RectangularCsvToInputFilesConverter::maximumConcentration\fC [private]\fP"
The maximum concentration in the input file 
.PP
Definition at line 51 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SS "unsigned int multiscale::video::RectangularCsvToInputFilesConverter::nrOfConcentrationsForPosition\fC [private]\fP"
Number of concentrations for each position 
.PP
Definition at line 40 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SS "string multiscale::video::RectangularCsvToInputFilesConverter::outputFilepath\fC [private]\fP"
Path to the output file 
.PP
Definition at line 36 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SS "\fBNumberIterator\fP* multiscale::video::RectangularCsvToInputFilesConverter::rowsIterator\fC [private]\fP"
Iterator over the number of rows 
.PP
Definition at line 53 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SS "unsigned int multiscale::video::RectangularCsvToInputFilesConverter::selectedConcentrationIndex\fC [private]\fP"
.PP
.nf
    Index of the concentration A in case the number of
.fi
.PP
 concentrations for each position is greater than 1
.PP
finalConcentration = A / (A1 + A2 + \&.\&.\&. + AN), where N is the number of concentrations for each position 
.PP
Definition at line 44 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SS "unsigned int multiscale::video::RectangularCsvToInputFilesConverter::width\fC [private]\fP"
Width of the grid 
.PP
Definition at line 39 of file RectangularCsvToInputFilesConverter\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
