.TH "multiscale::video::RectangularGnuplotScriptGenerator" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiscale::video::RectangularGnuplotScriptGenerator \- 
.PP
Gnuplot script generator from the provided concentrations considering a rectangular geometry\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RectangularGnuplotScriptGenerator\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBgenerateScript\fP (const vector< double > &concentrations, double simulationTime, unsigned long height, unsigned long width, const string &outputFilepath)  throw (string)"
.br
.RI "\fIGenerate the script\&. \fP"
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static void \fBgenerateHeader\fP (ofstream &fout, const string &outputFilepath, double simulationTime, unsigned long height, unsigned long width)"
.br
.RI "\fIGenerate the header of the script\&. \fP"
.ti -1c
.RI "static void \fBgenerateBody\fP (const vector< double > &concentrations, unsigned long height, unsigned long width, ofstream &fout)"
.br
.RI "\fIGenerate the body/content of the script\&. \fP"
.ti -1c
.RI "static void \fBgenerateFooter\fP (ofstream &fout)"
.br
.RI "\fIGenerate the footer of the script\&. \fP"
.ti -1c
.RI "static void \fBoutputHeader\fP (ifstream &fin, const string &outputFilename, double simulationTime, unsigned long height, unsigned long width, ofstream &fout)"
.br
.RI "\fIOutput the header of the script\&. \fP"
.ti -1c
.RI "static void \fBoutputContent\fP (const vector< double > &concentrations, unsigned long height, unsigned long width, ofstream &fout)"
.br
.RI "\fIOutput the content of the script\&. \fP"
.ti -1c
.RI "static void \fBoutputFooter\fP (ifstream &fin, ofstream &fout)"
.br
.RI "\fIOutput the footer of the script\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Gnuplot script generator from the provided concentrations considering a rectangular geometry\&. 
.PP
Definition at line 30 of file RectangularGnuplotScriptGenerator\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static void multiscale::video::RectangularGnuplotScriptGenerator::generateBody (const vector< double > &concentrations, unsigned longheight, unsigned longwidth, ofstream &fout)\fC [static]\fP, \fC [private]\fP"

.PP
Generate the body/content of the script\&. \fBParameters:\fP
.RS 4
\fIconcentrations\fP The concentrations 
.br
\fIheight\fP The height of the grid 
.br
\fIwidth\fP The width of the grid 
.br
\fIfout\fP Output file stream 
.RE
.PP

.SS "static void multiscale::video::RectangularGnuplotScriptGenerator::generateFooter (ofstream &fout)\fC [static]\fP, \fC [private]\fP"

.PP
Generate the footer of the script\&. \fBParameters:\fP
.RS 4
\fIfout\fP Output file stream 
.RE
.PP

.SS "static void multiscale::video::RectangularGnuplotScriptGenerator::generateHeader (ofstream &fout, const string &outputFilepath, doublesimulationTime, unsigned longheight, unsigned longwidth)\fC [static]\fP, \fC [private]\fP"

.PP
Generate the header of the script\&. \fBParameters:\fP
.RS 4
\fIfout\fP Output file stream 
.br
\fIoutputFilepath\fP Path to the output file 
.br
\fIsimulationTime\fP Simulation time 
.br
\fIheight\fP Height of the grid 
.br
\fIwidth\fP Width of the grid 
.RE
.PP

.SS "static void multiscale::video::RectangularGnuplotScriptGenerator::generateScript (const vector< double > &concentrations, doublesimulationTime, unsigned longheight, unsigned longwidth, const string &outputFilepath)  throw (string)\fC [static]\fP"

.PP
Generate the script\&. \fBParameters:\fP
.RS 4
\fIconcentrations\fP Concentrations 
.br
\fIsimulationTime\fP Simulation time 
.br
\fIheight\fP Height of the grid 
.br
\fIwidth\fP Width of the grid 
.br
\fIoutputFilepath\fP Path of the output file 
.RE
.PP

.SS "static void multiscale::video::RectangularGnuplotScriptGenerator::outputContent (const vector< double > &concentrations, unsigned longheight, unsigned longwidth, ofstream &fout)\fC [static]\fP, \fC [private]\fP"

.PP
Output the content of the script\&. \fBParameters:\fP
.RS 4
\fIconcentrations\fP The concentrations 
.br
\fIheight\fP The height of the grid 
.br
\fIwidth\fP The width of the grid 
.br
\fIfout\fP Output file stream 
.RE
.PP

.SS "static void multiscale::video::RectangularGnuplotScriptGenerator::outputFooter (ifstream &fin, ofstream &fout)\fC [static]\fP, \fC [private]\fP"

.PP
Output the footer of the script\&. \fBParameters:\fP
.RS 4
\fIfin\fP Input file stream 
.br
\fIfout\fP Output file stream 
.RE
.PP

.SS "static void multiscale::video::RectangularGnuplotScriptGenerator::outputHeader (ifstream &fin, const string &outputFilename, doublesimulationTime, unsigned longheight, unsigned longwidth, ofstream &fout)\fC [static]\fP, \fC [private]\fP"

.PP
Output the header of the script\&. \fBParameters:\fP
.RS 4
\fIfin\fP Input file stream 
.br
\fIoutputFilename\fP Name of the output file 
.br
\fIsimulationTime\fP Simulation time 
.br
\fIheight\fP The height of the grid 
.br
\fIwidth\fP The width of the grid 
.br
\fIfout\fP Output file stream 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
