.TH "include/multiscale/util/iterator/NumberIteratorType.hpp" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/multiscale/util/iterator/NumberIteratorType.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmultiscale\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBmultiscale::NumberIteratorType\fP { \fBmultiscale::STANDARD\fP = 1, \fBmultiscale::LEXICOGRAPHIC\fP = 2 }"
.br
.RI "\fIThe type of the number iterator\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
