.TH "include/multiscale/video/circular/PolarGnuplotScriptGenerator.hpp" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/multiscale/video/circular/PolarGnuplotScriptGenerator.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'multiscale/video/circular/AnnularSector\&.hpp'\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmultiscale::video::PolarGnuplotScriptGenerator\fP"
.br
.RI "\fIGnuplot script generator from the provided annular sectors\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmultiscale\fP"
.br
.ti -1c
.RI "namespace \fBmultiscale::video\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHEADER_IN\fP   'config/video/circular/header\&.in'"
.br
.ti -1c
.RI "#define \fBCONTENT_IN\fP   'config/video/circular/content\&.in'"
.br
.ti -1c
.RI "#define \fBFOOTER_IN\fP   'config/video/circular/footer\&.in'"
.br
.ti -1c
.RI "#define \fBREPLACE_HEADER_FILENAME\fP   'OUTPUT_FILENAME'"
.br
.ti -1c
.RI "#define \fBREPLACE_HEADER_SIM_TIME\fP   'OUTPUT_SIM_TIME'"
.br
.ti -1c
.RI "#define \fBREPLACE_CONTENT_INDEX\fP   'OBJ_INDEX'"
.br
.ti -1c
.RI "#define \fBREPLACE_CONTENT_RADIUS\fP   'OBJ_END_RADIUS'"
.br
.ti -1c
.RI "#define \fBREPLACE_CONTENT_START_ANGLE\fP   'OBJ_START_ANGLE'"
.br
.ti -1c
.RI "#define \fBREPLACE_CONTENT_END_ANGLE\fP   'OBJ_END_ANGLE'"
.br
.ti -1c
.RI "#define \fBREPLACE_CONTENT_CONCENTRATION\fP   'OBJ_CONCENTRATION'"
.br
.ti -1c
.RI "#define \fBGNUPLOT_EXTENSION\fP   '\&.plt'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CONTENT_IN   'config/video/circular/content\&.in'"

.PP
Definition at line 11 of file PolarGnuplotScriptGenerator\&.hpp\&.
.SS "#define FOOTER_IN   'config/video/circular/footer\&.in'"

.PP
Definition at line 12 of file PolarGnuplotScriptGenerator\&.hpp\&.
.SS "#define GNUPLOT_EXTENSION   '\&.plt'"

.PP
Definition at line 23 of file PolarGnuplotScriptGenerator\&.hpp\&.
.SS "#define HEADER_IN   'config/video/circular/header\&.in'"

.PP
Definition at line 10 of file PolarGnuplotScriptGenerator\&.hpp\&.
.SS "#define REPLACE_CONTENT_CONCENTRATION   'OBJ_CONCENTRATION'"

.PP
Definition at line 21 of file PolarGnuplotScriptGenerator\&.hpp\&.
.SS "#define REPLACE_CONTENT_END_ANGLE   'OBJ_END_ANGLE'"

.PP
Definition at line 20 of file PolarGnuplotScriptGenerator\&.hpp\&.
.SS "#define REPLACE_CONTENT_INDEX   'OBJ_INDEX'"

.PP
Definition at line 17 of file PolarGnuplotScriptGenerator\&.hpp\&.
.SS "#define REPLACE_CONTENT_RADIUS   'OBJ_END_RADIUS'"

.PP
Definition at line 18 of file PolarGnuplotScriptGenerator\&.hpp\&.
.SS "#define REPLACE_CONTENT_START_ANGLE   'OBJ_START_ANGLE'"

.PP
Definition at line 19 of file PolarGnuplotScriptGenerator\&.hpp\&.
.SS "#define REPLACE_HEADER_FILENAME   'OUTPUT_FILENAME'"

.PP
Definition at line 14 of file PolarGnuplotScriptGenerator\&.hpp\&.
.SS "#define REPLACE_HEADER_SIM_TIME   'OUTPUT_SIM_TIME'"

.PP
Definition at line 15 of file PolarGnuplotScriptGenerator\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
