.TH "include/multiscale/video/rectangular/RectangularCsvToInputFilesConverter.hpp" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/multiscale/video/rectangular/RectangularCsvToInputFilesConverter.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'multiscale/util/NumberIterator\&.hpp'\fP
.br
\fC#include 'multiscale/util/iterator/NumberIteratorType\&.hpp'\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmultiscale::video::RectangularCsvToInputFilesConverter\fP"
.br
.RI "\fICsv file to input file converter considering cartesian coordinates\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmultiscale\fP"
.br
.ti -1c
.RI "namespace \fBmultiscale::video\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOUTPUT_EXTENSION\fP   '\&.in'"
.br
.ti -1c
.RI "#define \fBOUTPUT_SEPARATOR\fP   ' '"
.br
.ti -1c
.RI "#define \fBOUTPUT_FILE_SEPARATOR\fP   '_'"
.br
.ti -1c
.RI "#define \fBINPUT_FILE_SEPARATOR\fP   ','"
.br
.ti -1c
.RI "#define \fBERR_NEG_CONCENTRATION\fP   'All concentrations must be non-negative\&.';"
.br
.ti -1c
.RI "#define \fBERR_SELECTED_CONCENTRATION_INDEX\fP   'The selected concentration index (0-based indexing) should be smaller than the number of concentrations\&.'"
.br
.ti -1c
.RI "#define \fBERR_NR_CONCENTRATIONS\fP   'The number of concentrations in the input file does not match the values of the input parameters height and width\&.';"
.br
.ti -1c
.RI "#define \fBERR_NEG_SIM_TIME\fP   'The simulation time must be non-negative\&.'"
.br
.ti -1c
.RI "#define \fBERR_INPUT_OPEN\fP   'The input file could not be opened\&.'"
.br
.ti -1c
.RI "#define \fBERR_INVALID_VALUE_LINE\fP   'Invalid value on line: '"
.br
.ti -1c
.RI "#define \fBERR_INVALID_VALUE_TOKEN\fP   ', value: '"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ERR_INPUT_OPEN   'The input file could not be opened\&.'"

.PP
Definition at line 19 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SS "#define ERR_INVALID_VALUE_LINE   'Invalid value on line: '"

.PP
Definition at line 20 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SS "#define ERR_INVALID_VALUE_TOKEN   ', value: '"

.PP
Definition at line 21 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SS "#define ERR_NEG_CONCENTRATION   'All concentrations must be non-negative\&.';"

.PP
Definition at line 15 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SS "#define ERR_NEG_SIM_TIME   'The simulation time must be non-negative\&.'"

.PP
Definition at line 18 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SS "#define ERR_NR_CONCENTRATIONS   'The number of concentrations in the input file does not match the values of the input parameters height and width\&.';"

.PP
Definition at line 17 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SS "#define ERR_SELECTED_CONCENTRATION_INDEX   'The selected concentration index (0-based indexing) should be smaller than the number of concentrations\&.'"

.PP
Definition at line 16 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SS "#define INPUT_FILE_SEPARATOR   ','"

.PP
Definition at line 13 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SS "#define OUTPUT_EXTENSION   '\&.in'"

.PP
Definition at line 10 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SS "#define OUTPUT_FILE_SEPARATOR   '_'"

.PP
Definition at line 12 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SS "#define OUTPUT_SEPARATOR   ' '"

.PP
Definition at line 11 of file RectangularCsvToInputFilesConverter\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
