.TH "include/multiscale/analysis/spatial/factory/RectangularMatFactory.hpp" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/multiscale/analysis/spatial/factory/RectangularMatFactory.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'multiscale/analysis/spatial/MatFactory\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmultiscale::analysis::RectangularMatFactory\fP"
.br
.RI "\fIClass for creating a Mat object considering a rectangular grid\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmultiscale\fP"
.br
.ti -1c
.RI "namespace \fBmultiscale::analysis\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
