.TH "include/multiscale/video/rectangular/RectangularGnuplotScriptGenerator.hpp" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/multiscale/video/rectangular/RectangularGnuplotScriptGenerator.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmultiscale::video::RectangularGnuplotScriptGenerator\fP"
.br
.RI "\fIGnuplot script generator from the provided concentrations considering a rectangular geometry\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmultiscale\fP"
.br
.ti -1c
.RI "namespace \fBmultiscale::video\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHEADER_IN\fP   'config/video/rectangular/header\&.in'"
.br
.ti -1c
.RI "#define \fBCONTENT_IN\fP   'config/video/rectangular/content\&.in'"
.br
.ti -1c
.RI "#define \fBFOOTER_IN\fP   'config/video/rectangular/footer\&.in'"
.br
.ti -1c
.RI "#define \fBREPLACE_HEADER_FILENAME\fP   'OUTPUT_FILENAME'"
.br
.ti -1c
.RI "#define \fBREPLACE_HEADER_HEIGHT\fP   'OUTPUT_DIMENSION1'"
.br
.ti -1c
.RI "#define \fBREPLACE_HEADER_WIDTH\fP   'OUTPUT_DIMENSION2'"
.br
.ti -1c
.RI "#define \fBREPLACE_HEADER_SIM_TIME\fP   'OUTPUT_SIM_TIME'"
.br
.ti -1c
.RI "#define \fBREPLACE_DIMENSION_EXTRA\fP   0\&.5"
.br
.ti -1c
.RI "#define \fBOUTPUT_SEPARATOR\fP   ' '"
.br
.ti -1c
.RI "#define \fBGNUPLOT_EXTENSION\fP   '\&.plt'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CONTENT_IN   'config/video/rectangular/content\&.in'"

.PP
Definition at line 10 of file RectangularGnuplotScriptGenerator\&.hpp\&.
.SS "#define FOOTER_IN   'config/video/rectangular/footer\&.in'"

.PP
Definition at line 11 of file RectangularGnuplotScriptGenerator\&.hpp\&.
.SS "#define GNUPLOT_EXTENSION   '\&.plt'"

.PP
Definition at line 22 of file RectangularGnuplotScriptGenerator\&.hpp\&.
.SS "#define HEADER_IN   'config/video/rectangular/header\&.in'"

.PP
Definition at line 9 of file RectangularGnuplotScriptGenerator\&.hpp\&.
.SS "#define OUTPUT_SEPARATOR   ' '"

.PP
Definition at line 20 of file RectangularGnuplotScriptGenerator\&.hpp\&.
.SS "#define REPLACE_DIMENSION_EXTRA   0\&.5"

.PP
Definition at line 18 of file RectangularGnuplotScriptGenerator\&.hpp\&.
.SS "#define REPLACE_HEADER_FILENAME   'OUTPUT_FILENAME'"

.PP
Definition at line 13 of file RectangularGnuplotScriptGenerator\&.hpp\&.
.SS "#define REPLACE_HEADER_HEIGHT   'OUTPUT_DIMENSION1'"

.PP
Definition at line 14 of file RectangularGnuplotScriptGenerator\&.hpp\&.
.SS "#define REPLACE_HEADER_SIM_TIME   'OUTPUT_SIM_TIME'"

.PP
Definition at line 16 of file RectangularGnuplotScriptGenerator\&.hpp\&.
.SS "#define REPLACE_HEADER_WIDTH   'OUTPUT_DIMENSION2'"

.PP
Definition at line 15 of file RectangularGnuplotScriptGenerator\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
