.TH "include/multiscale/util/RGBColourGenerator.hpp" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/multiscale/util/RGBColourGenerator.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmultiscale::RGBColourGenerator\fP"
.br
.RI "\fIGenerate a RGB colour\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmultiscale\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHUE_MIN\fP   0"
.br
.ti -1c
.RI "#define \fBHUE_MAX\fP   120"
.br
.ti -1c
.RI "#define \fBSATURATION\fP   1"
.br
.ti -1c
.RI "#define \fBVALUE\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HUE_MAX   120"

.PP
Definition at line 9 of file RGBColourGenerator\&.hpp\&.
.SS "#define HUE_MIN   0"

.PP
Definition at line 8 of file RGBColourGenerator\&.hpp\&.
.SS "#define SATURATION   1"

.PP
Definition at line 10 of file RGBColourGenerator\&.hpp\&.
.SS "#define VALUE   1"

.PP
Definition at line 11 of file RGBColourGenerator\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
