.TH "include/multiscale/util/iterator/StandardNumberIterator.hpp" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/multiscale/util/iterator/StandardNumberIterator.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'multiscale/util/NumberIterator\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmultiscale::StandardNumberIterator\fP"
.br
.RI "\fIIterator class starting at 1 and iterating over all natural numbers until the provided upper bound is reached\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmultiscale\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
