.TH "include/multiscale/util/StringManipulator.hpp" 3 "Sun Mar 17 2013" "Version 0.0.1" "Multiscale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/multiscale/util/StringManipulator.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmultiscale::StringManipulator\fP"
.br
.RI "\fIClass for manipulating strings\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmultiscale\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDIR_SEPARATOR\fP   '/'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DIR_SEPARATOR   '/'"

.PP
Definition at line 8 of file StringManipulator\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Multiscale from the source code\&.
