#ifndef RECTANGULARMATFACTORY_HPP
#define RECTANGULARMATFACTORY_HPP

#include "multiscale/analysis/spatial/MatFactory.hpp"

using namespace std;


namespace multiscale {

    namespace analysis {

        //! Class for creating a Mat object considering a rectangular grid
        class RectangularMatFactory : public MatFactory {

            public:

                RectangularMatFactory();
                ~RectangularMatFactory();

                //! Create a Mat object from the image file obtained from the RectangularGeometryViewer
                /*!
                 * Create the Mat instance from the given image file
                 *
                 *  \param inputFile The path to the image file
                 */
                Mat createFromViewerImage(const string &inputFile) override;

                //! Get the maximum grayscale intensity of the colour bar in the image
                /*!
                 * \param inputFile The path to the image file
                 */
                double maxColourBarIntensityFromViewerImage(const string &inputFile) override;

            protected:

                //! Process the concentrations from the input file
                /*!
                 * Read the concentrations from the input file and return them as an array which can be used
                 * afterwards to create a Mat object from them
                 *
                 * REMARK: The constructor of Mat does not copy the data. Therefore, DO NOT
                 *         deallocate it in this class.
                 *
                 * \param fin Input file stream from which the concentrations are read
                 */
                unsigned char *processConcentrations(ifstream& fin) override;

                //! Check if the image generated by the viewer has the required resolution
                /*!
                 * \param image Image generated by the viewer
                 */
                bool isValidViewerImage(const Mat &image) override;

            private:

                // Constants
                static const string ERR_CONC;

                static const int ROI_START_X;
                static const int ROI_START_Y;
                static const int ROI_WIDTH;
                static const int ROI_HEIGHT;

                static const int INPUT_IMG_WIDTH;
                static const int INPUT_IMG_HEIGHT;

                static const int COLOURBAR_MAX_X;
                static const int COLOURBAR_MAX_Y;

        };

    };

};


#endif
